### PR TITLE
Addresses #1655 NTR 'peripheral blood lymphocyte'

### PR DESCRIPTION
**Pull request by bvarner-ebi**
Addresses #1655 NTR 'peripheral blood lymphocyte'

### CODE REVIEW

**Comment by shawntanzk** [comment]
I have my reservation about this, but I guess @addiehl is the expert here
Could I convince you to switch the label to be blood lymphocyte and have the related synonym be peripheral blood lymphocyte? seems more appropriate given what you mentioned in the related ticket @bvarner-ebi

**Comment by addiehl** [comment]
'peripheral blood lymphocyte' matches usage in the literature better than 'blood lymphocyte'. If we were to make the term 'blood lymphocyte', I guarantee that someone will come along in a year or two and ask for 'peripheral blood lymphocyte'.  I don't mind making 'blood lymphocyte' an exact or related synonym.

**Comment by bvarner-ebi** [comment]
> I don't mind making 'blood lymphocyte' an exact or related synonym.

Perhaps make 'blood lymphocyte' a broad synonym?

**Comment by addiehl** [comment]
'blood lymphocyte' as a broad synonym works for me.

**Comment by bvarner-ebi** [comment]
@addiehl, @shawntanzk, has the latest commit addressed your concerns?

**Comment by shawntanzk** [comment]
> Perhaps make 'blood lymphocyte' a broad synonym?

By logical definition, this should be an exact synonym instead. PS sorry this slipped through the cracks for me

**Comment by bvarner-ebi** [comment]
> By logical definition, this should be an exact synonym instead. 

Do we need to add 'peripheral blood' to Uberon? It seems like the terms 'blood' and 'peripheral blood' have been used without distinction in CL, likely due to the assumptions @addiehl notes [here](https://github.com/obophenotype/cell-ontology/issues/1655#issuecomment-1271747053). 

If CL assumes 'blood' == 'peripheral blood', it seems reasonable to make the label 'blood lymphocyte' to align with the logical definition and make 'peripheral blood lymphocyte' an exact synonym. If CL does not assume 'blood' == 'peripheral blood', then 'peripheral blood lymphocyte' could be a narrow synonym until 'peripheral blood' is added.

Of note, in BTO, ['peripheral blood'](http://purl.obolibrary.org/obo/BTO_0000553) is a subclass of ['blood'](http://purl.obolibrary.org/obo/BTO_0000089).

**Comment by shawntanzk** [comment]
I'd be alright with either solution (exact synonym or adding term to uberon)
but my preference is exact synonym from what @addiehl said; im thinking about annotation - will having both confuse users?

**Comment by bvarner-ebi** [comment]
> 'd be alright with either solution (exact synonym or adding term to uberon)
> but my preference is exact synonym from what @addiehl said; im thinking about annotation - will having both confuse users?

If this will be the solution, it seems to make sense to make "peripheral blood" an exact synonym to "blood". However, I think one should consider if peripheral blood includes blood in the liver, spleen, umbilical cord, placenta, bone marrow, etc. A cursory web search shows results suggesting the latter are not generally considered "peripheral blood".

**Comment by shawntanzk** [comment]
perhaps youre right, creating the new term - even if users use a different term, queries can be done on blood and it would capture peripheral blood if we follow BTO hierarchy. I do like the cleanliness of creating terms and making equivs on them :)

**Comment by addiehl** [comment]
Still working on my thoughts:
Is a 'peripheral blood lymphocyte' really different (more specialized) than a 'blood lymphocyte'?

Note that Uberon has both ['arterial blood'](http://purl.obolibrary.org/obo/UBERON_0013755) and a ['venous blood'](http://purl.obolibrary.org/obo/UBERON_0013756). Ontologically, both of these might be considered subclasses of 'peripheral blood'.  In practice, peripheral blood is usually collected from a vein in humans (clearly peripheral venous blood), but in experiments with animals (such as mice), it might be collected sub-orbitally, from a tail-bleed, or even directly from a heart puncture, in which case it may be a mix of venous and arterial blood or perhaps neither if taken from the heart.

Should Uberon have a 'peripheral blood term' as the logical union of 'arterial blood' and 'venous blood'?

**Comment by bvarner-ebi** [comment]
> Is a 'peripheral blood lymphocyte' really different (more specialized) than a 'blood lymphocyte'?

CL seems to be going in the direction of creating a new class for a cell type when potentially the only difference is anatomical location (see https://github.com/obophenotype/cell-ontology/pull/1722). Based on  that, there could be justification for creating both  'peripheral blood lymphocyte' and 'blood lymphocyte' cell types even when there is not other distinguishing feature other than location.

**Comment by addiehl** [comment]
I think that creating 'blood lymphocyte' with a 'peripheral blood lymphocyte' term is okay just to end this discussion, but we should avoid further subclassing, like 'peripheral blood T cell'. What annotators are really capturing with these terms is the experimental origin of a blood sample, which in an ideal data annotation world would be captured via co-annotation with an OBI term (or something). We don't even have to create a new Uberon term 'peripheral blood'; we can just have 'peripheral blood lymphocyte'
'blood lymphocyte' AND ('located in' some 'arterial blood' OR 'located in' some 'venous blood')

**Comment by bvarner-ebi** [comment]
@addiehl, @shawntanzk, can you kindly review this PR so it gets captured in the next CL release? I believe all concerns have been addressed with the latest commit.

**Comment by shawntanzk** [comment]
never handled a `or` before - hope ELK handles it >.< 
other than that looks alright to me, but I'll leave @addiehl to approve given he is the expert here :)

**Comment by balhoff** [comment]
ELK doesn't support unions. Unions do work for certain purposes in Whelk, but it's not part of OWL EL.

**Comment by shawntanzk** [comment]
awks, guess we need to handle the logic differently then. If you urgently need the term, I would suggest stripping the logical definition and leaving it as textual for now

**Comment by bvarner-ebi** [comment]
> awks, guess we need to handle the logic differently then. If you urgently need the term, I would suggest stripping the logical definition and leaving it as textual for now

Is this going to break something if kept?

**Comment by addiehl** [comment]
There is precedent for use of OR or union of in CL:
[CD34-positive, CD38-positive common myeloid progenitor OR CD34-positive, CD38-positive common lymphoid progenitor](http://purl.obolibrary.org/obo/CL_0000995)
[CD7-negative lymphoid progenitor OR granulocyte monocyte progenitor](http://purl.obolibrary.org/obo/CL_0001012)
[CD115-positive monocyte OR common dendritic progenitor](http://purl.obolibrary.org/obo/CL_0001019)
[CD117-positive common myeloid progenitor OR CD217-positive common lymphoid progenitor](http://purl.obolibrary.org/obo/CL_0001030)

These CL classes are based on DC_CL [PMID:19243617](https://pubmed.ncbi.nlm.nih.gov/19243617/) from 2009, and represent uncertainty in the knowledge of developmental progenitors for dendritic cells at the time. Improving the representation of dendritic cells has been on my radar for a while. Nevertheless, these union classes do not prevent overall reasoning with ELK, but are probably just ignored.

So I see no major issue with the equivalence axiom as proposed for 'peripheral blood lymphocyte', as Jim has pointed out.

**Comment by bvarner-ebi** [comment]
> So I see no major issue with the equivalence axiom as proposed for 'peripheral blood lymphocyte', as Jim has pointed out.

Thank you, @addiehl. In that case, would you approve this PR so I can proceed with a merge?

**Comment by bvarner-ebi** [comment]
After speaking with @dosumis, it seemed the best way to move forward was to replace the EA of 'peripheral blood lymphocyte' with subclass axioms. I also update the text definition.

@addiehl, if this is an agreeable way forward, I will appreciate your approval of the this PR.

**Comment by bvarner-ebi** [comment]
@shawntanzk, @addiehl, @dosumis, unless there are grave concerns with approving this PR, would one of you mind approving it today so it can be incorporated in a CL release, which is planned for tomorrow AM?

**Comment by shawntanzk** [comment]
was super confused for awhile cause the robot diff still shows EA, then I rmbr I just implemented #gogoeditdiff hence it didn't update lol >.< yeah a lot more comfortable with the subclass

**Review by shawntanzk — APPROVED** [review]

**Pull request merged**
