### PR TITLE
Text def Purkinje neuron

### LINKED ISSUE #2176: [Text def] Purkinje neuron
**CL term**

CL:0000121 ; Purkinje cell

**Suggested revision of textual definition**

The current textual definition is embarrassingly bad 

image

Reads as if the cortex has a single type of output neuron!  More detail needed -CellGuide could be good inspiration (although probably too detailed) https://cellxgene.cziscience.com/cellguide/CL_0000121

### PR DESCRIPTION
**Pull request by AvolaAmg**
Fixes #2176

- Expand text definition and references
- Expand the comment section and references
- Add synonyms and references

### CODE REVIEW

**Review by JABelfiore — COMMENTED** [review]
Suggest text amends to the following: 
An inhibitory neuron and the sole output neuron of the cerebellar cortex, the Purkinje cell's soma is located between the granular and molecular layers of the cerebellum. It is one of the largest neural cells in the mammalian brain, ranging from 50 to 80 micrometres in diameter. Purkinje cells have planar, fan-shaped dendrites that branch extensively with little overlap. This cell type receives synaptic input from parallel fibres, which modulate high-frequency spike activity known as \"simple spikes,\" and climbing fibres, which modulate infrequent calcium spike activity known as \"complex spikes\". Purkinje cells are involved in motor coordination, particularly in correcting movements in progress."

Looks good! just minor grammatical changes :)

**Comment by AvolaAmg** [comment]
Thank you @JABelfiore for your review, I will apply the changes. Could you also check the content (references, synonyms etc)? I will ask you to re-review after I change the body of text!

**Comment by AvolaAmg** [comment]
#gogoeditdiff

**Review by JABelfiore — APPROVED** [review]
**Definition references**

Definition references are all great, all claims in the statement are covered by references :)


PMID:12907269 - confirms cell size, confirms complex spikes and calcium involvement

PMID:14568361 - confirms cell location, confirms dendrite shape and branching

PMID:31424738  - confirms sole output neurons of the cerebellar cortex, confirms spike modulation and definitions of simple and complex spikes

PMID:33288911 - confirms cell location, confirms spike modulation, confirms involvement in movement success

PMID:38168772 - confirms dendrite shape, confirms spike modulation 


**Comment text** 

Comment text looks great, just slightly altered wording of the second sentence slightly. Changed fetal (US English) to foetal (UK English)(even though I know the paper you are referencing is US spelling!) 

**Suggested comment amend:** 

Neurodegenerative disorders affecting Purkinje cells disrupt motor functions. Neurodegenerative disorders that causes loss and degeneration of Purkinje cells include: spinocerebellar ataxias (SCAs) (Josef P Kapfhammer and Etsuko Shimobayashi, 2023), Friedreich's ataxia (FRDA) (Kevin C Kemp et al., 2016), foetal alcohol syndrome (Laurent Servais et al., 2016), and Dandy-Walker malformation (Alexander Atamian et al., 2024).

**Comment references** 

Comment references are all great, all claims in the statement are covered by references :)

PMID:17535929 - confirms FAS, confirms disrupts motor functions, confirms contributes to ataxia 

PMID:27215193 - confirms FRDA

PMID:37426070 - confirms SCAs

https://doi.org/10.1016/j.stem.2023.11.013 - confirms dandy-walker malformation 


**Synonym references**

Synonym references are all correct :)

PMID:38168772 hasExactSynonym "PC" - confirms synonym

PMID:28821816 hasExactSynonym "PN"- confirms synonym

PMID:28821816 "Purkinje neuron"- confirms synonym

https://doi.org/10.1016/j.proghi.2004.07.002 "cerebellar Purkinje cell" - confirms synonym

**Review by aleixpuigb — CHANGES_REQUESTED** [review]
Acronyms are related synonyms and should have the annotation property 'abbreviation'.
CL uses US english, please use the US english version 'fetal'.

**Comment by AvolaAmg** [comment]
Hi there, thanks for the reviews!!
I am sticking with fetal, also the 'abbreviation' as an annotation property is present.

**Review by aleixpuigb — APPROVED** [review]

**Pull request merged**
