### PR TITLE
Added L6 FS Large sag PV

### LINKED ISSUE #875: [NTR] L6 FS cell w/ Large sag
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
L6 fast-spiking with large hyperpolarization sag Pvalb GABAergic interneuron of the primary motor cortex (Mus musculus)

**Synonyms**
L6 FS Large sag PV mOP (mus)

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
GABAergic interneuron of Pvalb subclass, found in L6 of the primary motor cortex. Mostly local axons. Some neurons exhibited a horizontally elongated or downward projecting axon mostly innervating L6b. Fast spiking, with large hyperpolarization sag and rebound potential.
PMID:22357664
PMID:31209381

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
GABAergic interneuron

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
http://purl.obolibrary.org/obo/UBERON_0001384 - Primary Motor Cortex
*has some soma location, can specify layer

**Your nano-attribution (ORCID)**

**Any additional notes or concerns**
subclass of Pvalb interneurons #868

### PR DESCRIPTION
**Pull request by shawntanzk**
Fixes obophenotype/provisional_cell_ontology#39

### CODE REVIEW

**Review by patrick-lloyd-ray — COMMENTED** [review]
I'm not sure the 'L' in 'large' should be capitalized, but looks fine otherwise.

**Review by dosumis — CHANGES_REQUESTED** [review]
I think we need some more general discussion - in CL & BDS calls -  of what aspects of e-phys to use as primary ways of distinguishing neuronal types before letting this through.    Label also needs some work.

**Comment by bvarner-ebi** [comment]
Checking in on this PR from Feb 2021 and last action over 1 year ago.

@shawntanzk, can we close, merge or add to CL agenda if more discussion is required?

**Comment by shawntanzk** [comment]
moved ticket over to PCL - term wasn't ready for CL

**Comment by bvarner-ebi** [comment]
> moved ticket over to PCL - term wasn't ready for CL

Should this PR be moved too: https://github.com/obophenotype/cell-ontology/pull/920

**Pull request closed without merging**
