### PR TITLE
Lung hackathon - epithelial cells

### PR DESCRIPTION
**Pull request by aleixpuigb**
This is an ongoing PR for the lung hackaton
Create equivalentTo in endo-epithelial cell and fix 'respiratory epithelial cell'

### CODE REVIEW

**Comment by aleixpuigb** [comment]
#gogoeditdiff

**Comment by dosumis** [comment]
#gogoeditdiff

**Comment by dosumis** [comment]
#gogoeditdiff

**Comment by dosumis** [comment]
Fixes:  #2376 #2378 #2379

**Comment by aleixpuigb** [comment]
@AvolaAmg I have gone through and it looks ok.
Note: [epithelial cell of alveolus of lung](http://purl.obolibrary.org/obo/CL_0010003) probably should be merged to [pulmonary alveolar epithelial cell](http://purl.obolibrary.org/obo/CL_0000322). A new ticket is required.

**Comment by AvolaAmg** [comment]
@aleixpuigb thanks for your comment, I can open that new ticket and approve the changes on this one.

**Review by AvolaAmg — APPROVED** [review]

**Pull request merged**
