### PR TITLE
added lateral ganglionic eminence derived neuron

### LINKED ISSUE #2255: [NTR] lateral ganglionic eminence derived neuron
Please check that the term does not already exist by using the ontology search tool OLS:
https://www.ebi.ac.uk/ols4/ontologies/cl

**Preferred term label**

lateral ganglionic eminence derived neuron

**Synonyms** (add reference(s), please)

**Definition** (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX)

Neuron derived from precursor cell in the lateral ganglion eminence.

https://en.wikipedia.org/wiki/Ganglionic_eminence#Lateral_ganglionic_eminence_(LGE)

**Parent cell type term** (check the hierarchy here https://www.ebi.ac.uk/ols4/ontologies/cl)

**Anatomical structure where the cell type is found** (check Uberon for anatomical structures: https://www.ebi.ac.uk/ols4/ontologies/uberon)

**Your ORCID**

**Additional notes or concerns**

Needed as general grouping term.

### PR DESCRIPTION
**Pull request by shawntanzk**
Fixes #2255

I followed CL:4023079 for logical definition - not sure if we need to add the precursor part (I think it is slightly redundant too and will probably involve more complexity with blank nodes and all than actually needed) 

#gogoeditdiff

### CODE REVIEW

**Comment by shawntanzk** [comment]
does #gogoeditdiff not work here anymore? :(

**Comment by shawntanzk** [comment]
ok ignore me, it does, I see its running in actions, just thought it showed in the pr too heh

**Review by dosumis — CHANGES_REQUESTED** [review]
> [CL_4023035](http://purl.obolibrary.org/obo/CL_4023035) [definition](http://purl.obolibrary.org/obo/IAO_0000115) "A neuron that is derived from precursor cell in the lateral ganglion eminence."
> 
> [comment](http://www.w3.org/2000/01/rdf-schema#comment) "wikipediaversioned:Ganglionic_eminence&oldid=1186824360"

comment --> xref

Other than that - looks good to me.

**Comment by shawntanzk** [comment]
Thanks @dosumis & @aleixpuigb - soz for the silly mistakes, was focusing more on the setting up everything in the VM and all so super distracted lol, anyway fixed :)

**Comment by anitacaron** [comment]
@aleixpuigb I checked the merged_import, and it's all from the last Uberon release with many changes in the synonym type.

**Pull request merged**
