### PR TITLE
Fixing lung multiciliated cell heirarchy

### LINKED ISSUE #432: should "lung ciliated cell" be a type of "multi-ciliated epithelial cell"
I was surprised to see that GO:0061141 "lung ciliated cell differentiation"  does not have a relationship to GO:1903251 "multi-ciliated epithelial cell differentiation".

I see in the definition of "lung ciliated cell differentiation" that it says "a motile cilium". However, I am under the impression that lung epithelial cells, as with other types of epithelial cells that are involved in moving fluids, are multiciliated cells.

GO:0061141: "lung ciliated cell differentiation"
Def: The process in which a relatively unspecialized cell acquires specialized features of a lung ciliated cell. A lung ciliated cell is a specialized lung epithelial cell that contains a motile cilium for moving substances released from lung secretory cells.

Chris Mungall has asked me to report this here, so please consider if "lung ciliated cell" should be a type of "multi-ciliated epithelial cell"

thanks,

-Karen

### PR DESCRIPTION
**Pull request by dosumis**
Fixed by aligning both textual and logical defs
Fixes #432
Note - classification of "bronchus ciliated cell" under lung will be fixed by https://github.com/obophenotype/uberon/issues/3410

### CODE REVIEW

**Comment by dosumis** [comment]
#gogoeditdiff

**Review by aleixpuigb — APPROVED** [review]
Everything looks good.
Note - In the diff report 'has characteristics' is substituted by 'bearer of', but the URL is correct for 'has characteristic'.

> Note - classification of "bronchus ciliated cell" under lung will be fixed by https://github.com/obophenotype/uberon/issues/3410

I have already commented in the ticket, but not all bronchus, i.e., main bronchus, are part of the lung.

**Comment by Caroline-99** [comment]
Noticed a minor typo in the respiratory ciliated cell - will change it now

**Comment by gouttegd** [comment]
@dosumis Here’s the diff computed on the `-simple` artefact:

<details>
# Ontology comparison

## Left
- Ontology IRI: `http://purl.obolibrary.org/obo/cl/cl-simple.owl`
- Version IRI: `http://purl.obolibrary.org/obo/cl/releases/2024-11-07/cl-simple.owl`
- Loaded from: `file:/Users/dpg44/Curation/Ontologies/repositories/CL/src/ontology/master/cl-simple.owl`

## Right
- Ontology IRI: `http://purl.obolibrary.org/obo/cl/cl-simple.owl`
- Version IRI: `http://purl.obolibrary.org/obo/cl/releases/2024-11-07/cl-simple.owl`
- Loaded from: `file:/Users/dpg44/Curation/Ontologies/repositories/CL/src/ontology/pr/cl-simple.owl`

### Ontology imports 



### Ontology annotations 



### ciliated cell of the bronchus `http://purl.obolibrary.org/obo/CL_0002332`
#### Removed
- [ciliated cell of the bronchus](http://purl.obolibrary.org/obo/CL_0002332) [definition](http://purl.obolibrary.org/obo/IAO_0000115) "A ciliated cell of the bronchus." 
  - [database_cross_reference](http://www.geneontology.org/formats/oboInOwl#hasDbXref) "GOC:tfm" 

  - [database_cross_reference](http://www.geneontology.org/formats/oboInOwl#hasDbXref) "PMID:18757316" 

#### Added
- [ciliated cell of the bronchus](http://purl.obolibrary.org/obo/CL_0002332) [definition](http://purl.obolibrary.org/obo/IAO_0000115) "A multi-ciliated epithelial cell located or the bronchus epithelium, characterized by a columnar shape and motile cilia on its apical surface." 
  - [database_cross_reference](http://www.geneontology.org/formats/oboInOwl#hasDbXref) "GOC:tfm" 

  - [database_cross_reference](http://www.geneontology.org/formats/oboInOwl#hasDbXref) "PMID:18757316" 


### ciliated columnar cell of tracheobronchial tree `http://purl.obolibrary.org/obo/CL_0002145`
#### Removed
- [ciliated columnar cell of tracheobronchial tree](http://purl.obolibrary.org/obo/CL_0002145) SubClassOf [multi-ciliated epithelial cell](http://purl.obolibrary.org/obo/CL_0005012) 



### lung ciliated cell `http://purl.obolibrary.org/obo/CL_1000271`
#### Removed
- [lung ciliated cell](http://purl.obolibrary.org/obo/CL_1000271) SubClassOf [ciliated epithelial cell](http://purl.obolibrary.org/obo/CL_0000067) 



### respiratory ciliated cell `http://purl.obolibrary.org/obo/CL_4030034`
#### Removed
- [respiratory ciliated cell](http://purl.obolibrary.org/obo/CL_4030034) [definition](http://purl.obolibrary.org/obo/IAO_0000115) "A ciliated cell of the respiratory system. Ciliated cells are present in airway epithelium." 
  - [database_cross_reference](http://www.geneontology.org/formats/oboInOwl#hasDbXref) "PMID:21364219" 

  - [database_cross_reference](http://www.geneontology.org/formats/oboInOwl#hasDbXref) "PMID:18757316" 

- [respiratory ciliated cell](http://purl.obolibrary.org/obo/CL_4030034) SubClassOf [ciliated cell](http://purl.obolibrary.org/obo/CL_0000064) 

#### Added
- [respiratory ciliated cell](http://purl.obolibrary.org/obo/CL_4030034) [definition](http://purl.obolibrary.org/obo/IAO_0000115) "A multi-ciliated epithelial cell located or the respiratory tract epithelium, characterized by a columnar shape and motile cilia on its apical surface." 
  - [database_cross_reference](http://www.geneontology.org/formats/oboInOwl#hasDbXref) "PMID:21364219" 

  - [database_cross_reference](http://www.geneontology.org/formats/oboInOwl#hasDbXref) "PMID:18757316" 

- [respiratory ciliated cell](http://purl.obolibrary.org/obo/CL_4030034) SubClassOf [multi-ciliated epithelial cell](http://purl.obolibrary.org/obo/CL_0005012) 

- [respiratory ciliated cell](http://purl.obolibrary.org/obo/CL_4030034) SubClassOf [respiratory epithelial cell](http://purl.obolibrary.org/obo/CL_0002368) 

</details>

The `-simple` diff does not show any more difference on the inferred classification than the `-base` diff. What were you expecting to see?

For clarity, here is a terse version of the `-simple` diff (I’ve left aside the _AnnotationAssertion_ axioms):

<details><summary>Axioms diff on -simple</summary>

```
5 axioms in left ontology but not in right ontology:
- SubClassOf(<http://purl.obolibrary.org/obo/CL_0002145> <http://purl.obolibrary.org/obo/CL_0005012>)
- SubClassOf(<http://purl.obolibrary.org/obo/CL_1000271> <http://purl.obolibrary.org/obo/CL_0000067>)
- SubClassOf(<http://purl.obolibrary.org/obo/CL_4030034> <http://purl.obolibrary.org/obo/CL_0000064>)

4 axioms in right ontology but not in left ontology:
+ SubClassOf(<http://purl.obolibrary.org/obo/CL_4030034> <http://purl.obolibrary.org/obo/CL_0002368>)
+ SubClassOf(<http://purl.obolibrary.org/obo/CL_4030034> <http://purl.obolibrary.org/obo/CL_0005012>)
```
</details>

And a terse version of the `-base` diff:

<details><summary>Axioms diff on -base</summary>

```
9 axioms in left ontology but not in right ontology:
- EquivalentClasses(<http://purl.obolibrary.org/obo/CL_0002332> ObjectIntersectionOf(<http://purl.obolibrary.org/obo/CL_0000064> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/UBERON_0002031>)))
- EquivalentClasses(<http://purl.obolibrary.org/obo/CL_1000271> ObjectIntersectionOf(<http://purl.obolibrary.org/obo/CL_0000067> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/UBERON_0000115>)))
- EquivalentClasses(<http://purl.obolibrary.org/obo/CL_4030034> ObjectIntersectionOf(<http://purl.obolibrary.org/obo/CL_0000064> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/UBERON_0004802>)))
- SubClassOf(<http://purl.obolibrary.org/obo/CL_0002145> <http://purl.obolibrary.org/obo/CL_0005012>)
- SubClassOf(<http://purl.obolibrary.org/obo/CL_1000271> <http://purl.obolibrary.org/obo/CL_0000067>)
- SubClassOf(<http://purl.obolibrary.org/obo/CL_4030034> <http://purl.obolibrary.org/obo/CL_0000064>)
- SubClassOf(<http://purl.obolibrary.org/obo/CL_4030034> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/UBERON_0004802>))

8 axioms in right ontology but not in left ontology:
+ EquivalentClasses(<http://purl.obolibrary.org/obo/CL_0002145> ObjectIntersectionOf(<http://purl.obolibrary.org/obo/CL_0000075> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/UBERON_0008397>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000051> <http://purl.obolibrary.org/obo/GO_0031514>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0000053> <http://purl.obolibrary.org/obo/PATO_0010007>)))
+ EquivalentClasses(<http://purl.obolibrary.org/obo/CL_0002332> ObjectIntersectionOf(<http://purl.obolibrary.org/obo/CL_0000075> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/UBERON_0002031>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000051> <http://purl.obolibrary.org/obo/GO_0031514>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0000053> <http://purl.obolibrary.org/obo/PATO_0010007>)))
+ EquivalentClasses(<http://purl.obolibrary.org/obo/CL_1000271> ObjectIntersectionOf(<http://purl.obolibrary.org/obo/CL_0000075> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/UBERON_0000115>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000051> <http://purl.obolibrary.org/obo/GO_0031514>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0000053> <http://purl.obolibrary.org/obo/PATO_0010007>)))
+ EquivalentClasses(<http://purl.obolibrary.org/obo/CL_4030034> ObjectIntersectionOf(<http://purl.obolibrary.org/obo/CL_0000075> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000050> <http://purl.obolibrary.org/obo/UBERON_0004802>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000051> <http://purl.obolibrary.org/obo/GO_0031514>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0000053> <http://purl.obolibrary.org/obo/PATO_0010007>)))
+ SubClassOf(<http://purl.obolibrary.org/obo/CL_4030034> <http://purl.obolibrary.org/obo/CL_0002368>)
+ SubClassOf(<http://purl.obolibrary.org/obo/CL_4030034> <http://purl.obolibrary.org/obo/CL_0005012>)
```
</details>

The `-simple` product does not contain any classification that is not also present in `-base`.

**Comment by Caroline-99** [comment]
@dosumis -  I wanted to give you a heads-up—I was running the imports in a different branch, but then I switched over to review/make changes to the lung multiciliated cell PR and accidentally merged the imports into this branch. I don't think it will cause problems, but let me know if you want me to adjust anything.

**Comment by dosumis** [comment]
I think I was confused by deleted asserted axioms being inferred
Before
image
image
After
image

I still think the diffs with simple are a bit easier to work with - as we have all of the asserted logical axioms but with labels in the edit file diff.

Note - I've updated one more term to follow the pattern.

**Comment by Caroline-99** [comment]
#gogoeditdiff

**Review by Caroline-99 — APPROVED** [review]

**Pull request merged**
