### PR TITLE
Remove `replaced_by` property from comment

### LINKED ISSUE #1531: Remove `replaced_by` property from inside `rdfs:comment`
One example:
Screenshot 2022-04-04 at 11 38 06

### PR DESCRIPTION
**Pull request by anitacaron**
Fixes #1531

### CODE REVIEW

**Comment by matentzn** [comment]
I think the range of IAO:is_replaced_by should be <IRI>, not string:

https://api.triplydb.com/s/feEAL1q-d

**Comment by shawntanzk** [comment]
everythign should be in IRI

**Comment by anitacaron** [comment]
Ping @matentzn

**Comment by anitacaron** [comment]
Yes, many diffs. Only related to `xsd:string` that was removed in some annotations `oboInOwl:hasDbXref`.

**Comment by matentzn** [comment]
Can you run https://obophenotype.github.io/cell-ontology/Fixing_xsdstring_diffs/

Still any diffs?

**Comment by anitacaron** [comment]
Only the order of the changes I created is different now.

**Comment by matentzn** [comment]
Did you commit the changed order? So we don't get diffs later?

**Review by matentzn — APPROVED** [review]
Excellent job!

**Pull request merged**
