### PR TITLE
New terms and edits for SCA

### PR DESCRIPTION
**Pull request by paolaroncaglia**
Addresses #974 , #975 , #987 , #988 and #1254

### CODE REVIEW

**Comment by paolaroncaglia** [comment]
Hi @shawntanzk (cc @matentzn ),
These are the new terms I'd like to bring into today's release (plus a couple of typo fixes), but the PR also contains some edits I didn't do today. Some of the extra changes revert edits I did in the past; other pertains to other terms some of which are neurons. I can't merge the PR as is. Would you please be available to take a look and help me see where the problem may be? Thanks in advance!
Paola

**Comment by shawntanzk** [comment]
I see some of my changes in there - seems that something went out of sync, I think the changes made are from an old version and fix has been done since, and somehow a merge with master didnt solve that. I would discard all changes that you didn't make - went through them already and seems like they are all trying to revert back to pre-fix

**Comment by paolaroncaglia** [comment]
I will list here the edits I _didn't_ do today:

- # Class: obo:CL_0000029 (neural crest derived neuron)
+ # Class: obo:CL_0000029 (neuron neural crest derived)
[can't remember who did this]

- # Class: obo:CL_0009009 (paneth cell of colon)
+ # Class: obo:CL_0009009 (paneth cell of epithelium of large intestine)
[this would revert a previous edit of mine, so really not wanted]

- # Class: obo:CL_0009011 (transit amplifying cell of colon)
+ # Class: obo:CL_0009011 (transit amplifying cell of large intestine)
[this would revert a previous edit of mine, so really not wanted]

- # Class: obo:CL_0009025 (mesothelial cell of colon)
+ # Class: obo:CL_0009025 (mesothelial cell of large intestine)
[this would revert a previous edit of mine, so really not wanted]

- # Class: obo:CL_0011003 (magnocellular neurosecretory cell)
+ # Class: obo:CL_0011003 (magnocellular neurosecretory cell (duplicate class))
[can't remember who did this]

- # Class: obo:CL_0011107 (obsolete Muller cell)
+ # Class: obo:CL_0011107 (Muller cell)
[can't remember who did this]

- # Class: obo:CL_0011112 (obsolete magnocellular neurosecretory cell)
+ # Class: obo:CL_0011112 (magnocellular neurosecretory cell)
[can't remember who did this]

- # Class: obo:CL_2000096 (fibroblast of the reticular layer of dermis)
+ # Class: obo:CL_2000096 (reticular layer of dermis fibroblast)
[can't remember who did this]

**Comment by paolaroncaglia** [comment]
@shawntanzk 
Thanks! Your edits in 'Revert wrong commits' are indeed the right ones.

**Pull request merged**
