### PR TITLE
add term CL_0011032 (lysosome-rich enterocyte)

### LINKED ISSUE #693: [NTR]  Lysosome-Rich Enterocytes
**Preferred term label:**
Lysosome-Rich Enterocytes

**Synonyms**
LRE
vacuolated enterocytes (Broad) 

**Definition (free text, please give PubMed ID)**

PMID:31474562

Enterocytes  that possess a large supranuclear vacuolar system  that  preferentially internalize dietary protein via receptor-mediated and fluid-phase endocytosis for intracellular digestion and trans-cellular transport.  In zebrafish these cells are located in the posterior region of the mid intestine throughout life.  In mammals thy are found in the ileum pre-weaning and later are replaced by mature enterocytes .  

**Parent term**
enterocyte CL:0000584

**Your nano-attribution (ORCID)**
ORCID 0000-0002-2244-7917
ORCID ID: 0000-0002-1009-339X
 

Note these are is_enterocyte since the same cell type is found in different locations in different species due to differences in intestinal development and morphology.

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
close #693

### CODE REVIEW

**Review by paolaroncaglia — COMMENTED** [review]
Hi @nicolevasilevsky ,
There are typos in the def, and xsd:strings may be cleaned up to make the diff more readable, but other than that I think it's good. Thanks.

**Comment by nicolevasilevsky** [comment]
thanks @paolaroncaglia. Fixed!

**Comment by nicolevasilevsky** [comment]
would you mind approving this?

**Review by paolaroncaglia — COMMENTED** [review]
Hi @nicolevasilevsky ,
This tiny typo is left at the end of the definition: "In mammals thy are found..."
Once that's fixed, please feel free to merge - or do you need approval?

**Comment by nicolevasilevsky** [comment]
thanks @paolaroncaglia. I fixed the typo. I will merge once this passes.

**Pull request merged**
