### PR TITLE
obsolete glial cell (sensu Nematoda and Protostomia) and glial cell (…

### LINKED ISSUE #715: obsolete glial cell sensu X
spot the obvious problem:

image

this will be fixed by the axiomatization I am doing (#707) and by fixing the pipeline (#709) which will place the hippocampal ones under veterbrate..

yet the idea of making groupings under glial cell for "Vertebrates" and "Protostomes + Nematodes" is arbitrary and weird and hard to maintain and goes back to CL 2005. We should just obsolete these groupings

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
…sensu Vertebrata)

closes #715

### CODE REVIEW

**Review by dosumis — APPROVED** [review]
I'm not even sure the only child terms are even glial cells.

**Comment by dosumis** [comment]
This seems to have resulted in some glial cell types floating to the top.  

image


I'll hot fix on master.

I thought we had a test for that  @matentzn ?  GuessI should always check branch in Protege before merging.

**Comment by matentzn** [comment]
No for this case, there was no test; but I think it is a great idea. Would you say the test is best described as: no class in the cl namespace other than the root can have less than one superclass?

**Comment by dosumis** [comment]
> no class in the cl namespace other than the root can have less than one superclass?

Sounds good.

**Comment by cmungall** [comment]
can we not generalize this? Every ontology could define expected roots with
a standardized AP. This would be useful other places, e.g. OLS; An option
in Protege to open-to-roots or center-to-roots. ROBOT can also use this in
checks. It can also be used to check nothing goes wrong in making the
import as it often does

**Comment by matentzn** [comment]
We already have that rolled out widely: IAO:0000700 

We could generally check that classes in the base namespace must be under a preferred root class.

**Pull request merged**
