### PR TITLE
[DO NOT MERGE] Revert GO mirror

### LINKED ISSUE #1378: Revert  GO MIRROR in cl.Makefile
```
mirror/go.owl: mirror/go.trigger
	echo "WARNING OVERWRITING GO MIRROR BECAUSE OF OBSOLETE CL TERM"
	if [ $(MIR) = true ] && [ $(IMP) = true ]; then curl -L $(URIBASE)/go/go-base.owl --create-dirs -o mirror/go.owl --retry 4 --max-time 200 && $(ROBOT) remove -i mirror/go.owl --term "CL:0000243" --preserve-structure false convert -o $@.tmp.owl && mv $@.tmp.owl $@; fi
.PRECIOUS: mirror/go.owl
```

Should be reverted when GO replaces `CL:0000243`.

@rays22 can you check if http://purl.obolibrary.org/obo/go/go-base.owl still uses CL:0000243? If so, make sure there is an issue on the GO repo and link it here.

### PR DESCRIPTION
**Pull request by shawntanzk**
Fixes #1378
@matentzn I wasn't sure if merged needed to be refreshed (seems like it didnt) but anyway basically refreshed all imports

### CODE REVIEW

**Comment by matentzn** [comment]
I would recommend not to update anything other then merged import, just because this will just cause the size of the repo to go out of proportions.. There are so many added axioms; it will be many MB added without any functional reason. but the fact that there is no diff on merged is odd. What command did you use?

**Comment by shawntanzk** [comment]
happy to close this PR and just run `no-mirror-refresh-merged`

**Comment by matentzn** [comment]
You dont need to run `no-mirror-refresh-imports` ever again (update docs?), but for this ticket, you cant keep the no-mirror, as we do need to at the very list redownload the GO mirror. You could do: 

```
sh run.sh make mirror/go.owl
sh run.sh make no-mirrors-refresh-merged
```

Thats all I think! Feel free to make a new PR and close this one! Either way is fine, but I would not commit unnecessary files.

**Comment by shawntanzk** [comment]
@matentzn oh yeah, sorry, didnt even think about that >.< my bad lol will fix

**Comment by shawntanzk** [comment]
@matentzn done - ps does this mean that import files are no longer used at all? like merge builds independently to import files?

**Comment by shawntanzk** [comment]
```
! grep "! obsolete" cl.obo
intersection_of: has_input CL:0000243 ! obsolete glial cell (sensu Vertebrata)
relationship: has_input CL:0000243 ! obsolete glial cell (sensu Vertebrata)
cl.Makefile:256: recipe for target 'test_obsolete' failed
make: *** [test_obsolete] Error 1
```
looks like the obsolete class is still there @rays22 - ill check if this is from GO

**Comment by shawntanzk** [comment]
it's coming from http://purl.obolibrary.org/obo/GO_0061900

**Comment by shawntanzk** [comment]
@matentzn i've just downloaded go.owl straight from the GO and it doesn't have CL_0000243, but the one i downloaded from mirror has - was wondering if its a base file issue?

**Comment by matentzn** [comment]
no go.owl is entirely different than go-base.owl. I would make a an issue on the GO https://github.com/geneontology/go-ontology/issues saying that GO Base contains the obsolete CL:0000243, tag @balhoff and ask them to replace it.

**Comment by shawntanzk** [comment]
Issue should be resolved in the next GO release

**Comment by shawntanzk** [comment]
yay! everything is passing, happy for you to merge this in @matentzn

**Review by matentzn — APPROVED** [review]

**Pull request merged**
