### PR TITLE
2021-08-06 Release

### PR DESCRIPTION
**Pull request by matentzn**
This required some hacking, I will explain you another time what it was.. Not an easy fix.

### CODE REVIEW

**Comment by shawntanzk** [comment]
> This required some hacking, I will explain you another time what it was.. Not an easy fix.

basically same problem I had of duplicating entries - happens when I imported uberon in.

**Comment by shawntanzk** [comment]
Release Notes:

New Terms:
enteroendocrine cell of small intestine
colon macrophage
colon goblet cell
stromal cell of lamina propria of colon
tuft cell of colon
enteroendocrine cell of colon
intestinal crypt stem cell of colon
lymphocyte of small intestine lamina propria
B cell of medullary sinus of lymph node
T cell of medullary sinus of lymph node
macrophage of medullary sinus of lymph node
anorectum macrophage
B cell of anorectum
T cell of anorectum
smooth muscle cell of anorectum
stromal cell of anorectum lamina propria
microfold cell of epithelium proper of anorectum
paneth cell of anorectum
transit amplifying cell of anorectum
anorectum goblet cell
enterocyte of anorectum
intestinal crypt stem cell of anorectum
enteroendocrine cell of anorectum
tuft cell of anorectum
stratified squamous epithelial cell of anal canal
dynamic gamma motor neuron
static gamma motor neuron
arachnoid barrier cell

Name Changes:
neuron neural crest derived -> neural crest derived neuron
paneth cell of epithelium of large intestine -> paneth cell of colon
transit amplifying cell of large intestine -> transit amplifying cell of colon
mesothelial cell of large intestine -> mesothelial cell of colon
reticular layer of dermis fibroblast -> fibroblast of the reticular layer of dermis

Fixes:
various spelling errors fixed 
Edited synonyms of L5 ET more accurately

**Comment by shawntanzk** [comment]
Hi @matentzn found some issues in cl-full.obo 
Seems that certain things are duplicated, and old things that should be changed instead have duplicate entries, 
here are some examples of that: 

ln 3098 - 3099: there are 2 defs, one with [GOC:tfm] one without
ln 26540 - 26541: there are 2 defs, one with orcid and pmid, one without 
ln 26733 - 26734: there are 2 defs, one with orcid one without
ln 27763 - 27754: same issues as above
ln 33933: this should not be there, it was edited to be changed to def instead of x-ref

Haven't gone through the whole file diffs, but i assume there are more like the above.

**Comment by shawntanzk** [comment]
@matentzn oh nvm, you know about it already I see that the changes in the fix arent to the CL files

**Comment by shawntanzk** [comment]
just a heads up, cl.owl file still has duplicate entries (see example): 
Screenshot 2021-08-10 at 07 31 41
Doesn't exist in cl-edit.owl though :)

**Comment by matentzn** [comment]
I made a new PR, but the problem still exists #1220 

I don't see how duplicates are being removed. Can you check that branch, and check whether their are duplicate definitions in cl-edit.owl, cl.owl and cl-base.owl?

**Pull request merged**
