### PR TITLE
Change part_of to has_soma_location for neuronss

### PR DESCRIPTION
**Pull request by shawntanzk**
Changed part_of relation to has_soma_location for neurons and added subclassOf PNS neuron for cardiac neuron and kidney nerve cell

Fixes https://github.com/obophenotype/cell-ontology/issues/1537

### CODE REVIEW

**Comment by shawntanzk** [comment]
Went through reasoned diff - only 2 things that might be problematic, the rest are positive changes (more accurate classifications) 

problematic removals:
[retinal bipolar neuron](http://purl.obolibrary.org/obo/CL_0000748) SubClassOf [retinal cell](http://purl.obolibrary.org/obo/CL_0009004)

Removal that might have to look into: 
[vomeronasal sensory neuron](http://purl.obolibrary.org/obo/CL_1001561) SubClassOf [neuronal receptor cell](http://purl.obolibrary.org/obo/CL_0000006)

**Comment by shawntanzk** [comment]
> Removal that might have to look into:
> [vomeronasal sensory neuron](http://purl.obolibrary.org/obo/CL_1001561) SubClassOf [neuronal receptor cell](http://purl.obolibrary.org/obo/CL_0000006)

Don't think this is not a problem - it s now subclass of sensory neuron which is a parent of neuronal receptor cell - not sure why this caused the change though

**Review by paolaroncaglia — COMMENTED** [review]
@shawntanzk I'll comment

**Comment by paolaroncaglia** [comment]
@shawntanzk 

> Went through reasoned diff - only 2 things that might be problematic, the rest are positive changes (more accurate classifications)

Agreed. The reasoned diff makes it look like there may be a few redundant subclasses, e.g. midbrain dopaminergic neuron, neocortex basket cell, but I think that's all ok?

> problematic removals: [retinal bipolar neuron](http://purl.obolibrary.org/obo/CL_0000748) SubClassOf [retinal cell](http://purl.obolibrary.org/obo/CL_0009004)

Yes, that was the one I noticed too. Don't want to lose that info.

> Removal that might have to look into: [vomeronasal sensory neuron](http://purl.obolibrary.org/obo/CL_1001561) SubClassOf [neuronal receptor cell](http://purl.obolibrary.org/obo/CL_0000006)

Not sure about that one. Thanks.

**Comment by shawntanzk** [comment]
Screenshot 2022-04-08 at 11 07 36
seems like 'part of' relationship is required to get the inference right, 2 suggestions to fix this:
1) assert retinal bipolar neuron as retinal cell
2) change retinal cell to use 'has soma location' -> im against this as not all neural cells are neurons (eg retinal blood vessel endothelial cell) - think it might break more than it fixes

**Comment by paolaroncaglia** [comment]
@shawntanzk 

> seems like 'part of' relationship is required to get the inference right, 2 suggestions to fix this:
> 1. assert retinal bipolar neuron as retinal cell
> 2. change retinal cell to use 'has soma location' -> im against this as not all neural cells are neurons (eg retinal blood vessel endothelial cell) - think it might break more than it fixes

Agreed that 1. seems safer and more biologically accurate than 2.

**Comment by shawntanzk** [comment]
hmmm seems like assert retinal bipolar neuron as retinal cell has a lot more implications - will go figure this out

**Comment by shawntanzk** [comment]
Not sure why it showed too long diff when ran automatically - have tried rerunning actions
Anyway when I have done it manually on my machine, and here's the diff, doest seem to be a problem 

<details>
# Ontology comparison

## Left
- Ontology IRI: `http://purl.obolibrary.org/obo/cl.owl`
- Version IRI: `http://purl.obolibrary.org/obo/cl/releases/2022-04-08/cl.owl`
- Loaded from: `file:/work/src/ontology/cl-master.owl`

## Right
- Ontology IRI: `http://purl.obolibrary.org/obo/cl.owl`
- Version IRI: `http://purl.obolibrary.org/obo/cl/releases/2022-04-08/cl.owl`
- Loaded from: `file:/work/src/ontology/cl-pr.owl`

### Ontology imports 



### Ontology annotations 



### Ammon's horn basket cell `http://purl.obolibrary.org/obo/CL_2000088`
#### Removed
- [Ammon's horn basket cell](http://purl.obolibrary.org/obo/CL_2000088) EquivalentTo [basket cell](http://purl.obolibrary.org/obo/CL_0000118) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [Ammon's horn](http://purl.obolibrary.org/obo/UBERON_0001954)) 

- [Ammon's horn basket cell](http://purl.obolibrary.org/obo/CL_2000088) SubClassOf [hippocampal interneuron](http://purl.obolibrary.org/obo/CL_1001569) 

#### Added
- [Ammon's horn basket cell](http://purl.obolibrary.org/obo/CL_2000088) EquivalentTo [basket cell](http://purl.obolibrary.org/obo/CL_0000118) and ([has soma location](http://purl.obolibrary.org/obo/RO_0002100) some [Ammon's horn](http://purl.obolibrary.org/obo/UBERON_0001954)) 

- [Ammon's horn basket cell](http://purl.obolibrary.org/obo/CL_2000088) SubClassOf [cerebral cortex GABAergic interneuron](http://purl.obolibrary.org/obo/CL_0010011) 

- [Ammon's horn basket cell](http://purl.obolibrary.org/obo/CL_2000088) SubClassOf [hippocampal neuron](http://purl.obolibrary.org/obo/CL_0002608) 


### cerebellar Golgi cell `http://purl.obolibrary.org/obo/CL_0000119`
#### Removed
- [cerebellar Golgi cell](http://purl.obolibrary.org/obo/CL_0000119) SubClassOf [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [cerebellar cortex](http://purl.obolibrary.org/obo/UBERON_0002129) 

- [cerebellar Golgi cell](http://purl.obolibrary.org/obo/CL_0000119) SubClassOf [CARO_0000000](http://purl.obolibrary.org/obo/CARO_0000000) 

#### Added
- [cerebellar Golgi cell](http://purl.obolibrary.org/obo/CL_0000119) SubClassOf [cerebellar neuron](http://purl.obolibrary.org/obo/CL_1001611) 

- [cerebellar Golgi cell](http://purl.obolibrary.org/obo/CL_0000119) SubClassOf [CNS interneuron](http://purl.obolibrary.org/obo/CL_0000402) 

- [cerebellar Golgi cell](http://purl.obolibrary.org/obo/CL_0000119) SubClassOf [has soma location](http://purl.obolibrary.org/obo/RO_0002100) some [cerebellar cortex](http://purl.obolibrary.org/obo/UBERON_0002129) 


### cerebellar granule cell `http://purl.obolibrary.org/obo/CL_0001031`
#### Removed
- [cerebellar granule cell](http://purl.obolibrary.org/obo/CL_0001031) EquivalentTo [granule cell](http://purl.obolibrary.org/obo/CL_0000120) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [cerebellum](http://purl.obolibrary.org/obo/UBERON_0002037)) 

- [cerebellar granule cell](http://purl.obolibrary.org/obo/CL_0001031) SubClassOf [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [cerebellum](http://purl.obolibrary.org/obo/UBERON_0002037) 

#### Added
- [cerebellar granule cell](http://purl.obolibrary.org/obo/CL_0001031) EquivalentTo [granule cell](http://purl.obolibrary.org/obo/CL_0000120) and ([has soma location](http://purl.obolibrary.org/obo/RO_0002100) some [cerebellum](http://purl.obolibrary.org/obo/UBERON_0002037)) 

- [cerebellar granule cell](http://purl.obolibrary.org/obo/CL_0001031) SubClassOf [cerebellar neuron](http://purl.obolibrary.org/obo/CL_1001611) 


### cerebellum basket cell `http://purl.obolibrary.org/obo/CL_2000027`
#### Removed
- [cerebellum basket cell](http://purl.obolibrary.org/obo/CL_2000027) EquivalentTo [basket cell](http://purl.obolibrary.org/obo/CL_0000118) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [cerebellum](http://purl.obolibrary.org/obo/UBERON_0002037)) 

- [cerebellum basket cell](http://purl.obolibrary.org/obo/CL_2000027) SubClassOf [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [cerebellum](http://purl.obolibrary.org/obo/UBERON_0002037) 

- [cerebellum basket cell](http://purl.obolibrary.org/obo/CL_2000027) SubClassOf [CARO_0000000](http://purl.obolibrary.org/obo/CARO_0000000) 

#### Added
- [cerebellum basket cell](http://purl.obolibrary.org/obo/CL_2000027) EquivalentTo [basket cell](http://purl.obolibrary.org/obo/CL_0000118) and ([has soma location](http://purl.obolibrary.org/obo/RO_0002100) some [cerebellum](http://purl.obolibrary.org/obo/UBERON_0002037)) 

- [cerebellum basket cell](http://purl.obolibrary.org/obo/CL_2000027) SubClassOf [cerebellar neuron](http://purl.obolibrary.org/obo/CL_1001611) 

- [cerebellum basket cell](http://purl.obolibrary.org/obo/CL_2000027) SubClassOf [CNS interneuron](http://purl.obolibrary.org/obo/CL_0000402) 


### cerebellum glutamatergic neuron `http://purl.obolibrary.org/obo/CL_2000028`
#### Removed
- [cerebellum glutamatergic neuron](http://purl.obolibrary.org/obo/CL_2000028) EquivalentTo [glutamatergic neuron](http://purl.obolibrary.org/obo/CL_0000679) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [cerebellum](http://purl.obolibrary.org/obo/UBERON_0002037)) 

- [cerebellum glutamatergic neuron](http://purl.obolibrary.org/obo/CL_2000028) SubClassOf [CARO_0000000](http://purl.obolibrary.org/obo/CARO_0000000) 

- [cerebellum glutamatergic neuron](http://purl.obolibrary.org/obo/CL_2000028) SubClassOf [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [cerebellum](http://purl.obolibrary.org/obo/UBERON_0002037) 

#### Added
- [cerebellum glutamatergic neuron](http://purl.obolibrary.org/obo/CL_2000028) EquivalentTo [glutamatergic neuron](http://purl.obolibrary.org/obo/CL_0000679) and ([has soma location](http://purl.obolibrary.org/obo/RO_0002100) some [cerebellum](http://purl.obolibrary.org/obo/UBERON_0002037)) 

- [cerebellum glutamatergic neuron](http://purl.obolibrary.org/obo/CL_2000028) SubClassOf [cerebellar neuron](http://purl.obolibrary.org/obo/CL_1001611) 


### dentate gyrus of hippocampal formation basket cell `http://purl.obolibrary.org/obo/CL_2000087`
#### Removed
- [dentate gyrus of hippocampal formation basket cell](http://purl.obolibrary.org/obo/CL_2000087) EquivalentTo [basket cell](http://purl.obolibrary.org/obo/CL_0000118) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [dentate gyrus of hippocampal formation](http://purl.obolibrary.org/obo/UBERON_0001885)) 

- [dentate gyrus of hippocampal formation basket cell](http://purl.obolibrary.org/obo/CL_2000087) SubClassOf [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [dentate gyrus of hippocampal formation](http://purl.obolibrary.org/obo/UBERON_0001885) 

- [dentate gyrus of hippocampal formation basket cell](http://purl.obolibrary.org/obo/CL_2000087) SubClassOf [CARO_0000000](http://purl.obolibrary.org/obo/CARO_0000000) 

#### Added
- [dentate gyrus of hippocampal formation basket cell](http://purl.obolibrary.org/obo/CL_2000087) EquivalentTo [basket cell](http://purl.obolibrary.org/obo/CL_0000118) and ([has soma location](http://purl.obolibrary.org/obo/RO_0002100) some [dentate gyrus of hippocampal formation](http://purl.obolibrary.org/obo/UBERON_0001885)) 

- [dentate gyrus of hippocampal formation basket cell](http://purl.obolibrary.org/obo/CL_2000087) SubClassOf [cerebral cortex GABAergic interneuron](http://purl.obolibrary.org/obo/CL_0010011) 

- [dentate gyrus of hippocampal formation basket cell](http://purl.obolibrary.org/obo/CL_2000087) SubClassOf [has soma location](http://purl.obolibrary.org/obo/RO_0002100) some [dentate gyrus of hippocampal formation](http://purl.obolibrary.org/obo/UBERON_0001885) 


### hippocampal granule cell `http://purl.obolibrary.org/obo/CL_0001033`
#### Removed
- [hippocampal granule cell](http://purl.obolibrary.org/obo/CL_0001033) SubClassOf [has soma location](http://purl.obolibrary.org/obo/RO_0002100) some [Ammon's horn](http://purl.obolibrary.org/obo/UBERON_0001954) 

#### Added
- [hippocampal granule cell](http://purl.obolibrary.org/obo/CL_0001033) SubClassOf [hippocampal neuron](http://purl.obolibrary.org/obo/CL_0002608) 


### hippocampal neuron `http://purl.obolibrary.org/obo/CL_0002608`
#### Removed
- [hippocampal neuron](http://purl.obolibrary.org/obo/CL_0002608) EquivalentTo [CNS neuron (sensu Vertebrata)](http://purl.obolibrary.org/obo/CL_0000117) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [Ammon's horn](http://purl.obolibrary.org/obo/UBERON_0001954)) 

- [hippocampal neuron](http://purl.obolibrary.org/obo/CL_0002608) SubClassOf [CNS neuron (sensu Vertebrata)](http://purl.obolibrary.org/obo/CL_0000117) 
  - [is_inferred](http://www.geneontology.org/formats/oboInOwl#is_inferred) "true" 

- [hippocampal neuron](http://purl.obolibrary.org/obo/CL_0002608) SubClassOf [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [Ammon's horn](http://purl.obolibrary.org/obo/UBERON_0001954) 

#### Added
- [hippocampal neuron](http://purl.obolibrary.org/obo/CL_0002608) EquivalentTo [CNS neuron (sensu Vertebrata)](http://purl.obolibrary.org/obo/CL_0000117) and ([has soma location](http://purl.obolibrary.org/obo/RO_0002100) some [Ammon's horn](http://purl.obolibrary.org/obo/UBERON_0001954)) 

- [hippocampal neuron](http://purl.obolibrary.org/obo/CL_0002608) SubClassOf [neuron of the forebrain](http://purl.obolibrary.org/obo/CL_0012001) 

- [hippocampal neuron](http://purl.obolibrary.org/obo/CL_0002608) SubClassOf [has soma location](http://purl.obolibrary.org/obo/RO_0002100) some [Ammon's horn](http://purl.obolibrary.org/obo/UBERON_0001954) 

- [hippocampal neuron](http://purl.obolibrary.org/obo/CL_0002608) SubClassOf [cerebral cortex neuron](http://purl.obolibrary.org/obo/CL_0010012) 


### hippocampal pyramidal neuron `http://purl.obolibrary.org/obo/CL_1001571`
#### Removed
- [hippocampal pyramidal neuron](http://purl.obolibrary.org/obo/CL_1001571) EquivalentTo [pyramidal neuron](http://purl.obolibrary.org/obo/CL_0000598) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [Ammon's horn](http://purl.obolibrary.org/obo/UBERON_0001954)) 

- [hippocampal pyramidal neuron](http://purl.obolibrary.org/obo/CL_1001571) SubClassOf [CARO_0000000](http://purl.obolibrary.org/obo/CARO_0000000) 

- [hippocampal pyramidal neuron](http://purl.obolibrary.org/obo/CL_1001571) SubClassOf [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [Ammon's horn](http://purl.obolibrary.org/obo/UBERON_0001954) 

- [hippocampal pyramidal neuron](http://purl.obolibrary.org/obo/CL_1001571) SubClassOf [pyramidal neuron](http://purl.obolibrary.org/obo/CL_0000598) 

#### Added
- [hippocampal pyramidal neuron](http://purl.obolibrary.org/obo/CL_1001571) EquivalentTo [pyramidal neuron](http://purl.obolibrary.org/obo/CL_0000598) and ([has soma location](http://purl.obolibrary.org/obo/RO_0002100) some [Ammon's horn](http://purl.obolibrary.org/obo/UBERON_0001954)) 

- [hippocampal pyramidal neuron](http://purl.obolibrary.org/obo/CL_1001571) SubClassOf [cerebral cortex pyramidal neuron](http://purl.obolibrary.org/obo/CL_4023111) 

- [hippocampal pyramidal neuron](http://purl.obolibrary.org/obo/CL_1001571) SubClassOf [has soma location](http://purl.obolibrary.org/obo/RO_0002100) some [Ammon's horn](http://purl.obolibrary.org/obo/UBERON_0001954) 


### hippocampal pyramidal neuron differentiation `http://purl.obolibrary.org/obo/GO_0097432`

#### Added
- [hippocampal pyramidal neuron differentiation](http://purl.obolibrary.org/obo/GO_0097432) SubClassOf [cerebral cortex neuron differentiation](http://purl.obolibrary.org/obo/GO_0021895) 


### kidney nerve cell `http://purl.obolibrary.org/obo/CL_1000606`
#### Removed
- [kidney nerve cell](http://purl.obolibrary.org/obo/CL_1000606) SubClassOf [neuron](http://purl.obolibrary.org/obo/CL_0000540) 

#### Added
- [kidney nerve cell](http://purl.obolibrary.org/obo/CL_1000606) SubClassOf [peripheral nervous system neuron](http://purl.obolibrary.org/obo/CL_2000032) 


### midbrain dopaminergic neuron `http://purl.obolibrary.org/obo/CL_2000097`
#### Removed
- [midbrain dopaminergic neuron](http://purl.obolibrary.org/obo/CL_2000097) EquivalentTo [dopaminergic neuron](http://purl.obolibrary.org/obo/CL_0000700) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [midbrain](http://purl.obolibrary.org/obo/UBERON_0001891)) 

- [midbrain dopaminergic neuron](http://purl.obolibrary.org/obo/CL_2000097) SubClassOf [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [midbrain](http://purl.obolibrary.org/obo/UBERON_0001891) 

#### Added
- [midbrain dopaminergic neuron](http://purl.obolibrary.org/obo/CL_2000097) EquivalentTo [dopaminergic neuron](http://purl.obolibrary.org/obo/CL_0000700) and ([has soma location](http://purl.obolibrary.org/obo/RO_0002100) some [midbrain](http://purl.obolibrary.org/obo/UBERON_0001891)) 

- [midbrain dopaminergic neuron](http://purl.obolibrary.org/obo/CL_2000097) SubClassOf [has soma location](http://purl.obolibrary.org/obo/RO_0002100) some [midbrain](http://purl.obolibrary.org/obo/UBERON_0001891) 

- [midbrain dopaminergic neuron](http://purl.obolibrary.org/obo/CL_2000097) SubClassOf [central nervous system neuron](http://purl.obolibrary.org/obo/CL_2000029) 


### midbrain dopaminergic neuron differentiation `http://purl.obolibrary.org/obo/GO_1904948`

#### Added
- [midbrain dopaminergic neuron differentiation](http://purl.obolibrary.org/obo/GO_1904948) SubClassOf [central nervous system neuron differentiation](http://purl.obolibrary.org/obo/GO_0021953) 


### mitral cell `http://purl.obolibrary.org/obo/CL_1001502`
#### Removed
- [mitral cell](http://purl.obolibrary.org/obo/CL_1001502) SubClassOf [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [olfactory bulb mitral cell layer](http://purl.obolibrary.org/obo/UBERON_0004186) 

#### Added
- [mitral cell](http://purl.obolibrary.org/obo/CL_1001502) SubClassOf [has soma location](http://purl.obolibrary.org/obo/RO_0002100) some [olfactory bulb mitral cell layer](http://purl.obolibrary.org/obo/UBERON_0004186) 


### neocortex basket cell `http://purl.obolibrary.org/obo/CL_2000086`
#### Removed
- [neocortex basket cell](http://purl.obolibrary.org/obo/CL_2000086) EquivalentTo [basket cell](http://purl.obolibrary.org/obo/CL_0000118) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [neocortex](http://purl.obolibrary.org/obo/UBERON_0001950)) 

- [neocortex basket cell](http://purl.obolibrary.org/obo/CL_2000086) SubClassOf [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [neocortex](http://purl.obolibrary.org/obo/UBERON_0001950) 

- [neocortex basket cell](http://purl.obolibrary.org/obo/CL_2000086) SubClassOf [CARO_0000000](http://purl.obolibrary.org/obo/CARO_0000000) 

#### Added
- [neocortex basket cell](http://purl.obolibrary.org/obo/CL_2000086) EquivalentTo [basket cell](http://purl.obolibrary.org/obo/CL_0000118) and ([has soma location](http://purl.obolibrary.org/obo/RO_0002100) some [neocortex](http://purl.obolibrary.org/obo/UBERON_0001950)) 

- [neocortex basket cell](http://purl.obolibrary.org/obo/CL_2000086) SubClassOf [has soma location](http://purl.obolibrary.org/obo/RO_0002100) some [neocortex](http://purl.obolibrary.org/obo/UBERON_0001950) 

- [neocortex basket cell](http://purl.obolibrary.org/obo/CL_2000086) SubClassOf [cerebral cortex GABAergic interneuron](http://purl.obolibrary.org/obo/CL_0010011) 


### periglomerular cell `http://purl.obolibrary.org/obo/CL_1001435`
#### Removed
- [periglomerular cell](http://purl.obolibrary.org/obo/CL_1001435) SubClassOf [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [olfactory bulb glomerular layer](http://purl.obolibrary.org/obo/UBERON_0005377) 

#### Added
- [periglomerular cell](http://purl.obolibrary.org/obo/CL_1001435) SubClassOf [has soma location](http://purl.obolibrary.org/obo/RO_0002100) some [olfactory bulb glomerular layer](http://purl.obolibrary.org/obo/UBERON_0005377) 


### retinal bipolar neuron `http://purl.obolibrary.org/obo/CL_0000748`
#### Removed
- [retinal bipolar neuron](http://purl.obolibrary.org/obo/CL_0000748) EquivalentTo [bipolar neuron](http://purl.obolibrary.org/obo/CL_0000103) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [retina](http://purl.obolibrary.org/obo/UBERON_0000966)) 

- [retinal bipolar neuron](http://purl.obolibrary.org/obo/CL_0000748) SubClassOf [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [retina](http://purl.obolibrary.org/obo/UBERON_0000966) 

#### Added
- [retinal bipolar neuron](http://purl.obolibrary.org/obo/CL_0000748) EquivalentTo [bipolar neuron](http://purl.obolibrary.org/obo/CL_0000103) and ([has soma location](http://purl.obolibrary.org/obo/RO_0002100) some [retina](http://purl.obolibrary.org/obo/UBERON_0000966)) 

- [retinal bipolar neuron](http://purl.obolibrary.org/obo/CL_0000748) SubClassOf [has soma location](http://purl.obolibrary.org/obo/RO_0002100) some [retina](http://purl.obolibrary.org/obo/UBERON_0000966) 


### sensory neuron of dorsal root ganglion `http://purl.obolibrary.org/obo/CL_1001451`
#### Removed
- [sensory neuron of dorsal root ganglion](http://purl.obolibrary.org/obo/CL_1001451) EquivalentTo [sensory neuron](http://purl.obolibrary.org/obo/CL_0000101) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [dorsal root ganglion](http://purl.obolibrary.org/obo/UBERON_0000044)) 

#### Added
- [sensory neuron of dorsal root ganglion](http://purl.obolibrary.org/obo/CL_1001451) EquivalentTo [sensory neuron](http://purl.obolibrary.org/obo/CL_0000101) and ([has soma location](http://purl.obolibrary.org/obo/RO_0002100) some [dorsal root ganglion](http://purl.obolibrary.org/obo/UBERON_0000044)) 

- [sensory neuron of dorsal root ganglion](http://purl.obolibrary.org/obo/CL_1001451) SubClassOf [has soma location](http://purl.obolibrary.org/obo/RO_0002100) some [dorsal root ganglion](http://purl.obolibrary.org/obo/UBERON_0000044) 


### sensory neuron of spinal nerve `http://purl.obolibrary.org/obo/CL_0009000`
#### Removed
- [sensory neuron of spinal nerve](http://purl.obolibrary.org/obo/CL_0009000) EquivalentTo [sensory neuron](http://purl.obolibrary.org/obo/CL_0000101) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [spinal nerve](http://purl.obolibrary.org/obo/UBERON_0001780)) 

- [sensory neuron of spinal nerve](http://purl.obolibrary.org/obo/CL_0009000) SubClassOf [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [spinal nerve](http://purl.obolibrary.org/obo/UBERON_0001780) 

- [sensory neuron of spinal nerve](http://purl.obolibrary.org/obo/CL_0009000) SubClassOf [sensory neuron](http://purl.obolibrary.org/obo/CL_0000101) 
  - [is_inferred](http://www.geneontology.org/formats/oboInOwl#is_inferred) "true" 

#### Added
- [sensory neuron of spinal nerve](http://purl.obolibrary.org/obo/CL_0009000) EquivalentTo [sensory neuron](http://purl.obolibrary.org/obo/CL_0000101) and ([has soma location](http://purl.obolibrary.org/obo/RO_0002100) some [spinal nerve](http://purl.obolibrary.org/obo/UBERON_0001780)) 

- [sensory neuron of spinal nerve](http://purl.obolibrary.org/obo/CL_0009000) SubClassOf [peripheral sensory neuron](http://purl.obolibrary.org/obo/CL_3000004) 

- [sensory neuron of spinal nerve](http://purl.obolibrary.org/obo/CL_0009000) SubClassOf [has soma location](http://purl.obolibrary.org/obo/RO_0002100) some [spinal nerve](http://purl.obolibrary.org/obo/UBERON_0001780) 


### vomeronasal sensory neuron `http://purl.obolibrary.org/obo/CL_1001561`
#### Removed
- [vomeronasal sensory neuron](http://purl.obolibrary.org/obo/CL_1001561) EquivalentTo [sensory neuron](http://purl.obolibrary.org/obo/CL_0000101) and ([part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [vomeronasal organ](http://purl.obolibrary.org/obo/UBERON_0002255)) and ([innervates](http://purl.obolibrary.org/obo/RO_0002134) some [epithelium of vomeronasal organ](http://purl.obolibrary.org/obo/UBERON_0003367)) 

- [vomeronasal sensory neuron](http://purl.obolibrary.org/obo/CL_1001561) SubClassOf [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [vomeronasal organ](http://purl.obolibrary.org/obo/UBERON_0002255) 

- [vomeronasal sensory neuron](http://purl.obolibrary.org/obo/CL_1001561) SubClassOf [neuronal receptor cell](http://purl.obolibrary.org/obo/CL_0000006) 

#### Added
- [vomeronasal sensory neuron](http://purl.obolibrary.org/obo/CL_1001561) EquivalentTo [sensory neuron](http://purl.obolibrary.org/obo/CL_0000101) and ([has soma location](http://purl.obolibrary.org/obo/RO_0002100) some [vomeronasal organ](http://purl.obolibrary.org/obo/UBERON_0002255)) and ([innervates](http://purl.obolibrary.org/obo/RO_0002134) some [epithelium of vomeronasal organ](http://purl.obolibrary.org/obo/UBERON_0003367)) 

- [vomeronasal sensory neuron](http://purl.obolibrary.org/obo/CL_1001561) SubClassOf [has soma location](http://purl.obolibrary.org/obo/RO_0002100) some [vomeronasal organ](http://purl.obolibrary.org/obo/UBERON_0002255) 

- [vomeronasal sensory neuron](http://purl.obolibrary.org/obo/CL_1001561) SubClassOf [sensory neuron](http://purl.obolibrary.org/obo/CL_0000101)

**Review by paolaroncaglia — APPROVED** [review]

**Pull request merged**
