### PR TITLE
add "cell" to synonyms to CL_0000525

### LINKED ISSUE #2100: syncytial trophoblast is exact synonym for CL:0000525 and UBERON:0000371
syncytiotrophoblast cell CL:0000525 has exact synonym syncytial trophoblast which is also an exact synonym of syncytiotrophoblast UBERON:0000371. CL term refers to cell type, while uberon refers to layer.
I am not sure if syncytial trophoblast commonly refers to the layer or cell type, but I am guessing one of them should not be exact synonym. 
On that note, I am guessing there should be some link somewhere (I have not run any thing (eg OAK) to see if there actually is a link, but at face value there does not seem to be an obvious one)

### PR DESCRIPTION
**Pull request by shawntanzk**
Fixes #2100 
extra changes from protege a bit annoying but harmless 
synonyms did not originally come with dbxref so leaving as is 
overall just trying to get synonyms to reflect how uberon and CL relates to each other

### CODE REVIEW

**Review by aleixpuigb — APPROVED** [review]
I have found this reference [PMID:11787150](https://pubmed.ncbi.nlm.nih.gov/11787150/) for syncytial trophoblast cell. I could also find another synonym "syncytiotrophoblastic cell" [PMID:21733368](https://pubmed.ncbi.nlm.nih.gov/21733368/). However I could not find any reference for the other two. However, as the synonyms of 'syncytiotrophoblas' are widely used, I think it is beneficial to have this synonyms.

**Comment by shawntanzk** [comment]
> I have found this reference [PMID:11787150](https://pubmed.ncbi.nlm.nih.gov/11787150/) for syncytial trophoblast cell. I could also find another synonym "syncytiotrophoblastic cell" [PMID:21733368](https://pubmed.ncbi.nlm.nih.gov/21733368/).

I will add these before merge

> However, as the synonyms of 'syncytiotrophoblas' are widely used, I think it is beneficial to have this synonyms.

avoiding this as uberon uses it (syncytiotrophoblast UBERON:0000371) adding cell behind follows the logical axioms. Happy to add that back as a related synonym perhaps?

**Comment by aleixpuigb** [comment]
Yes, can you change them to related synonyms? plasmidotrophoblast is not a synonym in uberon and syntrophoblast is a related synonym
image

Apologies, I shouldn't have accepted the PR so quickly.

**Comment by shawntanzk** [comment]
@aleixpuigb - agree, have made the changes :) Thanks!

**Review by aleixpuigb — CHANGES_REQUESTED** [review]
Consider changing "plasmidotrophoblast cell" to related as well. It lacks references, so I think it is better to have it as related.

**Comment by shawntanzk** [comment]
> Consider changing "plasmidotrophoblast cell" to related as well. It lacks references, so I think it is better to have it as related.

ah shoot sorry, accidentally missed, fixed now :) thanks for the spot

**Review by aleixpuigb — APPROVED** [review]

**Review by aleixpuigb — CHANGES_REQUESTED** [review]
"syncytiotrophoblast" is appearing again, is that intended?

**Comment by shawntanzk** [comment]
> "syncytiotrophoblast" is appearing again, is that intended?

yes :) ive placed it as a related because for your comment: 

>  However, as the synonyms of 'syncytiotrophoblas' are widely used, I think it is beneficial to have this synonyms.

I think the QC check (both on our side, and the ones to be implemented here) allow for duplicated related synonym but not exact

**Comment by aleixpuigb** [comment]
Oh sorry, that's not what I meant. I was referring to the synonyms of "syncytiotrophoblast" (syntrophoblast, plasmidotrophoblast), that it would be beneficial to have syntrophoblast cell and plasmidotrophoblast cell. Not to add "syncytiotrophoblast". Not sure if this makes it more clear. But I think it is better to remove "syncytiotrophoblast" and everything else will be ok.

**Comment by shawntanzk** [comment]
@aleixpuigb lol sorry, probably my bad, friday and all :p fixed. Thanks heaps

**Review by aleixpuigb — APPROVED** [review]
Now everything looks great!

**Pull request merged**
