### PR TITLE
For Issue #1373

### PR DESCRIPTION
**Pull request by bvarner-ebi**
Restrict CL:0000034 'stem cell' to Metazoa #1373

I will appreciate your review.

### CODE REVIEW

**Review by paolaroncaglia — APPROVED** [review]
Hi @bvarner-ebi ,
Looks good to me!
Please go ahead and merge (let us know if you don't have permission to). Thanks.

**Comment by bvarner-ebi** [comment]
Thank you for reviewing, @paolaroncaglia!
I currently do not have permission to merge:
"Merging is blocked
The base branch restricts merging to authorized users."

**Comment by paolaroncaglia** [comment]
@bvarner-ebi we're looking into this.

**Comment by bvarner-ebi** [comment]
@paolaroncaglia, maybe a repo owner needs to assign "admin" privileges to my username.

**Comment by paolaroncaglia** [comment]
Hi @bvarner-ebi ,

> @paolaroncaglia, maybe a repo owner needs to assign "admin" privileges to my username.

Yes, @dosumis was going to look into it. David, when you have a chance, could you please follow up with Bradley?
I'm happy to merge for him, but OTOH if I leave it unmerged he can test privileges if/when you change them. Thanks.

**Pull request merged**
