### PR TITLE
Add CL_0017003 (epithelial cell of prostatic urethra)

### PR DESCRIPTION
**Pull request by lubianat**
Related to issue #1134. 

I have not added a  `part of` axiom as I could not find the prostatic urethra (http://purl.obolibrary.org/obo/UBERON_0001335) on the CL import of UBERON.

### CODE REVIEW

**Review by dosumis — COMMENTED** [review]
Looks good.  Do you want to have a go at adding prostatic urethra to Uberon?  Once this is available you could change the logical definition to:

EquivalentTo: 'epithelial cell' and 'part of' some 'prostatic urethra' 

+ delete subClassOf and let reasoner classify dynamically.

**Review by dosumis — APPROVED** [review]

**Review by dosumis — CHANGES_REQUESTED** [review]
@lubianat  - apologies I misread your original comment.  As the term is in Uberon, can you have a go at updating imports?

To do this: add the ID to imports/uberon_imports.txt, then 

./run.sh make imports/uberon_import.owl

then please edit as suggested in comment.  

Happy to do a quick screenshare to help if you it problems.

**Comment by lubianat** [comment]
@dosumis Thank you for the guidance. 

I have tried the following: 

- Add the term (UBERON:0001335) to the end of the list in `cell-ontology/src/ontology/imports/uberon_terms.txt`
- On the src/ontology directory, run `./run.sh make imports/uberon_terms.txt`

The script downloaded some large  files ("`Pulling from obolibrary/odkfull`") and threw a message: 

```
cl.Makefile:106: warning: overriding recipe for target 'cl-simple.owl'
Makefile:587: warning: ignoring old recipe for target 'cl-simple.owl'
cl.Makefile:114: warning: overriding recipe for target 'cl-simple.obo'
Makefile:511: warning: ignoring old recipe for target 'cl-simple.obo'
cl.Makefile:125: warning: overriding recipe for target 'cl-basic.owl'
Makefile:600: warning: ignoring old recipe for target 'cl-basic.owl'
cl.Makefile:154: warning: overriding recipe for target 'cl-basic.obo'
Makefile:517: warning: ignoring old recipe for target 'cl-basic.obo'
make: Nothing to be done for 'imports/uberon_terms.tx
```

By the diff, it does not seem to have changed any file, though.

I guess I'll need the quick screenshare :). Perhaps sometime tomorrow? (Friday)

**Comment by dosumis** [comment]
CC @matentzn

**Comment by matentzn** [comment]
@lubianat you seem to have a typo:

You ran: 

```
./run.sh make imports/uberon_terms.tx
```

try:

```
./run.sh make imports/uberon_terms.txt
```

**Comment by lubianat** [comment]
@matentzn  Oh, it was a copy-paste-o, sorry for that. I actually ran `./run.sh make imports/uberon_terms.txt` and the error message ended with a `make: Nothing to be done for 'imports/uberon_terms.txt'.`

There were a 6 other terms and a couple empty lines before in the file, I tried removing those and leaving the txt only with UBERON:0001335, but got the same message.

**Comment by matentzn** [comment]
I should have asked what you are trying to do :D Assuming you want to import the new terms from the uberon module:

```
sh run.sh make refresh-uberon
```

**Comment by dosumis** [comment]
Here's what I suggested 

`./run.sh make imports/uberon_import.owl`

Does this still work?

**Comment by matentzn** [comment]
@dosumis yes!

**Comment by lubianat** [comment]
@matentzn thanks! Logging here what happens: 

- I ran the code and got an error: `There is insufficient memory for the Java Runtime Environment to continue.` (apparently the process takes ~2GB and I was already running too many things) 

- I freed some memory and ran again. 

As mentioned in the commit, it kind of seems to have worked, but seemly harmless modifications happened throughout the file.

**Comment by dosumis** [comment]
Update will pull in more terms to uberon_import than you spec'd.  As long as the term you specified is present you're fine.  If you can update the axiomatisation as suggested I'll approve.  Thanks!

**Comment by matentzn** [comment]
- [ ] @dosumis to confirm comments are addressed
- [ ] @lubianat to merge

**Comment by lubianat** [comment]
@matentzn I have just seem that the class ID will conflict with:
 - https://github.com/obophenotype/cell-ontology/pull/1170 
 
 I'll try and change the ID on Protege.

**Comment by anitacaron** [comment]
I've fixed the conflicts. I will run a new release soon, and this PR looks like everything is finished so that it can be included in the next release. @lubianat, do you think someone else can review this PR?

**Review by dosumis — APPROVED** [review]

**Comment by dosumis** [comment]
> I have just seem that the class ID will conflict with:

> https://github.com/obophenotype/cell-ontology/pull/1170
> I'll try and change the ID on Protege.

Fixed in PR, but this shouldn't happen. Can someone (@shawntanzk ?) look at how the clash happened and check @lubianat ID config to ensure it doesn't happen again.

Thanks.

**Comment by shawntanzk** [comment]
I rmbr that happening to me before, no idea why it happens sometimes, but its pretty rare it only happened a couple of times when I was doing a lot of additions. Just to make sure, here is my new entities settings that would be related to this: 
Screenshot 2022-08-12 at 07 58 18

**Pull request merged**
