### PR TITLE
CL release 2023-10-19

### PR DESCRIPTION
**Pull request by bvarner-ebi**
CL release 2023-10-19

Cursory review revealed expected updates.

### CODE REVIEW

**Comment by bvarner-ebi** [comment]
FYI @gouttegd as I noticed some edits involving "namespace: fly_anatomy.ontology".

**Comment by gouttegd** [comment]
The disappearance of the `oboInOwl#hasOBONamespace` annotations with a value of `fly_anatomy.ontology` is a consequence of FBbt having recently stopped to use OBO shorthands for some RO relations. I am not sure why such annotations were even present in CL in the first place (CL does not import FBbt), but in any case their removal is a healthy thing.

I am more concerned by things like this:

```diff
-property_value: depicted_by "http://upload.wikimedia.org/wikipedia/commons/d/d0/Canine-nose.jpg" xsd:anyURI
+property_value: depicted:by "http://upload.wikimedia.org/wikipedia/commons/d/d0/Canine-nose.jpg" xsd:anyURI
```

in some of the OBO artefacts. That `depicted:by` seems *very* wrong.

**Comment by bvarner-ebi** [comment]
> The disappearance of the `oboInOwl#hasOBONamespace` annotations with a value of `fly_anatomy.ontology` is a consequence of FBbt having recently stopped to use OBO shorthands for some RO relations. I am not sure why such annotations were even present in CL in the first place (CL does not import FBbt), but in any case their removal is a healthy thing.

@gouttegd, thank you for confirming.

> I am more concerned by things like this:
> 
> ```diff
> -property_value: depicted_by "http://upload.wikimedia.org/wikipedia/commons/d/d0/Canine-nose.jpg" xsd:anyURI
> +property_value: depicted:by "http://upload.wikimedia.org/wikipedia/commons/d/d0/Canine-nose.jpg" xsd:anyURI
> ```
> 
> in some of the OBO artefacts. That `depicted:by` seems _very_ wrong.

@anitacaron, assuming this is related to https://github.com/obophenotype/uberon/pull/3091. Is this expected?

**Comment by anitacaron** [comment]
> unsure if this is related to https://github.com/obophenotype/uberon/pull/3091. Is this expected?

They're unrelated, but it seems we don't have any control over the OBO format. Maybe it can be related to the change in CL that I removed the annotation declaration. It'll be fixed on the next Uberon release.

**Review by aleixpuigb — APPROVED** [review]

**Review by anitacaron — APPROVED** [review]

**Comment by bvarner-ebi** [comment]
> All the expected changes from PRs are reflected in the diff file.
> 
> Once the issues raised in the previous comments are solved, I will approve the PR.

Thanks for reviewing.
It seems like the OBO formatting issue is benign (@anitacaron has approved) and will be resolved after a new Uberon release is available.

**Pull request merged**
