### PR TITLE
Axiomatize PATO histological quality

### LINKED ISSUE #572: Obsolete use of CP_ iris and replace by CL_ instead to avoid future clashes?
There are a bunch of classes in CL that dont have the normal CL namespace, like this:

https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCP_0000028

Maybe it make sense in the long term to obsolete those and instead use CL_000 iris. Just to avoid bad things happening when the Core Process Ontology (CP) will be registered at OBO :P

### LINKED ISSUE #1403: Axiomization of histological quality after they have been added to PATO
See this PR: 
https://github.com/pato-ontology/pato/pull/452

Will need next release to do this.

### PR DESCRIPTION
**Pull request by shawntanzk**
Fixes #1403
Fixes #572 
Currently I see that the CP terms has been added as CL IDs with cytoplasm and PATO quality, I've done so for the rest. 
Note this ticket will automatically close 572 -> i think it is all we need to do for that ticket, but in case it isn't, please change accordingly.
Thanks!

### CODE REVIEW

**Review by dosumis — APPROVED** [review]

**Comment by matentzn** [comment]
Can you add a robot diff -f markdown here as a comment to the PR, else we cant really see what exactly this PR does. :)

**Comment by shawntanzk** [comment]
> Can you add a robot diff -f markdown here as a comment to the PR, else we cant really see what exactly this PR does. :)

for cl-edit? cause the diff is really small for this one. unless you mean merged_import

**Comment by shawntanzk** [comment]
# Ontology comparison
## Left
- Ontology IRI: `http://purl.obolibrary.org/obo/cl.owl`
- Version IRI: *None*
- Loaded from: `file:/work/src/ontology/tmp.owl`
## Right
- Ontology IRI: `http://purl.obolibrary.org/obo/cl.owl`
- Version IRI: *None*
- Loaded from: `file:/work/src/ontology/cl-edit.owl`
### Ontology imports 
### Ontology annotations 
### acidophilic cytoplasm `http://purl.obolibrary.org/obo/CL_0017502`
#### Removed
- [acidophilic cytoplasm](http://purl.obolibrary.org/obo/CL_0017502) SubClassOf [cytoplasm](http://purl.obolibrary.org/obo/GO_0005737) 
#### Added
- [acidophilic cytoplasm](http://purl.obolibrary.org/obo/CL_0017502) EquivalentTo [cytoplasm](http://purl.obolibrary.org/obo/GO_0005737) and ([bearer of](http://purl.obolibrary.org/obo/RO_0000053) some [acidophilic](http://purl.obolibrary.org/obo/PATO_0002418)) 
### neutrophillic cytoplasm `http://purl.obolibrary.org/obo/CL_0017500`
#### Removed
- [neutrophillic cytoplasm](http://purl.obolibrary.org/obo/CL_0017500) SubClassOf [cytoplasm](http://purl.obolibrary.org/obo/GO_0005737) 
#### Added
- [neutrophillic cytoplasm](http://purl.obolibrary.org/obo/CL_0017500) EquivalentTo [cytoplasm](http://purl.obolibrary.org/obo/GO_0005737) and ([bearer of](http://purl.obolibrary.org/obo/RO_0000053) some [neutrophillic](http://purl.obolibrary.org/obo/PATO_0070046))

**Review by matentzn — APPROVED** [review]

**Comment by matentzn** [comment]
As a side note: Its strange that the diff tool still shows the old, bad, `bearer of` label instead of `has characteristic`.

**Comment by shawntanzk** [comment]
@matentzn think one of the ontologies has an obsolete RO import - the rdfs:label bearer of is coming from merged import

**Comment by dosumis** [comment]
Markdown diff is great.  Can we encourage everyone to generate and post these?  (although, IIRC @gouttegd  was looking at a GitHub action to this automagically, so maybe wait for that?)

**Comment by shawntanzk** [comment]
I can try to take a look at doing it - been wanting to learn github automation stuff anyway :)

**Comment by matentzn** [comment]
@ubyndr is working on the diff gh action situation

**Pull request merged**
