### PR TITLE
Fixes #1460 update glomerular visceral epithelial cell label to podocyte

### LINKED ISSUE #1460: [Synonym] exchange the ontology term label for an existing synonym
**CL term**
CL:0000653: https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000653
There is an associated Term Not Found link: http://purl.obolibrary.org/obo/CL_0000653

**Issue**
Requesting that the ontology term label be "podocyte", as this is the term currently used by the community to name these cell types. "glomerular visceral epithelial cell" would then be a synonym. Here are a few papers:
-https://doi.org/10.1101/2021.07.28.454201
-https://doi.org/10.1038/s41467-021-22368-w
-https://doi.org/10.1101/2021.10.10.463829
-https://dx.doi.org/10.1126%2Fscience.aat5031

### PR DESCRIPTION
**Pull request by bvarner-ebi**
update label of glomerular visceral epithelial cell to podocyte and some other synonym additions

Per @paolaroncaglia:
> [x] add exact synonyms to CL:0000653 "kidney podocyte", "renal podocyte" to help disambiguate?
> [x] I'd also remove the old comment from CL:0000653, and add a seeAlso annotation pointing to this ticket. Thanks.
> [x] P.S. of course also consider adding submitter's provided references.

After a very cursory review of the provided references in #1460, I added https://doi.org/10.1101/2021.10.10.463829 as a dbref since it seem more focused on podocyte analysis than the first two. Unfortunately I was unable to access the full paper at the fourth link. I'd be happy to add it if the relevant passages that support this update from the paper are shared, @jychien. I am also happy to add your ORCID if you provide it.

### CODE REVIEW

**Comment by jychien** [comment]
FYI, for the fourth paper, they have a data portal where you can access and see the cell types: https://www.kidneycellatlas.org/

**Review by paolaroncaglia — APPROVED** [review]
@bvarner-ebi all good, thanks.
I have a minor doubt about the best way to enter DOIs, which I've just asked about in the Uberon-editors Slack channel. But it's not a blocker, so feel free to go ahead and merge.

**Comment by bvarner-ebi** [comment]
Thank you for the link, @jychien. I am familiar with that data portal. Thank you for the review, @paolaroncaglia. My inclination is that adding the fourth link is not required as it won't impact the current definition of the term and it's not necessary to justify renaming the label. If there is a particular passage from the link you'd like to incorporate in the annotations, I think that would then justify adding it. If you have more thoughts on this, pls share.

Regarding DOI formatting, it sounds like there is not consensus yet, but will follow the standard once a decision is made. Hopefully we could run a query that would update all of these once finalised.

**Comment by jychien** [comment]
@bvarner-ebi Thank you for the explanation. No, I don't think there is any additional information that the fourth link provided in regards to the usage of 'podocyte'.

**Pull request merged**
