### PR TITLE
Added L5/6 Non-martinotti SST

### LINKED ISSUE #948: [NTR] L5/6 non-Martinotti cell
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
L5/6 Non-martinotti morphology Sst expressing GABAergic cortical interneuron (Mus musculus)

**Synonyms**
L5/6 Non-martinotti SST (Mus)

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
A Sst GABAergic cortical interneuron of Sst subclass found in L5/L6 with non-Martionotti morphology. They have strongly facilitating excitatory inputs and moderately depressing outputs. They have powerful muscarinic depolarization, faster action potential than Martinotti and slightly slower action potential than PV basket cells. 
(PMID:27477017)

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
GABAergic interneuron

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
Cerebral Cortex

**Your nano-attribution (ORCID)**

**Any additional notes or concerns**

### PR DESCRIPTION
**Pull request by shawntanzk**
Fixes #948

### CODE REVIEW

**Review by patrick-lloyd-ray — COMMENTED** [review]
Looks good to me.

**Comment by dosumis** [comment]
Does everything with that does not have Martinotti morphology have non-Martinotti morphology? i.e. does this apply to most cells?
We sometimes can't avoid negative differentia, but I'd like to know more.  Does this mean that this is a morphologically heterogenous class when the other differentia are taken in to account (GABA-ergic + Marker) ?

**Comment by shawntanzk** [comment]
@dosumis I'll take note of your comment and merge for now, but good point, it definitely is something we should figure out, will look into it/keep it as a question to ask experts. Thanks

**Comment by shawntanzk** [comment]
have asked Jeremy about this - will get back to this once I get an answer

**Comment by shawntanzk** [comment]
Messy diffs that is problematic caused by clashing IRI that fixed wrongly, easier to close this PR and reopen a new one

**Pull request closed without merging**
