### PR TITLE
add terms: alveolar fibroblasts (2)

### PR DESCRIPTION
**Pull request by JoshuaFortriede**
New Terms:
alveolar type 1 fibroblast cell
alveolar type 2 fibroblast cell

Completes the following tickets:
Issue #1030
Issue #1053
Issue #1280

### CODE REVIEW

**Comment by paolaroncaglia** [comment]
Hi @JoshuaFortriede , before I forget,

> Completes the following tickets: Issue-1030 Issue-1053 Issue-1280

FYI, if you prefix the ticket number with a # sign (no space), e.g. #1030 , the pull request will be linked to the ticket, which makes it much easier to document/retrieve discussions, commits etc. 
Thanks.

**Review by paolaroncaglia — CHANGES_REQUESTED** [review]
Hi @JoshuaFortriede ,
Not sure what this is in line 29309 and 29325, but it looks incorrect? <http://www.ebi.ac.uk/cellline/definition> I suppose you meant to use the definition annotation property instead.
Also, the first definition "A lipid droplet containing fibroblast of lung..." would be less ambiguous as "A lipid droplet-containing fibroblast of lung..." please, or even "A lung fibroblast containing lipid droplets...", otherwise the focus seems to be on the lipid droplet itself.
Lastly, please ensure that all suggestions contained in #1030 , #1053 and #1280 (synonyms, PMIDs, ORCID...), if appropriate/correct, are added to the terms.
Everything else looks fine :-)
Thanks!
Paola

**Comment by JoshuaFortriede** [comment]
@paolaroncaglia, I believe I have fixed the issues. I also changed the terms to be subclass of "pulmonary interstitial fibroblast" and not "fibroblast of lung" as it is more specific and correctly specifies them as being interstitial.

**Review by paolaroncaglia — COMMENTED** [review]
Hi @JoshuaFortriede ,
Thanks, I agree with the more granular parent you choose.
As far as I can tell, ORCIDs from the 3 tickets you're addressing are still not included in these terms, I think at least the type 1 term should? Please double-check that synonyms and PMIDs that submitters suggested are all there - looking at the tickets quickly, I'm wondering if we should also have a term for 'alveolar fibroblast' to address #1030 - there's no reference to interstitial localization there.
Thanks!

**Comment by JoshuaFortriede** [comment]
Contributors have been added. For the #1030, while the term request doesn't specify that these are interstitial cells, looking at the marker genes in single cell datasets, they appear to be the same cells as #1053 and #1280.

**Review by paolaroncaglia — APPROVED** [review]

**Comment by paolaroncaglia** [comment]
Thanks @JoshuaFortriede . Please feel free to merge this pull request, delete the branch, and update + close the tickets.

**Pull request merged**
