### PR TITLE
Change has_completed to obo:RO_0002353

### PR DESCRIPTION
**Pull request by shawntanzk**
#gogoeditdiff
see https://github.com/oborel/obo-relations/issues/574#issuecomment-1349249113
Also tagging @bpeters42
Please do see the automated diff (once it comes up) to ensure that changes are accurate.
Thanks

### CODE REVIEW

**Review by balhoff — APPROVED** [review]

**Comment by shawntanzk** [comment]
@addiehl Could you also give a positive review before I merge this, would be more comfortable if you go through this too. Thanks :)

**Comment by shawntanzk** [comment]
#gogoeditdiff

**Comment by shawntanzk** [comment]
Not 100% sure why the QC isn't autorunning, but manually triggered it and it passed https://github.com/obophenotype/cell-ontology/actions/runs/3847578786

**Comment by shawntanzk** [comment]
Merging this given the time has passed, please open a new ticket if there is any issues

**Pull request merged**
