### PR TITLE
Update cl-edit.owl

### PR DESCRIPTION
**Pull request by JArgasinska**
Fixed typo noted in #1391

### CODE REVIEW

**Comment by bvarner-ebi** [comment]
Hi @JArgasinska,

I see you successfully fixed the typo in the definition.

I'm not sure why line 2650 "Declaration(Class(obo:PR_000005444))" was added or why ^^xsd:string was added (line 29442).

@shawntanzk, @dosumis, could you comment on either of these latter two changes?

**Comment by shawntanzk** [comment]
added ^^xsd:string is correct - its probably from another PR that didnt refresh it with ^^xsd:string and when you normalised it, it added that in there

**Comment by bvarner-ebi** [comment]
Thanks, @shawntanzk. 
I see "Declaration(Class(obo:PR_000005444))" also appears as an added line in PR #1397. I'm not sure why it is there, but it does not seem like it would cause a conflict. Can someone confirm?

**Comment by shawntanzk** [comment]
@bvarner-ebi yeah that's mine, sorry about that. It should be added - when I imported that previously, I didn't quite understand how the merged file import that CL is on now worked and so it was left dangling in the last release - protege is just trying to fix it by declaring it, shouldn't be a problem.

**Review by bvarner-ebi — APPROVED** [review]
@bvarner-ebi review:
Typo is fixed.
Other observed changes are explained in the comments above.

**Comment by JArgasinska** [comment]
@dosumis could you grant the permission for me to merge the pull request? Thanks

**Comment by shawntanzk** [comment]
> @dosumis could you grant the permission for me to merge the pull request? Thanks

I've just done it - you should be able to now :)

**Comment by JArgasinska** [comment]
> > @dosumis could you grant the permission for me to merge the pull request? Thanks
> 
> I've just done it - you should be able to now :)

Thanks! It feels like I got to the top of Mt Everest by fixing that typo :)

**Pull request merged**
