### PR TITLE
Addresses #1583-NTR-connecting_tubule_principal_cell

### PR DESCRIPTION
**Pull request by bvarner-ebi**
Addresses #1583 kidney connecting tubule principal cell

### CODE REVIEW

**Comment by shawntanzk** [comment]
Same as hillock cell - I think your subclass to  [kidney connecting tubule epithelial cell (http://purl.obolibrary.org/obo/CL_1000768) is needed for the classification (something on nephron not being properly connected to kidney is the issue here I think). But the subclass axiom `[CL_4030018](http://purl.obolibrary.org/obo/CL_4030018) SubClassOf [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [renal connecting tubule](http://purl.obolibrary.org/obo/UBERON_0005097)` that is repeated in equivalent class axiom is defs not needed

**Comment by bvarner-ebi** [comment]
> Same as hillock cell - I think your subclass to [kidney connecting tubule epithelial cell (http://purl.obolibrary.org/obo/CL_1000768) is needed for the classification (something on nephron not being properly connected to kidney is the issue here I think). But the subclass axiom '[CL_4030018](http://purl.obolibrary.org/obo/CL_4030018) SubClassOf [part_of](http://purl.obolibrary.org/obo/BFO_0000050) some [renal connecting tubule](http://purl.obolibrary.org/obo/UBERON_0005097)' that is repeated in equivalent class axiom is defs not needed

I removed the redundant axiom. Thanks for catching these!

**Comment by bvarner-ebi** [comment]
@shawntanzk, @emquardokus, hopefully this one is more straightforward to review / approve.

**Review by shawntanzk — APPROVED** [review]
Still honestly not quite happy with the [CL_4030018](http://purl.obolibrary.org/obo/CL_4030018) SubClassOf [kidney connecting tubule epithelial cell](http://purl.obolibrary.org/obo/CL_1000768) axiom but I get that that will take some effort to figure out. But I guess nothing is wrong with this per se. I will approve this, but you might want to write up a ticket on figuring out why it doesn't infer and look into this when you have the time.

**Comment by bvarner-ebi** [comment]
> Still honestly not quite happy with the [CL_4030018](http://purl.obolibrary.org/obo/CL_4030018) SubClassOf [kidney connecting tubule epithelial cell](http://purl.obolibrary.org/obo/CL_1000768) axiom but I get that that will take some effort to figure out. But I guess nothing is wrong with this per se. I will approve this, but you might want to write up a ticket on figuring out why it doesn't infer and look into this when you have the time.

@shawntanzk, I can remove that axiom. Here is what is inferred:
Screenshot 2022-07-01 at 09 54 22

Is this a better modelling approach?

**Pull request merged**
