### PR TITLE
Retinal bipolar cells

### PR DESCRIPTION
**Pull request by dosumis**

### CODE REVIEW

**Comment by addiehl** [comment]
But platelets do secrete serotonin...

**Comment by dosumis** [comment]
> But platelets do secrete serotonin...

This is inferred and will be asserted in release:

image

**Comment by dosumis** [comment]
BTW - thanks for checking.  Diff is a bit bigger than I would like due to a few annotation axioms having type 'string'  in master but not in my branch.   This explains most apparent immune system / blood cell edits. I went through all these quickly to check for any other changes and all looks OK.

**Comment by dosumis** [comment]
Looks like some header axioms dropped too.  I'll add back.

**Comment by addiehl** [comment]
Thanks for clearing that up

**Pull request merged**
