### PR TITLE
CL 28 October release

### PR DESCRIPTION
**Pull request by bvarner-ebi**

### CODE REVIEW

**Comment by anitacaron** [comment]
Is this right that there isn't any difference in the cl-simple.owl file?

**Comment by bvarner-ebi** [comment]
> Is this right that there isn't any difference in the cl-simple.owl file?

It looks like there are changes....

Screenshot 2022-10-28 at 14 56 56

I don't think the github-actions messages work for release PRs. The same message appeared last month: https://github.com/obophenotype/cell-ontology/pull/1703#issuecomment-1248126922.

**Comment by shawntanzk** [comment]
> Is this right that there isn't any difference in the cl-simple.owl file?

yes, the simple file builds it from edit file and compares it to the existing simple - given there shouldn't be any change in the edit file, there shouldn't be any change in diffs during release :)

**Review by shawntanzk — APPROVED** [review]
I assume the changes in `human_reference_atlas` are intentional - just double checking
Other than that looks good, thanks for making the release @bvarner-ebi

**Comment by anitacaron** [comment]
Yes, the subset `human_reference_atlas` is in constant change 😄

**Pull request merged**
