### PR TITLE
imported UBERON:0007221

### PR DESCRIPTION
**Pull request by shawntanzk**
refreshed uberon mirror and imported UBERON:0007221
Happy for whoever reviews this to merge in
Fixes https://github.com/obophenotype/cell-ontology/issues/1466
Related to https://github.com/obophenotype/cell-ontology/pull/1401#issuecomment-1046883764

### CODE REVIEW

**Review by paolaroncaglia — COMMENTED** [review]
@shawntanzk thank you, the import of the Uberon term I needed looks good. There's a ton of diffs to Uberon imported terms - I skimmed the list and the ones I looked at are ok; I presume that all Uberon diffs were looked at as part of the Uberon release, so no need to check all of them here, right?
@bvarner-ebi I see that you're tagged in this review too because one of your tickets was impacted, but not sure what we should check for, could you take a look please?
I'm happy to merge when both questions are addressed :-) Thanks!

**Comment by shawntanzk** [comment]
The changes are due to 1) uberon mirror being refreshed (so all the changes are in there), and 2) I'm guessing the term I pulled it also pulled in other terms that it is dependent on.

> not sure what we should check for

mainly that the addition/change you want is in this ticket. I did a quick check in the reasoned diff and saw that there were changes to the term @bvarner-ebi wanted - just probably good to check that its the correct change lol. I also checked that uberon:0007221 is in there :)

**Comment by paolaroncaglia** [comment]
@shawntanzk thanks, yes I checked and what I need is in there :-) I'll wait for Bradley to check too, no rush.

**Review by bvarner-ebi — APPROVED** [review]
I see the changes requested from https://github.com/obophenotype/uberon/issues/2230. Thank you, @shawntanzk!

**Pull request merged**
