### PR TITLE
Switching has_(not)_completed to RO terms

### PR DESCRIPTION
**Pull request by shawntanzk**
Switch has_completed to output_of
Switch has_not_completed to capable_of
See https://github.com/oborel/obo-relations/issues/574
Related to https://github.com/obophenotype/cell-ontology/issues/1481
tagging @bpeters42
will not merge unless we have approval from @addiehl

### CODE REVIEW

**Comment by dosumis** [comment]
Very useful to see all changed examples together.  Looks like there's plenty to discuss here, so have converted to Draft pending discussion on CL call.

**Comment by addiehl** [comment]
Please do not switch has_not_completed to capable_of.  They do not mean the same thing.  See  https://github.com/oborel/obo-relations/issues/574 for my suggestion.

**Comment by bvarner-ebi** [comment]
@shawntanzk, can we update or close this PR? There has been no noted activity for > 6 months.

**Comment by shawntanzk** [comment]
I'm going to close this for now, we need to resolve the discussion in https://github.com/oborel/obo-relations/issues/574 for this to move on

**Pull request closed without merging**
