### PR TITLE
FIxes #2676 myotendinous junction nucleus

### LINKED ISSUE #2676: [NTR-cxg] myotendinous junction
Please check that the term does not already exist by using the ontology search tool OLS:
https://www.ebi.ac.uk/ols4/ontologies/cl

**Preferred term label**
myotendinous junction

**Synonym(s)** (add reference(s), please)
myotendinous junction nuclei [https://doi.org/10.1038/s41467-020-20063-w](https://doi.org/10.1038/s41467-020-20063-w)
MTJ [https://doi.org/10.1038/s41467-020-18789-8](https://doi.org/10.1038/s41467-020-18789-8)
MTJ nuclei [https://doi.org/10.1038/s41467-020-20064-9](https://doi.org/10.1038/s41467-020-20064-9)

**Definition**
Myotendinous junction nuclei are specialized muscle nuclei located at the interface where muscle fibers connect to tendons. These myonuclei help regulate the structural integrity and function of the muscle-tendon connection, playing a key role in transmitting the force generated by muscle contraction to the tendon.

**Parent cell type term**
CL:0008046: extrafusal muscle fiber

**Anatomical structure where the cell type is found** 
UBERON:0001134: skeletal muscle tissue

**Your ORCID**
0009-0001-6947-615X

**Additional notes or concerns** 

[https://doi.org/10.1038/s41467-020-20063-w](https://doi.org/10.1038/s41467-020-20063-w): "Myotendinous junction (MTJ) nuclei ... were notable for expression of Col22a1 ..."

### PR DESCRIPTION
**Pull request by Caroline-99**
FIxes #2676
-Added a new term with textual and logical defs, references, and synonyms

### CODE REVIEW

**Comment by Caroline-99** [comment]
#gogoeditdiff

**Review by dosumis — APPROVED** [review]
Looks good.  Can I check that marker genes work across species?

**Comment by Caroline-99** [comment]
> Looks good. Can I check that marker genes work across species?

COL22A1 seems to be a well-established marker for the MTJ across various species - in zebrafish (PMID: 24131632), mice (PMID: [33311464](https://pubmed.ncbi.nlm.nih.gov/33311464/)) and humans (PMID: 36924352). However, there is limited information about ANKRD1 expression in MTJ nuclei across multiple species, it has been shown to be expressed in mice (PMID: [33311464](https://pubmed.ncbi.nlm.nih.gov/33311464/)). I am happy to only keep COL22A1 in the core definition ?

**Comment by dosumis** [comment]
> COL22A1 seems to be a well-established marker for the MTJ across various species - in zebrafish (PMID: 24131632), mice (PMID: [33311464](https://pubmed.ncbi.nlm.nih.gov/33311464/)) and humans (PMID: 36924352). However, there is limited information about ANKRD1 expression in MTJ nuclei across multiple species, it has been shown to be expressed in mice (PMID: [33311464](https://pubmed.ncbi.nlm.nih.gov/33311464/)). I am happy to only keep COL22A1 in the core definition ?

Sounds good.

**Comment by Caroline-99** [comment]
@dosumis @aleixpuigb Updated the definition to only include COL22A1

**Review by aleixpuigb — APPROVED** [review]

**Pull request merged**
