### PR TITLE
Addresses #1695 NTR-cxg BEST4 intestinal epithelial cell

### PR DESCRIPTION
**Pull request by bvarner-ebi**
Addresses #1695 NTR-cxg BEST4 intestinal epithelial cell

### CODE REVIEW

**Comment by shawntanzk** [comment]
I would prefer it if the BEST4+ part was axiomatized given its a defining part of the cell type

**Comment by shawntanzk** [comment]
Given the def says human, should you add a human taxon restriction? 
Also can we make this into an equiv class axiom? - not sure if the parent would make it too broad or if it is accurate to do so?

**Comment by bvarner-ebi** [comment]
Hi, @shawntanzk, following the [comments](https://github.com/obophenotype/cell-ontology/issues/1695#issuecomment-1256313376) from the linked issue, can you advise if it makes sense to make this class species agnostic or specific to humans, as originally requested and as the current commit reflects? My concern is that a "middle-ground" solution would create ambiguity, but I'm open to remodelling. If we operate with the open-world assumption, I am thinking the current commit may make more sense for the requester.

**Comment by shawntanzk** [comment]
after skimming the papers - I think its fair to leave this as human specific. 
I would add a (Hsap) at the back - we have done this with BDS stuff where we aren't sure that it exists outside mouse and evidence only suggest existence in mouse
see http://purl.obolibrary.org/obo/CL_4023023 for example

**Comment by bvarner-ebi** [comment]
> after skimming the papers - I think its fair to leave this as human specific.
> I would add a (Hsap) at the back - we have done this with BDS stuff where we aren't sure that it exists outside mouse and evidence only suggest existence in mouse
> see http://purl.obolibrary.org/obo/CL_4023023 for example

Thank you, @shawntanzk. I see examples in CL where " ,human" is appended to the label, e.g., [CD16-positive, CD56-dim natural killer cell, human](http://purl.obolibrary.org/obo/CL_0000939). Does using that convention seem reasonable in this case, for consistency? 
If using (Hsap) is preferable, should all labels in CL be aligned?
Of note, proteins seem to be styled with " (human)" appended to the label.

**Comment by shawntanzk** [comment]
Hmm good point. I'd say stick with human for now (thinking of people searching and all) but would be good to bring this up in a CL call - probably should standardise

**Review by shawntanzk — APPROVED** [review]
@bvarner-ebi - could you help bring up the inconsistency in taxon tags in the next CL call please? thanks :)

**Pull request merged**
