### PR TITLE
Added displaced amacrine cell

### LINKED ISSUE #380: displaced (inverted) amacrine cell
Unlike most amacrine cells, whose cell bodies reside in the INL, the cell bodies of displaced amacrine cells lie in the RGC layer.

From Randlett et al. 2010 (PubMed ID 21557506):
"Displaced amacrine cells (dACs) are a subpopulation of Sox2 expressing ACs that migrate further than other ACs, and come to lie basal to the IPL in the ganglion cell layer (Galvez et al., 1977; Taranova et al., 2006). dACs still have their neurites extending apically into the IPL, and therefore exhibit an inverted polarity with respect to the other AC subtypes."
Zebrafish dACs in ZDB-PUB-090914-32 (PubMed ID 19732413).

Original comment by: leylab

### PR DESCRIPTION
**Pull request by shawntanzk**
Fixes #380
Currently blocked as PR import is stopped due to insufficient memory
Still need to add expresses some Sox2 (PR:000015426)

### CODE REVIEW

**Comment by shawntanzk** [comment]
@matentzn adding you as a reviewer for the change in cl.makefile

**Comment by shawntanzk** [comment]
Lay description of change in cl.makefile:
Change processes to lower memory consumption - this unifies it more with vanilla makefile where PR import is labelled as a large import

**Comment by shawntanzk** [comment]
btws, review of PR_import is difficult cause of a whole lot of `rdf:datatype="http://www.w3.org/2001/XMLSchema#string"` diffs, but it should be correct (it runs perfectly fine in protege when adding the PR term to cl-edit at least)

**Comment by matentzn** [comment]
But the new approach works?

**Review by matentzn — APPROVED** [review]

**Comment by matentzn** [comment]
I did not review contents of cl-edit.owl

**Comment by shawntanzk** [comment]
> But the new approach works?

yes works nicely, thanks :) 

> I did not review contents of cl-edit.owl

No worries, will wait for @paolaroncaglia to re-review the cl-edit before I merge, thanks :)

**Comment by shawntanzk** [comment]
Note to self: after this is merged, push master into #1289 and try re running a refresh of imports, if it works, can push through update odk

**Review by paolaroncaglia — APPROVED** [review]
@shawntanzk cl-edit looks good to me, thanks.

**Pull request merged**
