### PR TITLE
Addresses #114 NTR catecholaminergic neuron

### PR DESCRIPTION
**Pull request by aleixpuigb**
Addresses #114 NTR catecholaminergic neuron

### CODE REVIEW

**Comment by aleixpuigb** [comment]
#gogoeditdiff

**Comment by aleixpuigb** [comment]
It is strange that only `noradrenergic neuron` is inferred as a subclass of this term.

image

In GO this classes are inferred as SubclassesOf `catecholamine secretion, neurotreansmission`:

image

However, this is not reflected in CL:

image

**Comment by balhoff** [comment]
@matentzn probably a justification for "base-plus".

**Review by dosumis — APPROVED** [review]

**Comment by aleixpuigb** [comment]
> @aleixpuigb I have a guess about this. GO gets this subsumption using some behind-the-scenes GCIs for CHEBI that aren't included in our base file. If CL is building on the GO base file, some necessary axioms might be missing.

Thank you, @balhoff! That makes it clear.

**Comment by dosumis** [comment]
@balhoff - my first thought was that if base is build from go-plus it should have all the necessary axioms - and if not, this is a misfeature of the GO build.  But, thinking about it, there is a ticket somewhere about derivation of base and the problems of retaining GCIs.  I'd like to look again at how we might solve that problem as I increasingly have use cases for GCIs.  CC @matentzn

**Comment by balhoff** [comment]
@dosumis you are right, I would call it a misfeature of go-base. I'm not sure that we should spread these CHEBI GCIs out into other ontologies (I'm referring to the "biochebi" stuff). But we need to include the reasoning results into go-base if don't don't include those GCIs.

**Pull request merged**
