### PR TITLE
Closes #1420 add synonyms to "mammary alveolar cell"

### LINKED ISSUE #1420: [Synonym] add synonyms to "mammary alveolar cell"
**CL term**: mammary alveolar cell (CL:0002325)

**Synonym to be added**:
"mammary alveolar epithelial cell"
"mammary gland alveolar epithelial cell"

**broad/exact/narrow/related ?** exact

### PR DESCRIPTION
**Pull request by bvarner-ebi**

### CODE REVIEW

**Comment by shawntanzk** [comment]
@bvarner-ebi would you mind putting the closes #1420 on the description in the future so I can easily click on it please? :) thanks! (I know, I'm very lazy :p )

**Comment by bvarner-ebi** [comment]
Absolutely, @shawntanzk. On my screen it shows the commit name with a clickable link below the description field, but I will also put it in the description field for future PRs.

Screenshot 2022-01-28 at 12 26 19

I ran `make normalise_xsd_string` before committing. Are you saying I should run it again before merging?

**Comment by shawntanzk** [comment]
@bvarner-ebi ah totally missed that, thanks :) 



> I ran `make normalise_xsd_string` before committing. Are you saying I should run it again before merging?

huh strange, just noticed that the synonyms you added do not have xsd:string behind them, give a go running `make normalise_xsd_string` again, if not doesn't matter too much, thanks

**Comment by bvarner-ebi** [comment]
Now I see. Thanks for catching, @shawntanzk.
To fix, I manually added the 'xsd:string' type to the new synonyms.

**Pull request merged**
