### PR TITLE
Remove `oboInOwl:hasOBONamespace`

### LINKED ISSUE #531: namespace assignment not consistent
cell concepts missing namespace definition, eg CL:0011114
namespace: cell

### PR DESCRIPTION
**Pull request by anitacaron**
Fixes #531

### CODE REVIEW

**Review by matentzn — APPROVED** [review]
Excellent, thank you!

**Comment by matentzn** [comment]
Always remember to normalise in these kinds of PRs, either by opening saving in Protege, or

```
sh run.sh make normalize_src
```

**Comment by anitacaron** [comment]
I normalized, and it worked. This time is deleting many `xsd:string`.

**Comment by matentzn** [comment]
Dont forget: https://obophenotype.github.io/cell-ontology/Fixing_xsdstring_diffs/ in CL..

**Comment by anitacaron** [comment]
After normalisation, I committed two changes (fix classes' names) in obsolete terms.

**Review by matentzn — APPROVED** [review]

**Comment by matentzn** [comment]
Excellent can be merged.

**Pull request merged**
