### PR TITLE
Fixes #2049 add soma location OFF-bipolar cell

### LINKED ISSUE #2049: [Class hierarchy] OFF-bipolar cell 'has soma location' some 'inner nuclear layer of retina'
**CL term**
OFF-bipolar cell CL:0000750

**Suggested revision of class hierarchy**
It is missing [has soma location](https://www.ebi.ac.uk/ols4/ontologies/cl/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FRO_0002100?lang=en) some [inner nuclear layer of retina](https://www.ebi.ac.uk/ols4/ontologies/cl/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0001791?lang=en).

### PR DESCRIPTION
**Pull request by aleixpuigb**
Fixes #2049 add soma location OFF-bipolar cell

### CODE REVIEW

**Comment by aleixpuigb** [comment]
#gogoeditdiff

**Review by bvarner-ebi — COMMENTED** [review]
Consider if it is more appropriate to place this axiom at the level of the parent class, CL:0000748 'retinal bipolar neuron'.

**Comment by aleixpuigb** [comment]
> Consider if it is more appropriate to place this axiom at the level of the parent class, CL:0000748 'retinal bipolar neuron'.

Thank you for the suggestion, I will add this axiom to 'retinal bipolar neuron' and remove from ON-bipolar cell.

**Comment by aleixpuigb** [comment]
#gogoeditdiff

**Comment by dosumis** [comment]
I think moving the soma location axiom to the more general term makes sense from what I know of the biology.  For a broader review of the biology - I've found this useful:

Euler, T., Haverkamp, S., Schubert, T., & Baden, T. (2014). Retinal bipolar cells: elementary building blocks of vision. Nature Reviews Neuroscience, 15(8), 507–519. https://doi.org/10.1038/nrn3783

**Review by bvarner-ebi — APPROVED** [review]

**Pull request merged**
