### PR TITLE
goblet_cell_definition - Fixes #2453

### LINKED ISSUE #2453: [Text def] goblet cell
**CL term**

goblet cell

**Suggested revision of textual definition**

A specialized, columnar, mucus secreting epithelial cell with a shape that resembles a flask or goblet. A narrow basal end contains the nucleus while the apical end swollen by the accumulation of mucus laden secretory granules.  Short microvilli project from the apical plasma membrane.

### PR DESCRIPTION
**Pull request by dosumis**
@JABelfiore -  Please review text for clarity

### CODE REVIEW

**Review by JABelfiore — APPROVED** [review]
Suggested text amend: 

A specialized, columnar, mucus-secreting epithelial cell shaped like a flask or goblet. The cell has a narrow basal end containing the nucleus and a swollen apical end filled with mucus-laden secretory granules. Short microvilli extend from the apical plasma membrane.

**Comment by dosumis** [comment]
> Suggested text amend:
> 
> A specialized, columnar, mucus-secreting epithelial cell shaped like a flask or goblet. The cell has a narrow basal end containing the nucleus and a swollen apical end filled with mucus-laden secretory granules. Short microvilli extend from the apical plasma membrane.

Thanks! Revised.  @JABelfiore Please ask @aleixpuigb  about doing suggested edits for these.  Might be quicker.

Also needs GO update.  @aleixpuigb  would you be able to show @JABelfiore how to run these?

**Comment by aleixpuigb** [comment]
> Also needs GO update. @aleixpuigb would you be able to show @JABelfiore how to run these?

We can do during the sprint meeting, so @Caroline-99 and @AvolaAmg can also learn it if they don't know how to update imports. It will take only 2 minutes

**Comment by AvolaAmg** [comment]
Thanks @aleixpuigb 
I would benefit from knowing how to run the GO update.

**Comment by dosumis** [comment]
#gogoeditdiff

**Comment by dosumis** [comment]
Needs approval before merge. Can you give it a quick check over?

**Review by aleixpuigb — APPROVED** [review]

**Pull request merged**
