### PR TITLE
Closes #1435 [NTR] TEMRA: terminally differentiated effector memory c…

### LINKED ISSUE #1435: [NTR] TEMRA: terminally differentiated effector memory cells re-expressing CD45RA
@addiehl please
Currently in CL "TEMRA" is a broad synonym for both
CL:0001062 effector memory CD8-positive, alpha-beta T cell, terminally differentiated
and
CL:0001087 effector memory CD4-positive, alpha-beta T cell, terminally differentiated
As far as I can see, there isn't a broader term in CL to represent TEMRA cells.
Based on usage in literature, would you consider adding one please? 
If the specs below are correct, I can add it myself.

**Preferred term label:**
effector memory CD45RA-positive, alpha-beta T cell, terminally differentiated

**Synonyms**
terminally differentiated effector memory cells re-expressing CD45RA (exact) (https://en.wikipedia.org/wiki/T_cell#Memory_T_cells)
terminally differentiated effector memory CD45RA+ T cells (exact) (PMID:25104859)
TEMRA cell (exact) (PMID:25104859)
effector memory RA T cell (broad? if not exact) (PMID:16237082)
TEMRA (broad or related, with has_synonym_type=abbreviation) (PMID:16237082)

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
An alpha beta memory T cell with the phenotype CD45RA-positive.

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
CL:0000791 mature alpha-beta T cell

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0002-2825-0621

**Any additional notes or concerns**
To become parent of 
CL:0001062 effector memory CD8-positive, alpha-beta T cell, terminally differentiated
and
CL:0001087 effector memory CD4-positive, alpha-beta T cell, terminally differentiated

Thank you.
Paola

### PR DESCRIPTION
**Pull request by bvarner-ebi**
Closes #1435 [NTR] TEMRA: terminally differentiated effector memory cells re-expressing CD45RA

### CODE REVIEW

**Comment by bvarner-ebi** [comment]
@paolaroncaglia, could you confirm that 'alpha beta' in the definition should not be hyphenated?
I will appreciate your review.

**Comment by addiehl** [comment]
'alpha-beta' definitely should be hyphenated in the definition.

**Comment by bvarner-ebi** [comment]
> 'alpha-beta' definitely should be hyphenated in the definition.

Thank you, @addiehl. I revised the definition.

**Review by paolaroncaglia — COMMENTED** [review]
Hi @bvarner-ebi ,
This looks great, thank you!
One minor comment (and it's my bad, not yours): the annotation property has_synonym_type=abbreviation is not available in CL. It is in Uberon, and I remembered it from there. So please remove the text string "abbreviation" from the broad synonym TEMRA for now. If you'd like, it might be a useful exercise to open a new ticket to import the annotation property has_synonym_type = abbreviation into CL, but that's optional. Other than that, your PR is good, feel free to merge once you've removed "abbreviation". Thanks.

**Comment by bvarner-ebi** [comment]
Thank you for the advice, @paolaroncaglia.
I opened #1441. I'll merge this for now and can readdress adding the 'abbreviation' synonym_type_property once it is available in CL.

**Review by paolaroncaglia — APPROVED** [review]

**Pull request merged**
