### PR TITLE
Add cl pcl combined product

### LINKED ISSUE #1683: CL - PCL product
CL + PCL combined product as been suggested by the community 
Possible concerns: PCL is huge as is, hopefully CL + PCL is manageable. 
Other than that it should be a simple custom make goal

### PR DESCRIPTION
**Pull request by shawntanzk**
Fixes #1683

Currently when making cl.owl - it does produce a combined product in owl format.
However, obo and json format conversion seems to have issues. 
I think this is due to custom stuff we use in PCL:
```
ERROR Input ontology contains 558 triple(s) that could not be parsed:
 - <http://purl.obolibrary.org/obo/PCL_0011569> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> _:genid2147629726.
 - <http://purl.obolibrary.org/obo/PCL_0023582> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> _:genid2147630205.
 - <http://purl.obolibrary.org/obo/PCL_0011575> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> _:genid2147629732.
 - <http://purl.obolibrary.org/obo/PCL_0019583> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> _:genid2147630085.
 - <http://purl.obolibrary.org/obo/PCL_0019508> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> _:genid2147630010.
 - <http://purl.obolibrary.org/obo/PCL_0011752> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> _:genid2147629822.
 ```

### CODE REVIEW

**Comment by shawntanzk** [comment]
Will also want to test running a full release to make sure everything runs fine before merging

**Comment by matentzn** [comment]
FYI: https://github.com/EnvironmentOntology/envo/issues/1283

Could be the same OWLAPI issue, and its not a problem if so.

**Comment by shawntanzk** [comment]
@matentzn - I think this is ready. Did a test and seems ok. Thanks!

**Comment by shawntanzk** [comment]
using CL-base instead of CL-full -> hopefully that will reduce the size

**Comment by shawntanzk** [comment]
Moved to https://github.com/obophenotype/provisional_cell_ontology/pull/41

**Pull request closed without merging**
