### PR TITLE
Addresses #1718 edit telocyte

### PR DESCRIPTION
**Pull request by bvarner-ebi**
Addresses #1718 edit telocyte

### CODE REVIEW

**Comment by bvarner-ebi** [comment]
@emquardokus, can kindly review the updates?

**Comment by emquardokus** [comment]
@bvarner-ebi looks good! Thanks!

**Review by emquardokus — APPROVED** [review]
Looks good! Thank you for taking care of this.

**Comment by bvarner-ebi** [comment]
Thanks for reviewing, @emquardokus!

**Pull request merged**
