### PR TITLE
Fix wrong CL Ids

### LINKED ISSUE #1112: UUID IRI used in six axioms
There is a term `http://purl.obolibrary.org/obo/D96882F1-8709-49AB-BCA9-772A67EA6C33` with no label or any other annotations which is used in six axioms for 'immature basophil', 'immature eosinophil', and 'immature neutrophil'.

These are all meant to have some unknown thing as a part.

### PR DESCRIPTION
**Pull request by matentzn**
Fixes #1112 #498

Not addressed is the issue of retrofitting this to have GO:CC + PATO definitions, #572

### CODE REVIEW

**Comment by shawntanzk** [comment]
guessing the error in checks is caused by terms using CP that you have obsoleted? 
Not sure if there's any automated way, but if not, happy to remap them if needed

**Comment by matentzn** [comment]
No, the imports need to be tweaked a bit, gimme a sec.. CP ids still come through from PATO and Uberon..

**Comment by matentzn** [comment]
This PR must be approved by @dosumis who prefers to deal with this issue somewhat differently. Do not merge before he approves.

**Comment by matentzn** [comment]
@shawntanzk can you remove and merge this? @dosumis says its fine.

**Comment by shawntanzk** [comment]
> @shawntanzk can you remove and merge this? @dosumis says its fine.

not sure what you mean by remove?

**Comment by matentzn** [comment]
Review and merge. Not remove. my brain is fried.

**Review by shawntanzk — APPROVED** [review]

**Pull request merged**
