### PR TITLE
Related to #1810 unresolvable IRIs

### PR DESCRIPTION
**Pull request by bvarner-ebi**
Related to #1810 unresolvable IRIs 
assigned numeric IDs to native CL object properties

### CODE REVIEW

**Comment by bvarner-ebi** [comment]
QC appears to fail because two of the three renamed entities have an 'expand expression to' annotation, which is not permitted for terms with CL IRIs per  ../sparql/illegal-annotation-property-violation.sparql:

```
FAIL Rule ../sparql/illegal-annotation-property-violation.sparql: 2 violation(s)
[32](https://github.com/obophenotype/cell-ontology/actions/runs/4241973672/jobs/7372881034#step:4:33)
term,annotation
[33](https://github.com/obophenotype/cell-ontology/actions/runs/4241973672/jobs/7372881034#step:4:34)
http://purl.obolibrary.org/obo/CL_4030046,http://purl.obolibrary.org/obo/IAO_0000424
[34](https://github.com/obophenotype/cell-ontology/actions/runs/4241973672/jobs/7372881034#step:4:35)
http://purl.obolibrary.org/obo/CL_4030045,http://purl.obolibrary.org/obo/IAO_0000424
```

**Review by balhoff — APPROVED** [review]

**Comment by bvarner-ebi** [comment]
Thanks for reviewing, @balhoff.
@matentzn, can you comment on [the QC failure noted above](https://github.com/obophenotype/cell-ontology/pull/1854#issuecomment-1439837290)? Is there a reason that annotation is blocked for CL terms?

**Comment by matentzn** [comment]
This failure gives me great peace of mind. All you need to do is edit the 

../sparql/illegal-annotation-property-violation.sparql file and add the new property to the list of allowed properties. You can do this on this branch here, and assign me as a reviewer

**Comment by bvarner-ebi** [comment]
Thanks, @matentzn. SPARQL file updated.
Why are some annotations blocked for CL terms?

**Comment by bvarner-ebi** [comment]
> Looks great! Now QC should pass. Thanks!

Why are some annotations blocked for CL terms?

**Comment by bvarner-ebi** [comment]
> Generally, this solves two purposes:
...

Thank you for the context and for the review!

**Pull request merged**
