### PR TITLE
Addresses #2150 Standardise annotation property: abbreviation

### PR DESCRIPTION
**Pull request by ghost**
Addresses #2150: Standardise annotation property: abbreviation

### CODE REVIEW

**Comment by bvarner-ebi** [comment]
#gogoeditdiff

**Comment by bvarner-ebi** [comment]
@anitacaron, can you help troubleshoot this error?

**Level	Rule Name	Subject	Property	Value**
ERROR	multiple_definitions	sncg GABAergic cortical interneuron	definition	A GABAergic neuron located in the cerebral cortex that expresses Gamma-synuclein
ERROR	multiple_definitions	sncg GABAergic cortical interneuron	definition	<xref:(ILX:0770150)>

There appears to be only one definition...

**Comment by anitacaron** [comment]
@bvarner-ebi, where do you see this error?

The error failing the QC in this branch is
```
ERROR	missing_label	OMO:0003000	rdfs:label	
```

I'll check why it's not getting the label from the merged_import.owl

**Comment by bvarner-ebi** [comment]
> @bvarner-ebi, where do you see this error?

The QC report output mentions: "*** [Makefile:199: reports/cl-edit.owl-obo-report.tsv] Error 1"
Looking at [that file](https://github.com/obophenotype/cell-ontology/blob/2150-replace_abbreviation_syn_type_prop/reports/cl-edit.owl-obo-report.tsv) now, it looks like it is 2 years old, so please disregard.

> I'll check why it's not getting the label from the merged_import.owl

Thank you.

**Comment by bvarner-ebi** [comment]
> I'll check why it's not getting the label from the merged_import.owl

The label does appear in Protégé. Thank you for investigated why it's not being recognised.

Screenshot 2023-09-25 at 14 20 11

**Comment by anitacaron** [comment]
> The QC report output mentions: "*** [Makefile:199: reports/cl-edit.owl-obo-report.tsv] Error 1"
Looking at [that file](https://github.com/obophenotype/cell-ontology/blob/2150-replace_abbreviation_syn_type_prop/reports/cl-edit.owl-obo-report.tsv) now, it looks like it is 2 years old, so please disregard.

The file `reports/cl-edit.owl-obo-report.tsv` is related to `src/ontology`. 

The 5 first violations on this report are what you see in the QC log.

Screenshot 2023-09-25 at 14 26 16

**Comment by anitacaron** [comment]
You can remove them, please.

**Comment by anitacaron** [comment]
The issue appeared after this commit https://github.com/obophenotype/cell-ontology/pull/2159/commits/677cd19fab2cbdd600b63cd1776721e0435d7edd. This axiom is part of the property in OMO, you can remove it. I'm checking to import this too.

**Review by aleixpuigb — COMMENTED** [review]
All seems ok, but just to double check, the deletion of the import of `http://purl.obolibrary.org/obo/uberon/core#ABBREVIATION` will be addressed in a different ticket as you mentioned in the ticket, right? As it is not used I wasn't sure if it could just be removed.

**Comment by bvarner-ebi** [comment]
> All seems ok, but just to double check, the deletion of the import of `http://purl.obolibrary.org/obo/uberon/core#ABBREVIATION` will be addressed in a different ticket as you mentioned in the ticket, right? As it is not used I wasn't sure if it could just be removed.

Thank you for checking.


If http://purl.obolibrary.org/obo/uberon/core#ABBREVIATION is not removed after the [Uberon updates have been made](https://github.com/obophenotype/uberon/issues/3079) and refreshed in CL, it can be deleted in CL.

**Review by aleixpuigb — APPROVED** [review]

**Pull request merged**
