### PR TITLE
2021-11-25 Release

### PR DESCRIPTION
**Pull request by shawntanzk**
Release Notes:

New Terms:
- specified double negative thymocyte (Homo sapiens)
- committed double negative thymocyte (Homo sapiens)
- rearranging double negative thymocyte (Homo sapiens)
- monocyte-derived dendritic cell
- type 1 spiral ganglion neuron
- type 2 spiral ganglion neuron
- cochlea auditory hair cell

Edits:
- Temporary fix on enterocyte of the appendix (will break if uberon import is refreshed)
- Made auditory hair cell more general 
- Fixed def of Cajal-Retzius cell
- Added some comments on thyocte cells 
- Added various synonyms
- Merged myoepithelial cell of lactiferous gland
- Added layer axioms and equivalent classes for a bunch of neuronal cells

### CODE REVIEW

**Comment by shawntanzk** [comment]
Currently enterocyte of the appendix temporarily fixed by forcefully placing a uberon mirror file that excludes offending axioms by removing all uberon_* terms in cl_import.owl in uberon (yes very cyclical)  

Failure due to obsolete myoepithelial cell of lactiferous gland - will look into this, but im guessing its cause uberon axioms of these (hopefully not cyclical again), will look into this

**Comment by shawntanzk** [comment]
Ok fixed :) all ready to go

**Review by paolaroncaglia — COMMENTED** [review]
@shawntanzk 
I've reviewed cl-base.owl wrt "my" terms and all looks good, thanks.
What's the file I should check to review the changes for 'enterocyte of appendix' please? cl-full? TIA, I'm a bit in a rush this morning...

**Comment by shawntanzk** [comment]
@paolaroncaglia if all good, could you give a thumbs up in the review please, thanks

**Review by paolaroncaglia — APPROVED** [review]

**Pull request merged**
