### PR TITLE
Fixes #2576 ntr intestinal subserosal fibroblast

### LINKED ISSUE #2576: [NTR] intestinal subserosal fibroblast
Please check that the term does not already exist by using the ontology search tool OLS:
https://www.ebi.ac.uk/ols4/ontologies/cl

**Preferred term label**
intestinal subserosal fibroblast

**Synonyms** (add reference(s), please)

**Definition** (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX)
A fibroblast that is part of the subserosa of the intestine. This cell interacts with immune cells and play roles in inflammation and fibrosis. In certain conditions, such as Crohn's disease, subserosal fibroblast may differentiate into myofibroblasts.

[PMID:23143399](https://pubmed.ncbi.nlm.nih.gov/23143399/)
[PMID: 26694715](https://pubmed.ncbi.nlm.nih.gov/26694715/)
PMID: [38877292](https://pubmed.ncbi.nlm.nih.gov/38877292)

**Parent cell type term** (check the hierarchy here https://www.ebi.ac.uk/ols4/ontologies/cl)
fibroblast (maybe -  a new grouping term intestinal fibroblast could be added)

**Anatomical structure where the cell type is found** (check Uberon for anatomical structures: https://www.ebi.ac.uk/ols4/ontologies/uberon)
[subserosa](http://purl.obolibrary.org/obo/UBERON_0012375) - maybe a new term for subserosa of intestine is needed 
adjacent to [serosa of intestine](http://purl.obolibrary.org/obo/UBERON_0001243)

**Your ORCID**

**Additional notes or concerns**

### PR DESCRIPTION
**Pull request by Caroline-99**
Added a new term 'intestinal subserosal fibroblast' with textual and logical defs and references

### CODE REVIEW

**Comment by Caroline-99** [comment]
#gogoeditdiff

**Comment by dosumis** [comment]
I think that this really needs to be a part of subserosa of intestine- but looks like  Uberon is missing a  term for this.  

image

Based on classification of the serosa - this term could justifiably subsume subserosa

http://purl.obolibrary.org/obo/UBERON_0000042

image

Looks to me like the connective tissue mentioned in this definition is the subserosa.

So - we could make a part relationship to serosa of intestine for now, until we extend uberon.

**Comment by Caroline-99** [comment]
> I think that this really needs to be a part of subserosa of intestine- but looks like Uberon is missing a term for this.
> 
> image
> Based on classification of the serosa - this term could justifiably subsume subserosa
> 
> http://purl.obolibrary.org/obo/UBERON_0000042
> 
> image
> Looks to me like the connective tissue mentioned in this definition is the subserosa.
> 
> So - we could make a part relationship to serosa of intestine for now, until we extend uberon.

I will change it to` part of some serosa of intestine` for now and I will make an uberon ticket for `subserosa of intestine`. 
For now, do I get rid of` part of some subserosa ` as well ?

**Comment by dosumis** [comment]
I think it wouldn't do any harm to keep the subserosa bit too.  The basic problem is that Uberon classifies serosa as serosal membrane, which seems to include subserosa (although not formally).  But the term subserosa makes it sound distinct. We could go through and do a larger edit to Uberon to make consistent.

**Review by AvolaAmg — APPROVED** [review]

**Pull request merged**
