### PR TITLE
Fibroblasts are stromal

### LINKED ISSUE #2281: 'fibroblast' is not a decendent of 'stromal cell' [Class hierarchy]
**CL term**

`fibroblast` is a child of `connective tissue cell`
`stromal cell` is a child of `connective tissue cell`

However, there is no relationship between fibroblast and stromal cell. It is the general usage that cells from a tissue are broken up into stromal, immune, endothelial, and epithelial compartments, and fibroblasts are generally accepted as a subset of the stromal cells. So, this would create confusion if users are interested in all stromal cells at CELLxGENE, but then do will not actually be selecting from fibroblasts.

For example, fibroblasts are considered to be stromal cells in the following example, and any cells labeled as stromal cell are non-specific stromal cell: https://cellxgene.cziscience.com/collections/5c868b6f-62c5-4532-9d7f-a346ad4b50a7 (https://doi.org/10.1016/j.immuni.2023.01.002) Fig1:

Screenshot 2024-02-15 at 1 52 42 PM

This [publication](http://10.0.13.62/ijms222413422) has a summary:

> The term “stromal cells” refers to a highly heterogeneous class of connective tissue cells that build the infrastructure of any organ and fulfill a variety of fundamental roles in health and disease. Embedded into the framework of stromal cells are parenchymal cells, which define the specific function of an organ. Distinctive populations of stromal cells with different morphologies and functions include (i) fibroblasts, pericytes, and telocytes that are widely distributed throughout various organ systems; (ii) cells with stemness features, such as bone-marrow-derived mesenchymal stem/stromal cells (MSCs) and adipose tissue-derived stem/stromal cells (ASCs); and (iii) stromal cells specifically restricted to some organs, such as interstitial cells of Cajal in the gastrointestinal tract muscularis and fibroblastic reticular cells in secondary lymphoid organs, among others.

**Suggested revision of class hierarchy**

It is unclear the intended cell that is being described by the definition of `stromal cell`:

> A connective tissue cell of an organ found in the loose connective tissue. These are most often associated with the uterine mucosa and the ovary as well as the hematopoietic system and elsewhere.

However, because 'stromal cell' is a commonly used cell type and associated with fibroblasts, it would be good to make sure that the hierarchy is reflective of the general understanding. 'stromal cell' sounds as if it potentially could be synonymous with `connective tissue cell`.

### PR DESCRIPTION
**Pull request by dosumis**
Fixes https://github.com/obophenotype/cell-ontology/issues/2281

### CODE REVIEW

**Comment by Caroline-99** [comment]
#gogoeditdiff

**Comment by dosumis** [comment]
Example check on inference with perplexity https://www.perplexity.ai/search/describe-what-is-known-about-f-Hd5CMxxbSaijeb1nfO0giQ

**Comment by dosumis** [comment]
Reasons this should pass review.

Checking newly inferred subclasses:

Terms referencing connective tissue in name must be stromal
- [x] fibroblast of outer membrane of prostatic capsule   https://www.perplexity.ai/search/describe-what-is-known-about-f-Hd5CMxxbSaijeb1nfO0giQ
- [x] pancreatic stellate cell - Description of location in def consistent with being stromal
- [z] Thymic type 1 and type 2 https://www.perplexity.ai/search/where-are-type-1-thymic-fibrob-mblclzGwSeeG__QezCx09Q

**Comment by aleixpuigb** [comment]
Hi @dosumis I saw that you have assigned me this PR. Is this a mistake and I am meant to review it or do I have to do anything with it? Thanks

**Comment by dosumis** [comment]
> Hi @dosumis I saw that you have assigned me this PR. Is this a mistake and I am meant to review it or do I have to do anything with it? Thanks

Just want to get this merged soon.  

If you agree with the basic premise (see ticket), then the remaining work is to review newly inferred classifications in https://github.com/obophenotype/cell-ontology/pull/2571#issuecomment-2356348094. 

I went though the list yesterday and checked that they seem reasonable - see 
https://github.com/obophenotype/cell-ontology/pull/2571#issuecomment-2402929415 for justifications.

If you are happy with these then please approve.

(I'm sure there's quit a bit of redundancy on top of what you've found, but this will get stripped in the release product, so not sure worth the extra work to fix)

**Review by aleixpuigb — APPROVED** [review]

**Pull request merged**
