### PR TITLE
Addresses #2004 NTR dorsal striatum medium spiny neuron subtypes

### PR DESCRIPTION
**Pull request by bvarner-ebi**
Addresses #2004 NTR dorsal striatum medium spiny neuron subtypes

### CODE REVIEW

**Comment by dosumis** [comment]
#gogoeditdiff

**Comment by dosumis** [comment]
image

Re use or 'part of' are the neurons entirely within the compartment(s) mentioned?
Also - I suspect that the semantics of `('dorsal striatum' and 'matrix compartment')` are not what you intend.  Is anything an instance of both 'dorsal striatum' and 'matrix compartment' ?

**Comment by dosumis** [comment]
Also looks like parent classes could do with some work. e.g. - medium spiny neuron should be GABA-ergic.  SHould probably also have location recorded using has_soma_location rather than part_of given that these are projection neurons.

**Comment by bvarner-ebi** [comment]
> Re use or 'part of': are the neurons entirely within the compartment(s) mentioned?

Thank you for the feedback. Will change to 'has soma location'.

> Also looks like parent classes could do with some work. e.g. - medium spiny neuron should be GABA-ergic. SHould probably also have location recorded using has_soma_location rather than part_of given that these are projection neurons.

Will open a separate ticket to address.

> Also - I suspect that the semantics of ('dorsal striatum' and 'matrix compartment') are not what you intend. Is anything an instance of both 'dorsal striatum' and 'matrix compartment' ?

The reference paper for these new cell type terms refers to MSNs found in the matrix compartments that are part of the DS. My understanding is that these matrix compartments are considered part of the striatum, so I believe the answer is yes.

> Do we need an Uberon term for "matrix compartment of dorsal striatum"?

Is it preferred to add another term to Uberon or simply assert this cell type is found in matrix compartments that are also part of the DS?

**Comment by dosumis** [comment]
> Is it preferred to add another term to Uberon or simply assert this cell type is found in matrix compartments that are also part of the DS?

Strictly, we're not asserting this anywhere right now. It's a bit hard to tell from the definitions, but based on usage 'matrix compartment' seems to be a general type with instances by region, whereas the term 'dorsal striatum' is use to refer to the whole region.  e.g. 

[matrix compartment of caudate nucleus](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0029001?lang=en)  Equivalent to
([matrix compartment](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0027368?lang=en) and [part of](https://www.ebi.ac.uk/ols4/ontologies/uberon/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FBFO_0000050?lang=en) [RO](https://www.ebi.ac.uk/ols4/ontologies/ro/properties/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FBFO_0000050) some [caudate nucleus](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0001873?lang=en))

So the correct anonymous class expression for the region we need to refer to here would be 

"'matrix compartment' and part of some 'dorsal striatum'", not "'matrix compartment' and 'dorsal striatum'".  If we add this as a class to Uberon, the reasoner will make it a superclass of 'matrix compartment of caudate nucleus' based on the caudate nucleus being 'part of' the dorsal striatum.

I think best to add to Uberon, but happy to use an anonymous class expression in CL for now.

**Comment by dosumis** [comment]
#gogoeditdiff

**Review by aleixpuigb — APPROVED** [review]
Everything looks fine.
My only comment is about the spelling of `extra-striosomal`. In the [dbxref](https://doi.org/10.1016/j.cub.2021.10.015) and [other articles](https://doi.org/10.1016/0304-3940(89)90048-7), it is used as `extrastriosomal`, but this might be one of the English (UK) and English (USA) differences in the spelling.

**Pull request merged**
