### PR TITLE
Change deploy_release to use release_assets instead of assets 

### PR DESCRIPTION
**Pull request by shawntanzk**
Not sure if this should stay in the end of the day, but for consistency, im making PR here since we have uploaded it this round. If we decide not to have it, can either revert or just not merge this.

### CODE REVIEW

**Comment by anitacaron** [comment]
Ok, I looked into makefile, and it should change the variable in to RELEASE_ASSETS instead of ASSETS.

```
FILTER_OUT=../patterns/definitions.owl ../patterns/pattern.owl reports/cl-edit.owl-obo-report.tsv
MAIN_FILES_RELEASE = $(foreach n, $(filter-out $(FILTER_OUT), $(ASSETS)), ../../$(n))
```

**Comment by shawntanzk** [comment]
ok tested it out, and i think you're right. Have remove the cp part in makefile and remove the merged_import - I think its ok to leave this release as it is , but next one will be fixed.

**Comment by anitacaron** [comment]
Ok, I'll do this already for the UBERON release.

**Comment by anitacaron** [comment]
Can you change the PR's title, please?

**Comment by anitacaron** [comment]
What do you think about this change, @matentzn?

**Comment by matentzn** [comment]
No objections

**Review by anitacaron — APPROVED** [review]

**Pull request merged**
