### PR TITLE
add new term CL_0011030 (dermal microvascular endothelial cell)

### LINKED ISSUE #1105: [NTR]dermal microvascular endothelium cell
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
dermal microvascular endothelium cell

**Synonyms**
DMEC cell

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
Has brenda id BTO:0004574

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**

**Your nano-attribution (ORCID)**

**Any additional notes or concerns**

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
close #1105

### CODE REVIEW

**Comment by paolaroncaglia** [comment]
Hi @nicolevasilevsky ,
The PR looks good to me, I have 3 comments:
SubClassOf(obo:CL_0011030 obo:CL_2000008) is redundant with the equivalence axiom, and should be removed;
The Brenda ID may be added as a definition dbxref;
When checking diffs, the annoying xsd:strings may be cleaned up as per https://github.com/obophenotype/cell-ontology/blob/master/docs/Fixing_xsdstring_diffs.md.
Hope this helps. Thanks!

**Comment by nicolevasilevsky** [comment]
Thanks @paolaroncaglia I made these changes

**Comment by nicolevasilevsky** [comment]
@paolaroncaglia @dosumis @addiehl would one of you like to approve this before I merge?

I'll go ahead and merge in a few days if I don't have a response.

thanks!

**Review by cmungall — APPROVED** [review]

**Comment by paolaroncaglia** [comment]
Hi @nicolevasilevsky ,

> @paolaroncaglia @dosumis @addiehl would one of you like to approve this before I merge?
> 
> I'll go ahead and merge in a few days if I don't have a response.

I see that Chris approved, but the branch has conflicts...
(Happy Thanksgiving in advance anyway)

**Comment by nicolevasilevsky** [comment]
Ah, thanks @paolaroncaglia. I fixed the conflict, I'll merge when it passes.

**Pull request merged**
