### PR TITLE
Early enterocyte of colon

### PR DESCRIPTION
**Pull request by JABelfiore**
def, refs and synonyms added

### CODE REVIEW

**Comment by dosumis** [comment]
#gogoeditdiff

**Review by dosumis — COMMENTED** [review]
Looks good, but can we do better in recording location -  maybe crypt wall?

**Review by dosumis — DISMISSED** [review]
At least some PMIDs look wrong.

**Comment by dosumis** [comment]
#gogoeditdiff

**Comment by dosumis** [comment]
Enterocyte of colon is now colonocyte, so name here should match (early colonocyte)

**Comment by JABelfiore** [comment]
> Member

 This term is already early colonocyte, early enterocyte of colon is a synonym

**Review by aleixpuigb — APPROVED** [review]
All changes have been addressed.

**Pull request merged**
