### PR TITLE
[DO NOT MERGE] Addresses #1698 NTR immune cell

### PR DESCRIPTION
**Pull request by bvarner-ebi**
Addresses #1698 NTR immune cell

### CODE REVIEW

**Comment by addiehl** [comment]
I oppose the addition of this cell type as redundant with leukocyte.

**Comment by bvarner-ebi** [comment]
> I oppose the addition of this cell type as redundant with leukocyte.

Thank you, @addiehl. I'll pose your objection to the requester and suggest they consider using 'leukocyte' and that we can add "immune cell" as a related synonym to that class.

**Comment by bvarner-ebi** [comment]
> > I oppose the addition of this cell type as redundant with leukocyte.
> 
> Thank you, @addiehl. I'll pose your objection to the requester and suggest they consider using 'leukocyte' and that we can add "immune cell" as a related synonym to that class.

Actually, @addiehl, I see "immune cell" is already an exact synonym for ['leukocyte'](http://purl.obolibrary.org/obo/CL_0000738). I can propose we change it to a related synonym.

**Comment by addiehl** [comment]
Yes, I think loosening the synonym type to "related" makes sense.

**Pull request closed without merging**
