### PR TITLE
2022-02-16 Release

### PR DESCRIPTION
**Pull request by shawntanzk**
Making a release to get the https://github.com/obophenotype/cell-ontology/pull/1446 into a release. See https://github.com/obophenotype/cell-ontology/issues/1359 for reason. 

@bvarner-ebi see https://obophenotype.github.io/cell-ontology/odk-workflows/ReleaseWorkflow/#review-the-release for how to review a release.

### CODE REVIEW

**Comment by dosumis** [comment]
> secretory cell seems to be removed from quite a few cell types - not sure why this is, anyone has any idea?

Maybe change to GO?

BTW - wondering why release doesn't include a nice readable ROBOT diff.  Maybe ODK feature request?

**Comment by shawntanzk** [comment]
> BTW - wondering why release doesn't include a nice readable ROBOT diff. Maybe ODK feature request?

reasoned ROBOT diff is built from cl-edit, so all the changes are already in.
Perhaps having a manual release diff action that just compares cl.owl directly? 
We do plan to have a general ROBOT diff format that has a variable that can slot in whichever file you want, though that would still make it which might run into the same problem. I think an easier solution might be to write that separately.

**Comment by shawntanzk** [comment]
> Maybe change to GO?

btws i have IMP=false on release (standard these days), so GO wouldn't be refreshed, that being said, it might have been in one of the PRs that is in this release

**Comment by bvarner-ebi** [comment]
> secretory cell seems to be removed from quite a few cell types - not sure why this is, anyone has any idea?

It appears CL:0000151 secretory cell was stripped of its superclasses (and all descriptions) in this new release.

**Comment by shawntanzk** [comment]
it seems this is a problem - why secretory cell not a native cell anymore? and when did that get introduced

Screenshot 2022-02-16 at 11 39 22

**Comment by shawntanzk** [comment]
if theres no objections, can I just add back: 
`EquivalentClasses(obo:CL_0000151 ObjectIntersectionOf(obo:CL_0000003 ObjectSomeValuesFrom(obo:RO_0002215 obo:GO_0032940)))` to secretory cell?

**Comment by dosumis** [comment]
Looks like a mistake to me.

**Comment by bvarner-ebi** [comment]
>  if theres no objections, can I just add back:
EquivalentClasses(obo:CL_0000151 ObjectIntersectionOf(obo:CL_0000003 ObjectSomeValuesFrom(obo:RO_0002215 obo:GO_0032940))) to secretory cell?

It looks like this was removed accidentally in one of my previous PRs (#1427). Apologies and thank you @shawntanzk for fixing the error.

**Comment by shawntanzk** [comment]
The secreting cells axioms have been added back - PR ready to go, do give a thumbs up if you're happy with it

**Comment by bvarner-ebi** [comment]
> see https://obophenotype.github.io/cell-ontology/odk-workflows/ReleaseWorkflow/#review-the-release for how to review a release.

Thank you for the link, @shawntanzk. I can't seem to find the actual steps required for a review at this stage (the PR). 
The instructions state to "review the following three files in detail (based on our experience)", but what are the steps for completing detailed reviews for the files?

**Comment by shawntanzk** [comment]
in this case, making sure your terms are what they suppose to be and no inference is wrong (eg removal of secretory cell). There really isn't a simple way I think, cause it depends on what changes you've made. In general I do a overall look to make sure nothing looks outrageous, so for you, mostly its on the terms you added - that no mistakes were made, that inferences get inferred rightly, etc.

**Comment by bvarner-ebi** [comment]
Thanks, @shawntanzk. 
Also, is there an established cadence or schedule for CL releases?

**Comment by shawntanzk** [comment]
> Also, is there an established cadence or schedule for CL releases?

nope, this has been brought up before for uberon I think, and the hesitation was to prevent too man releases which would be a problem with space in github. Don't fully remember the discussion, but know we have talked about this before. There are plans to move uberon to a s3 bucket (I have no idea what that actually means except that it solves our space issue lol) so maybe after that we can see that implemented in CL too

**Comment by paolaroncaglia** [comment]
> There are plans to move uberon to a s3 bucket (I have no idea what that actually means except that it solves our space issue lol) 

That's an [Amazon cloud storage solution](https://aws.amazon.com/s3/?nc1=h_ls) FYI.

**Comment by shawntanzk** [comment]
btws would really not like this to linger too long - if everything is alright please give a thumbs up, thanks :)

**Review by paolaroncaglia — COMMENTED** [review]
@shawntanzk as mentioned offline, I didn't do any CL edits since the CL release last month, so I don't have any terms of my own to double-check. The inferred hierarchy makes sense. I spot-checked a handful of random terms and they look ok. Noticed once again the lack of textual definition on several terms, but that's another story... to be hopefully dealt with as part of #1262 .

**Review by bvarner-ebi — APPROVED** [review]
I reviewed cl.owl and found my edits to be incorporated since the last release

**Pull request merged**
