### PR TITLE
Fixed def typo noted in #1368

### PR DESCRIPTION
**Pull request by bvarner-ebi**
Hi @paolaroncaglia, would you mind reviewing my fix for the definition typo noted in #1368?

### CODE REVIEW

**Review by paolaroncaglia — COMMENTED** [review]
(@dosumis please) 
Hi @bvarner-ebi ,
Thank you for your first CL pull request!
The typo fix itself is fine, but the pull request contains lots of spurious diffs that I'm not 100% sure about. @dosumis , could you take a look please?
Thanks,
Paola

**Comment by dosumis** [comment]
Hi @bvarner-ebi 

Your edit is to the wrong file. Should be to src/ontology/cl-edit.owl.  cl.owl is a release file (!).  Spurious diffs are, at least in part, due to this file being RDFXML, which, unlike the functional syntax used for the master file, is not safe for diffs.

 Please roll back changes or discard branch and start a new one.
Thanks!

**Review by dosumis — CHANGES_REQUESTED** [review]
See comment

**Comment by paolaroncaglia** [comment]
> Your edit is to the wrong file. 

Doh - I missed the forest for the tree. Note to self - never review or edit until you're properly caffeinated (especially if you're a bit spaced out after your vaccine booster). Sorry guys!

**Comment by bvarner-ebi** [comment]
Thank you for reviewing, @paolaroncaglia and @dosumis.
I will make a new branch with edits to the correct file.

**Pull request closed without merging**
