### PR TITLE
Closes #1475 NTR fallopian tube secretory epithelial cell

### LINKED ISSUE #1475: [NTR] fallopian tube secretory epithelial cell
**Preferred term label:**
fallopian tube secretory epithelial cell

**Synonyms**
oviduct secretory epithelial cell
uterine tube secretory epithelial cell

**Definition**
Fallopian tube secretory epithelial cell is one of the three cell types of the fallopian tube epithelium. The two other cell types of the fallopian tube epithelium are the ciliated cells and the intercalary cell, or peg cells. The secretory cell has approximately the same height as the ciliated cell and is usually a more narrow columnar cell. The nucleus is ovoid and perpendicular to the long axis of the cell. The chromatin is more dense and the nucleolus smaller than that seen in the ciliated cell. [https://www.proteinatlas.org/learn/dictionary/normal/fallopian+tube]

**Parent cell type term:**
CL:1001591 (oviduct glandular cell)

**What is the anatomical structure that the cell is a part of?**
UBERON:0003889 (fallopian tube)

**Your nano-attribution (ORCID)**
0000-0002-0819-0473

### PR DESCRIPTION
**Pull request by bvarner-ebi**
Closes #1475 NTR fallopian tube secretory epithelial cell

### CODE REVIEW

**Review by paolaroncaglia — APPROVED** [review]
Hi @bvarner-ebi ,
This PR is ok so I'll approve it, but I have a comment. It looks like the new term would be the only child of its parent. The suggested definition (as well as the current definition of the suggested parent) mentions the existence of two sibling cell types, that are not in CL or in NTRs apparently. Ideally we'd want to have them in CL. OTOH, I'm not sure how specific they'd be, especially the ciliated cell type (would the location be the only differentia with its parent 'ciliated cell'? I know, there are precedents). So it's a balance. Up to you if you'd like to ask the submitter if she could provide informative details to warrant addition of the 2 siblings; consider my comment as part of ontology training. :-) Thanks.

**Comment by bvarner-ebi** [comment]
Thank you, @paolaroncaglia, for the suggestion! I will ask the submitter if she would like to provide details for the other cell types.

**Comment by shawntanzk** [comment]
>  It looks like the new term would be the only child of its parent.

Not sure if this is ideal, as in reasoned ontology it will end up the same, but given that oviduct glanduloar cell has an equiv class axiom, technically you could put it as a child of glandular epithelial cell and it should automatically reason there.

**Comment by shawntanzk** [comment]
defintion:

**Comment by shawntanzk** [comment]
defintion doesnt mention anything about secretory part which i think is an issue, and in general the definidum doesnt seem to really define the cell type.
I personally also think "The other cell types of the fallopian tube epithelium are the ciliated cell and the intercalary cell, or peg cell." should come at the end of the gloss as it doesnt directly relate to defining the cell type, but this might be more personal.

**Comment by bvarner-ebi** [comment]
> defintion doesnt mention anything about secretory part which i think is an issue, and in general the definidum doesnt seem to really define the cell type.
> I personally also think "The other cell types of the fallopian tube epithelium are the ciliated cell and the intercalary cell, or peg cell." should come at the end of the gloss as it doesnt directly relate to defining the cell type, but this might be more personal.

I agree, @shawntanzk. I considered moving the part referencing other cells to a comment or removing totally.

**Comment by shawntanzk** [comment]
>  moving the part referencing other cells to a comment or removing totally.

I would move it to comment, cause I think its still super useful :)

**Comment by bvarner-ebi** [comment]
> defintion doesnt mention anything about secretory part which i think is an issue, and in general the definidum doesnt seem to really define the cell type.
> I personally also think "The other cell types of the fallopian tube epithelium are the ciliated cell and the intercalary cell, or peg cell." should come at the end of the gloss as it doesnt directly relate to defining the cell type, but this might be more personal.

I revised the definition and will appreciate your review.

**Comment by shawntanzk** [comment]
Looks good. Just one change in the gloss - "This cell type has been implicated as a source of high-grade serous ovarian carcinoma." should be in comment.

**Comment by bvarner-ebi** [comment]
> Looks good. Just one change in the gloss - "This cell type has been implicated as a source of high-grade serous ovarian carcinoma." should be in comment.

Thank you. Done!

**Review by paolaroncaglia — APPROVED** [review]

**Review by shawntanzk — APPROVED** [review]

**Pull request merged**
