### PR TITLE
2021-04-22 release

### PR DESCRIPTION
**Pull request by shawntanzk**
**New Terms:**

•	upper motor neuron
•	Betz cell
•	fetal hepatobiliary progenitor cell
•	tuft cell of appendix
•	enterocyte of appendix
•	transit amplifying cell of appendix
•	intestinal crypt stem cell of appendix
•	L6b glutamatergic cortical neuron
•	L2/3-6 intratelencephalic projecting glutamatergic cortical neuron
•	L5 extratelencephalic projecting glutamatergic cortical neuron
•	L6 corticothalamic-projecting glutamatergic cortical neuron
•	L5/6 near-projecting glutamatergic neuron of the primary motor cortex (Mus musculus)
•	non-medulla-projecting extratelencephalic-projecting glutamatergic neuron of the primary motor cortex (Mus musculus)
•	medulla-projecting extratelencephalic-projecting glutamatergic neuron of the primary motor cortex (Mus musculus)
•	L6b subplate glutamatergic neuron of the primary motor cortex (Mus musculus)
•	L2/3 intratelencephalic projecting glutamatergic neuron of the primary motor cortex (Mus musculus)
•	L4/5 intratelencephalic projecting glutamatergic neuron of the primary motor cortex (Mus musculus)
•	L5 intratelencephalic projecting glutamatergic neuron of the primary motor cortex (Mus musculus)
•	L6 intratelencephalic projecting glutamatergic neuron of the primary motor cortex (Mus musculus)
•	vascular leptomeningeal cell
•	Betz upper motor neuron
•	spinal interneuron synapsing Betz cell
•	mesothelial fibroblast
•	corticothalamic VAL/VM projecting glutamatergic neuron of the primary motor cortex (Mus musculus)
•	vascular leptomeningeal cell (Mus musculus)
•	mesothelial fibroblast of the leptomeninx
•	meis2 expressing cortial GABAergic cell (Mus musculus)
•	mesothelial cell of appendix
•	enteroendocrine cell of appendix
•	T cell of appendix
•	B cell of appendix
•	plasma cell of appendix
•	dendritic cell of appendix

**Imports:**

•	PATO_0070001
•	PATO_0070007
•	PATO_0070008
•	PATO_0070009
•	PATO_0070011
•	PATO_0070017
•	PATO_0070019

•	PR_000002030
•	PR_000003264
•	PR_000009981
•	PR_P11087
•	PR_P26618 
•	PR_P51885 
•	PR_P97367

•	UBERON_0000391
•	UBERON_0001896
•	UBERON_0002707
•	UBERON_0013486
•	UBERON_0022315

•	RO_0002175
•	RO_0002101

Edits:

- BDS subset terms: changed location details in definition to "with a soma found in"
- Added BDS subset tags where missing

### CODE REVIEW

**Comment by paolaroncaglia** [comment]
@shawntanzk 

You might consider removing the extra "projecting" in the labels below, please?
L6 corticothalamic-projecting projecting glutamatergic cortical neuron
non-medulla projecting extratelencephalic projecting glutamatergic neuron of the primary motor cortex (Mus musculus)
medulla projecting extratelencephalic projecting glutamatergic neuron of the primary motor cortex (Mus musculus)

Also, tiny typo here:
spinal interneuron syanpsing Betz cell

Thanks! :-)
Paola

**Comment by paolaroncaglia** [comment]
Also, I was literally about to merge 6 new cell types for the Single Cell Atlas appendix anatomogram... am I still in time for this release please?

**Comment by shawntanzk** [comment]
Thanks @paolaroncaglia :) 
L6 corticothalamic-projecting projecting glutamatergic cortical neuron is defs a mistake, the other 2 are actually correct. 
and will get the typo, thanks so much for spotting it! 
If you dont mind, is it ok if I pushed this release first and I'll push another one with the 6 new cell types tomorrow? 
I've been going through the files to check and I think I will get confused with more additions at this point >.<

**Comment by shawntanzk** [comment]
> If you dont mind, is it ok if I pushed this release first and I'll push another one with the 6 new cell types tomorrow?
> I've been going through the files to check and I think I will get confused with more additions at this point >.<

actually take that back, if im going to make the edits anyway, will go through again anyway :) let me know once they are merged and I'll re-run the release? Thanks

**Comment by paolaroncaglia** [comment]
Thanks very much @shawntanzk , I'll merge now and comment here in a moment.

**Comment by paolaroncaglia** [comment]
In case it's helpful:

> L6 corticothalamic-projecting projecting glutamatergic cortical neuron is defs a mistake, the other 2 are actually correct.

Ah ok, great. Possibly the labels may be clearer as follows? Just a suggestion - I know you have been working a lot on these:

non-medulla-projecting extratelencephalic-projecting glutamatergic neuron of the primary motor cortex (Mus musculus)
medulla-projecting extratelencephalic-projecting glutamatergic neuron of the primary motor cortex (Mus musculus)

**Comment by paolaroncaglia** [comment]
@shawntanzk 
My PRs are merged, thanks again! (FYI, https://github.com/obophenotype/cell-ontology/pull/1044)

**Comment by shawntanzk** [comment]
> Ah ok, great. Possibly the labels may be clearer as follows? Just a suggestion - I know you have been working a lot on these:
> 
> non-medulla-projecting extratelencephalic-projecting glutamatergic neuron of the primary motor cortex (Mus musculus)
> medulla-projecting extratelencephalic-projecting glutamatergic neuron of the primary motor cortex (Mus musculus)

oooo that's smart, does clarify it a lot, yeah ill make that change, thanks so much!

**Comment by matentzn** [comment]
@shawntanzk going strong!!! Awesome work all around!

**Review by paolaroncaglia — APPROVED** [review]
Hi @shawntanzk ,
I've had a quick look at cl-base.obo and cl-basic.obo and they look fine to me. There are other files to check, but I've never done a CL release, and I wouldn't want to hold things up as I'll be busy the rest of today, so I'm approving and leaving it to @matentzn or @dosumis to confirm. Thanks, great job!
Paola

**Review by matentzn — APPROVED** [review]
Technically this appears perfect! Great job! be carefully about the v tag when you make a Github version!

**Pull request merged**
