### PR TITLE
Add telocyte (CL:0017004)

### LINKED ISSUE #1048: [NTR] telocyte
**Preferred term label:**
telocyte

**Synonyms**
interstitial Cajal-like cell; ICLC; interstitial Cajal cell-like cell

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
A cell with a small, oval-shaped body with around 10 micrometers of diameter present in the interstitium. It has one to five long cytoplasmic protrusions (telopodes) extending from tens to hudreds of micrometers and mostly below 0.2 microns of caliber. PMID:20367664

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
CL:0000630 (supportive cell) is one possibility. 

Maybe a parent new term "interstitial cell" could be interesting.  

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**

Found in a number of different organs, including kidney, heart, pancreas, placenta and more. I am not sure which to add. In addition, telocytes in different tissues might have different markers and execute different functions. 

**Your nano-attribution (ORCID)**
0000-0003-2473-2313

**Any additional notes or concerns**

Has a few possible crossrefs: 

**Wikipedia**: https://en.wikipedia.org/wiki/Telocyte
**MeSH**: https://meshb.nlm.nih.gov/record/ui?ui=D000067170
**Wikidata**: https://www.wikidata.org/wiki/Q7697784

### PR DESCRIPTION
**Pull request by lubianat**
Closes #1048 .

Telocytes are a rather common intersticial cell. It was also mentioned in #1155.

Note: a few spurious diffs appearing after running the normalisation script, but it seems manageable.

Description is a bit chunky, any ideas on shortening it are welcome.

I'm not sure who to assign as a reviewer, I'll try @nicolevasilevsky  but feel free to reassign (perhaps @gouttegd can help here?)

### CODE REVIEW

**Review by dosumis — COMMENTED** [review]
Looks good.  Wondering if 'connective tissue cell' might be a better classification? 

Can you also request telopode from GO?  From a quick look at [Wikipedia](https://en.wikipedia.org/wiki/Telocyte), it seems they have sufficiently distinctive structure to justify a GO Cellular_compoment term.  We can make a has_part relationship between telopode and telocyte once this is in place.

**Comment by lubianat** [comment]
Thank you, David. I have added a NTR on GO's tracker: https://github.com/geneontology/go-ontology/issues/21973 . 
I think connective tissue cell would be probably safer, I go with that too.

**Comment by gouttegd** [comment]
It seems GO has added `telopode` (geneontology/go-ontology#21974), so from the comments above it looks like what remains to be done here is to:

- [ ] add the `has_part` relationship with the new GO term;
- [ ] change the parent to `connective tissue cell` (CL:0002320);
- [ ] fix the conflict against master;

and then this is ready for merge?

(No pressure, just your shepherd trying to tend his flock…)

**Comment by lubianat** [comment]
@gouttegd Thank you for the shepherding :) I am not sure how to add new GO terms to CL (I guess it is similar to UBERON terms, but idk). Also, I imagine there is a GO release cycle or something, right? I wonder if the term is already "visible" from within CL

**Comment by paolaroncaglia** [comment]
Hi @lubianat ,

> I imagine there is a GO release cycle or something, right?

Yes, monthly. The latest release date is shown on the top right at http://geneontology.org/, and more detail is available at http://geneontology.org/docs/downloads/. I'm not sure how the general import of GO into CL works, whether it has to be triggered manually, and whether specific wanted terms need to be manually added to a list...? @matentzn @dosumis thanks :-)

**Comment by matentzn** [comment]
Here are the instructions in our shiny new docs: https://obophenotype.github.io/cell-ontology/odk-workflows/UpdateImports.html

**Comment by lubianat** [comment]
@gouttegd I've tried to make the suggested modifications (sorry for the long delay). 
I am not quite sure on the next steps, can you help here with your outstanding shepherding? :)

**Comment by gouttegd** [comment]
The last modifications look good to me.

Do you know how to resolve Git conflicts? There are three that need to be fixed before we can merge.

**Comment by lubianat** [comment]
> The last modifications look good to me.
> 
> Do you know how to resolve Git conflicts? There are three that need to be fixed before we can merge.
> 
> If you don’t, ping me on Slack and I can guide you through it.

Wow, I am so sorry this took that long. I am not really sure how to solve ontology git conflicts, as these are often too large to fix manually. 

I'll get back to this this week and see what needs to be fixed.

**Comment by gouttegd** [comment]
@lubianat I’ve refreshed the imports to fix the failed CI check. I think this is now ready to merge, unless anyone objects I’ll do that sometimes next week.

**Pull request merged**
