### PR TITLE
Uberon import uberon 8410037

### PR DESCRIPTION
**Pull request by shawntanzk**
@matentzn there is a whole lot of `rdf:datatype="http://www.w3.org/2001/XMLSchema#string` diffs, not sure if this is something that needs to be looked into.

### CODE REVIEW

**Review by paolaroncaglia — COMMENTED** [review]
Hi @shawntanzk ,
Many thanks for doing this. Like you, I'm not sure if the large diff is ok, so let's hear from @matentzn ... Thank you both!
Paola

**Comment by shawntanzk** [comment]
good news: the obsolete test is working
bad news: there seems to be some obsolete terms that is causing checks to fail - does this need to be fixed in uberon? 

make: *** [test_obsolete] Error 1
is_a: GO:0044464 ! obsolete cell part
intersection_of: composed_primarily_of CL:0000124 ! obsolete glial cell (sensu Nematoda and Protostomia)
relationship: composed_primarily_of CL:0000124 ! obsolete glial cell (sensu Nematoda and Protostomia)
relationship: composed_primarily_of GO:0044464 ! obsolete cell part
relationship: has_component GO:0044464 {minCardinality="2"} ! obsolete cell part
cl.Makefile:286: recipe for target 'test_obsolete' failed
Error: Process completed with exit code 2.

**Comment by matentzn** [comment]
@shawntanzk please simply delete the label from the uberon import - manually. Hacking the modules was one of the things I was doing at the CL release. Basically you will have to hack this until we manage to update all ontologies - the fallout came from a significant change in RO. I would:
1. Make the change
2. run `sh run.sh make test IMP=false PAT=false` until it passes.
3. Push back up

**Comment by shawntanzk** [comment]
@matentzn managed to clear the obsolete GO term but there is an obsolete CL term and I'm not seeing it in uberon import, was wondering if I need to clear it from somewhere else? 

robot --catalog catalog-v001.xml convert --input cl.owl --check false -f obo  -o cl.obo.tmp.obo && grep -v ^owl-axioms cl.obo.tmp.obo > cl.obo && rm cl.obo.tmp.obo
! grep "! obsolete" cl.obo
intersection_of: composed_primarily_of CL:0000124 ! obsolete glial cell (sensu Nematoda and Protostomia)
make: *** [test_obsolete] Error 1
relationship: composed_primarily_of CL:0000124 ! obsolete glial cell (sensu Nematoda and Protostomia)
cl.Makefile:286: recipe for target 'test_obsolete' failed

**Comment by matentzn** [comment]
If the `master` branch is not broken atm, just keep deleting stuff from the uberon module until this passes - this is what I did. There is no other good way to solve this now because of all the cyclic dependencies..

**Comment by matentzn** [comment]
If you want you can ping me on slack, and we can just hash stuff out there really quick. Its a bit of a hackery.

**Comment by shawntanzk** [comment]
oh sorry, found it, im stupid, searched for CL: instead of CL_

**Comment by shawntanzk** [comment]
YAY! its finally passed :) happy to merge this down after I get a thumbs up @matentzn @paolaroncaglia :) 
Cause the diff is insanely large here's what I changed:
1) remove obsolete label for GO:0044464
2) changed CL:0000124 to CL:0000125 (glial cell)

**Review by matentzn — APPROVED** [review]

**Comment by paolaroncaglia** [comment]
> YAY! its finally passed :) happy to merge this down after I get a thumbs up @matentzn @paolaroncaglia :)

Thanks very much @shawntanzk and @matentzn !

**Pull request merged**
