### PR TITLE
Addresses #1712 [Typo/Bug] ttp://www.geneontology.org/formats/oboInOwl#created_by

### PR DESCRIPTION
**Pull request by bvarner-ebi**
Addresses obophenotype/caro#36 [Typo/Bug] ttp://www.geneontology.org/formats/oboInOwl#created_by

### CODE REVIEW

**Comment by shawntanzk** [comment]
wait, why is this in merged_import? doing changes in merged_import directly will not last, it will end up being changed back once we refresh it, we need to trace the source of the typo

**Comment by shawntanzk** [comment]
This comes from CARO: https://ontobee.org/ontology/CARO?iri=http://purl.obolibrary.org/obo/CARO_0020003 <- you can see it here, will open a ticket there instead

**Comment by bvarner-ebi** [comment]
> This comes from CARO: https://ontobee.org/ontology/CARO?iri=http://purl.obolibrary.org/obo/CARO_0020003 <- you can see it here, will open a ticket there instead

I made the changes in cl-edit.owl using Protégé. Thanks for finding the source of the typo.
Should this PR just be closed without merging?

**Comment by shawntanzk** [comment]
Closing PR as this is a CARO issue, have moved the ticket there

**Pull request closed without merging**
