### PR TITLE
add taxon restraint to CL:0000411 flatworm hypodermal cell

### LINKED ISSUE #1070: [Logical def] Add TC to CL:0000411 flatworm hypodermal cell
**CL term**
CL:0000411 flatworm hypodermal cell
"An epithelial cell of the hypodermis of flatworms." 
(has Wbbt xref)

**Suggested revision of logical definition**
Add taxon constraint only_in Platyhelminthes

Thanks.

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
close #1070

### CODE REVIEW

**Review by paolaroncaglia — COMMENTED** [review]
Hi @nicolevasilevsky ,
I just recalled the recent discussion on using in_taxon instead of only_in_taxon, see the April 26th discussion here
https://docs.google.com/document/d/1XvMbNvr0FEsdqGhg79BYCYEHSqUxRHMcvhbGizEAht8/edit and the ticket here https://github.com/oborel/obo-relations/issues/459.
I'm attending a talk atm so I couldn't go through the entire ticket thread - bottom line, which of the 2 should we use? Thanks again! :-)

**Comment by nicolevasilevsky** [comment]
Chris said in https://github.com/oborel/obo-relations/issues/459#issuecomment-832283522
>So the choice is

> 1. We make only-in-taxon functional and use that instead of in-taxon - everywhere
> 2. We leave as is, use in-taxon and not have it be functional, and rely on GCIs being present
I don't think 3 (status quo) is a viable option.

> Deciding between 1 and 2 is a complex engineering tradeoff, but I think 2 is the winner

So I think we should use 'in taxon'.

I updated this - thanks @paolaroncaglia!

**Comment by cmungall** [comment]
consistency is best. Continue to use RO_0002162 as that is what is being used in other axioms in this ontology. So this is OK to merge

If and when we change to RO_0002160 we will do as one single sweep. But note this is non-trivial. See https://github.com/oborel/obo-relations/issues/459

btw there are spurious diffs but let's merge anyway

I added this to the taxon project

**Comment by nicolevasilevsky** [comment]
I will merge, thanks @cmungall!

**Pull request merged**
