### PR TITLE
Add Axl+ dendritic cell

### PR DESCRIPTION
**Pull request by lubianat**
Related to issue #764.

I was not able to think about a logical definition, maybe @addiehl or @masciam have suggestions?

### CODE REVIEW

**Comment by bvarner-ebi** [comment]
FYI @shawntanzk

**Comment by shawntanzk** [comment]
2 things need to be added:

- [ ] in_taxon some homo_sapien 
- [ ] expresses AXL, expresses SIGLEC6 <- CL uses PRO atm despite inaccuracy of protein vs gene (might be related to this PR https://github.com/obophenotype/cell-ontology/pull/901)

**Comment by lubianat** [comment]
@shawntanzk in_taxon some homo_sapien is inferred from subclassOf "dendritic cell, human", isn't it?

**Comment by shawntanzk** [comment]
@lubianat - sorry, my bad, youre right :)

**Comment by bvarner-ebi** [comment]
@lubianat, checking in on this PR. It has no reviewers and seems to have no activity for several months. Can you merge or close?

**Comment by lubianat** [comment]
@bvarner-ebi thanks! @shawntanzk pointed I should add some way of saying the cell expresses the genes. How should I do that, though? 

I think both proteins are present in the plasma membrane at some point, but is there a more general way that does not depend on the protein in the plasma membrane?

**Comment by shawntanzk** [comment]
> @bvarner-ebi thanks! @shawntanzk pointed I should add some way of saying the cell expresses the genes. How should I do that, though?

```
expresses some PR:000001928
expresses some PR:000004528
```

Let me know if you need help adding those in the PR obo slim :)

**Comment by lubianat** [comment]
@shawntanzk  I don't know what you mean by "OBO slim", I'm sorry

**Comment by lubianat** [comment]
By PR you mean Protein Ontology or Pull Request? lol

**Comment by shawntanzk** [comment]
> @shawntanzk I don't know what you mean by "OBO slim", I'm sorry

ah yeah, we really need to document this. 
Basically PR ontology is too big, so we have a obo slim version where we add terms we care about: https://github.com/obophenotype/pro_obo_slim
We import that instead of the whole PR, so new terms might have to be added there before we import them into CL. 
if this isn't urgent, give me some time to write docs
carpal tunnel is killing me a bit atm, so writing full docs sounds painful >.<

**Comment by lubianat** [comment]
@shawntanzk Not urgent for me; take care of your carpal tunnel! It looks a bit cumbersome, so I'll wait for the docs. Thanks!

**Comment by bvarner-ebi** [comment]
@lubianat, it's been a while since I did this, but here are my notes on adding PRO terms to CL after @shawntanzk helped me do this. 
If you try this, can you let us know how it goes? If successful, they can be added to documentation...

- Add desired PR term to **[seed.txt](https://github.com/obophenotype/pro_obo_slim/blob/master/seed.txt)** in [pro_obo_slim](https://github.com/obophenotype/pro_obo_slim)
- Open docker
- Open terminal
- Navigate (`cd`) to the main directory in pro_obo_slim
- Run `sh odk.sh make all`
- Make a pull request and merge all updates - can merge this without review
- In the cell-ontology repo, create a branch
- Add PRO term to [src/ontology/imports/pr_terms.txt](https://github.com/obophenotype/cell-ontology/blob/master/src/ontology/imports/pr_terms.txt)
- Go to terminal, navigate to [cell-ontology/src/ontology](https://github.com/obophenotype/cell-ontology/tree/master/src/ontology)
- Run `sh run.sh make mirror/pr.owl -b`
(Note: `-b` forces command to run even if the mirror is up-to-date)
- Run `sh run.sh make imports/merged_import.owl`
- Open Protégé. The PRO term should now be available for modelling 
END

**Comment by lubianat** [comment]
@Thank you bvarner! 

We should have a simpler way to automate all of that... 

My step-by-step: 

After having Docker installed and configured: 

- Clone https://github.com/obophenotype/pro_obo_slim. 
- Edit locally https://github.com/obophenotype/pro_obo_slim/blob/master/seed.txt to add the Protein Ontology terms desired. 
- Navigate (`cd`) to the main directory in pro_obo_slim
- Run `sh odk.sh make all` to download docker image and run code to update the Slim version of PR 

At this point I had to stop, because the diff has added ^^xsd:string statements. This is a known issue: 
 - https://obophenotype.github.io/cell-ontology/Fixing_xsdstring_diffs/
 
But I am not sure on how to do it for pro_obo_slim

**Comment by anitacaron** [comment]
Hi @lubianat, do you use macos? You can try 

```
sed -i '' -E "s/Annotation[(](oboInOwl[:]hasDbXref [\"][^\"]*[\"])[)]/Annotation(\1^^xsd:string)/g" pr_slim.owl
```

**Comment by bvarner-ebi** [comment]
@lubianat, if you merge this PR by end of day today, it can be incorporated for the next CL release, which is planned for tomorrow. Otherwise, it would go in a future release.

**Comment by bvarner-ebi** [comment]
Hi, @lubianat, can we close this PR? 
If there are pending tech issues, can you work with @anitacaron to resolve?

**Comment by bvarner-ebi** [comment]
@lubianat, thank you for the update.

May I suggest going forward to use the [new term request template](https://github.com/obophenotype/cell-ontology/issues/new?assignees=&labels=new+term+request&template=a_adding_term.md&title=%5BNTR%5D) and leaving it unassigned? 

That way you can still contribute to CL by providing content in the template and an editor can pick up the issue and manage the technical aspects of adding the term. It's an option to continue contributing to CL without navigating the potential technical hurdles.

For the sake of this ticket, I propose:
- [ ] close this PR without merging
- [ ] @lubianat: double-check #764 and confirm the content is correct
- [ ] once #764 is reviewed, assign the ticket to me, and I'll put it in my work queue to add (but may be low priority)

**Comment by dosumis** [comment]
Hi Tiago,

>This issue has already taken more than 2 years (!), while on Wikidata I could [add it as soon as I desired, taking in a couple minutes on June 2021](https://www.wikidata.org/w/index.php?title=Q107297674&action=history).

> This task, for example, requires a lot of memory usage; I am lucky to have 32 GB RAM in my work computer, 16 wouldn't cut it. It would be good if the hardware requirements were documented; I risked a crash in my PC and losing other stuff I am running.

I agree that this is completely ridiculous. I also think it is unnecessary.  You should be able to do your edits and hand this off to the technical team to do relevant updated before a release.

  There is a very simple fix for referring to terms not yet in imports - that is just add a new Class in Protege under root, pasting in the URL (https://oboacademy.github.io/obook/howto/update-import/#protege-based-declaration).    This has been discouraged in recent years because it can cause some pipeline issues, but that should not be something anyone outside of the technical team should need to worry about.  

Hope this helps,
David

**Comment by dosumis** [comment]
@anitacaron  to fix the PRO references on this ticket so that it can be merged.

**Comment by shawntanzk** [comment]
I'll handle it :)

**Comment by shawntanzk** [comment]
#gogoeditdiff

**Comment by shawntanzk** [comment]
I'm a bit worried about making a equiv axiom as i don't know how strong the markers are, so I just did subclasses instead, hope that is ok

**Pull request merged**
