### PR TITLE
Change memory T has_completed

### PR DESCRIPTION
**Pull request by shawntanzk**
related to https://github.com/obophenotype/cell-ontology/issues/1490#issuecomment-1063705251
Actual ticket needs closer look at -> this is only single case

### CODE REVIEW

**Comment by shawntanzk** [comment]
```
ERROR There are 5 unsatisfiable classes in the ontology.
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/CL_0001203
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/CL_0000907
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/CL_0000909
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/CL_0000913
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/CL_0001062
```

**Review by addiehl — COMMENTED** [review]
Why was [PATO:0001603](http://purl.obolibrary.org/obo/PATO_0001603) 'increased life span' used instead of [PATO:0001701](http://purl.obolibrary.org/obo/PATO_0001701) 'mature' for the CL:0000909 equivalent class axiom?

**Comment by shawntanzk** [comment]
> Why was [PATO:0001603](http://purl.obolibrary.org/obo/PATO_0001603) 'increased life span' used instead of [PATO:0001701](http://purl.obolibrary.org/obo/PATO_0001701) 'mature' for the CL:0000909 equivalence class axiom?

sorry this slipped my radar, @addiehl not too sure - this term was created that way awhile ago. Could you create a ticket requesting that change if it should be mature instead? want to avoid mixing multiple issues in a single ticket :) Other than that do you agree with the changes made? if so could you give a thumbs up please? thanks :)

**Comment by bvarner-ebi** [comment]
Hi, @shawntanzk, can this PR be merged and/or closed? 
Appears to be pending review from @dosumis or @addiehl.

**Comment by shawntanzk** [comment]
yes needs review by them
btws just realised I didn't reply this from @addiehl 

> Why was [PATO:0001603](http://purl.obolibrary.org/obo/PATO_0001603) 'increased life span' used instead of [PATO:0001701](http://purl.obolibrary.org/obo/PATO_0001701) 'mature' for the CL:0000909 equivalence class axiom?

No idea, but this doesn't involve this ticket, and if changes need to be made on this, I would prefer it if another ticket was opened and discussion on that there :) thanks

**Comment by shawntanzk** [comment]
> This PR has not seen any activity in the past month; if nobody comments or reviews it in the next week, the PR editor will be allowed to proceed with merging without explicit approval, should they wish to do so.

Given this, I will merge this in, if there is any other issues, please open a new ticket. Thanks

**Pull request merged**
