### PR TITLE
revise label for supporting cell

### LINKED ISSUE #1329: Revise label of CL:0000630 supportive cell?
**CL term**
CL:0000630 supportive cell

**Description of typo, bug or error**
"A cell whose primary function is to support other cell types."
As a non-native English speaker, this is one of my favourite CL terms. But shouldn't the primary label be 'supporting cell', with 'supportive cell' as a synonym? The current label seems very little used in literature. Even the BTO term that it xrefs to is named 'supporting cell', and all subtypes in CL are labelled 'supporting' or 'support', e.g. 'supporting cell of carotid body'.
Note that if we rename the grouping class, we should also revise definitions containing "supportive cell". Thanks.

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
close #1329

### CODE REVIEW

**Review by shawntanzk — APPROVED** [review]

**Review by paolaroncaglia — CHANGES_REQUESTED** [review]
Hi @nicolevasilevsky ,
Thank you for taking this ticket! It all looks good to me, except that I'd retain the "support/supportive" strings as synonyms, rather than remove them altogether. I find it a helpful ontology practice for users. The synonym scope could be exact in this case, or related in the case of "supportive" if one's very picky, but I'd go for exact. Sorry I didn't mention it explicitly in my request. Thank you!

**Comment by nicolevasilevsky** [comment]
Hi @paolaroncaglia I did change the old labels to exact synonyms, I didn't delete them.

Is something else missing?

Thanks!

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky all is good - sorry I missed that! Thanks!

**Comment by nicolevasilevsky** [comment]
@paolaroncaglia can I go ahead and merge this? Or do we need more approvals?

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky I think it's fine, I'll merge. Thank you!

**Pull request merged**
