### PR TITLE
Addresses #1811 NTR 'respiratory ciliated cell'

### PR DESCRIPTION
**Pull request by bvarner-ebi**
Addresses #1811 NTR 'respiratory ciliated cell'

### CODE REVIEW

**Comment by aleixpuigb** [comment]
Maybe you could also add CL:0002332 'ciliated cell of the bronchus' as a subclass of 'respiratory ciliated cell'

**Comment by bvarner-ebi** [comment]
> Maybe you could also add CL:0002332 'ciliated cell of the bronchus' as a subclass of 'respiratory ciliated cell'

Thanks for the review, @aleixpuigb. Please see modelling below. CL:0002332 'ciliated cell of the bronchus' is a grandchild of  'respiratory ciliated cell'.

Screenshot 2023-01-25 at 16 09 03

Question for @dosumis: Should 'ciliated cell of the bronchus' be inferred as a direct subclass of 'respiratory ciliated cell'? If I do **not** assert that 'ciliated columnar cell of tracheobronchial tree' is a subclass of 'respiratory ciliated cell', 'ciliated cell of the bronchus' is inferred as a direct subclass. 

If I do assert that 'ciliated columnar cell of tracheobronchial tree' is a subclass of 'respiratory ciliated cell' (like I do in this PR), 'ciliated cell of the bronchus' is a grandchild of 'respiratory ciliated cell'. 

Is this expected behaviour?

**Review by aleixpuigb — APPROVED** [review]

**Comment by bvarner-ebi** [comment]
@dosumis, do you have any feedback on this PR, specifically [this comment](https://github.com/obophenotype/cell-ontology/pull/1819#issuecomment-1403874415)? 

If there is no concern or response by end of week, I plan to merge.

**Comment by dosumis** [comment]
#gogoeditdiff

**Comment by dosumis** [comment]
FOr terms with potentially large logical implications like this, I think it is important to run #gogoeditdiff and look at the results in the reasoned diff.  (Don't know if this works on merge PRs -  If it does, a GitHub action will post comments on this PR at some point)

**Comment by dosumis** [comment]
Hmmm -  it's run but seems to be giving results that are nothing to do with the PR.

**Pull request merged**
