### PR TITLE
adding embryonic and fetal/neonatal skeletal muscle fibers; adding ne…

### LINKED ISSUE #979: [NTR] embryonic skeletal muscle fiber and neonatal skeletal muscle fiber
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term labels:**
embryonic skeletal muscle fiber
neonatal skeletal muscle fiber

**Synonyms**

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
- embryonic: A skeletal muscle fiber found in an embryo. In mammalian embryos, skeletal muscle expresses myosin heavy chain-embryonic (MyHC-emb, encoded by the MYH3), which regulates skeletal muscle development. PMID:7196501|PMID:32094117.
- neonatal: A skeletal muscle fiber found at the fetal and neonatal stages. In mammalian fetuses and neonates, skeletal muscle expresses myosin heavy chain-neonatal (MyHC-neo, encoded by the MYH8 gene). This expression disappears shortly after birth and is replaced by expression of adult heavy chain myosins. PMID:7196501|PMID:26180627.

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
- both: [skeletal muscle fiber](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0008002)
- _develops from_ [skeletal muscle myoblast](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000515)

- embryonic: [embryonic cell](https://www.ebi.ac.uk/ols/ontologies/cl/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0002321)

How to relate stages?
- embryonic: [embryo stage](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0000068)
- neonatal: [neonate stage](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0007221)

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
- [skeletal muscle tissue](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001134)

**Your nano-attribution (ORCID)**
0000-0003-2034-601X

**Any additional notes or concerns**
Not sure how to relate developmental stage.

### PR DESCRIPTION
**Pull request by mkeays**
…onate stage and perinatal stage to Uberon import (fixes #979)

Not completely sure if relationships to developmental stages are correct but they make sense to me!

### CODE REVIEW

**Review by paolaroncaglia — CHANGES_REQUESTED** [review]
Hi @mkeays ,
In this case, I think that the subclass assertions would be safe as equivalence axioms, for both terms. I.e. 
embryonic skeletal muscle fiber = equivalent to 'skeletal muscle fiber' and ('existence starts and ends during' some 'embryonic stage'); same for the other term.
In addition, for 'fetal and neonatal skeletal muscle fiber', the axiom you suggest implies that the fiber exists at all times during both fetal and neonatal stages. If that's the intended meaning, then I think your suggestion would work, but I'd like to have confirmation from @dosumis please. Thanks.

**Comment by mkeays** [comment]
OK great, I can change to `Equivalent To` -- I'm never quite sure when to use which.

Yes, my understanding is that the fetal/neonatal type is present from the fetal stage (after embryonic but before birth) and up to some short time after birth (in humans about 1 month according to [this](https://skeletalmusclejournal.biomedcentral.com/articles/10.1186/s13395-015-0046-6) -- this is based on the type of myosin heavy chains they express.

**Comment by matentzn** [comment]
I have resolved the conflicts with the master branch but I don't know what the action items are here.

It seems to me that the term was already edited on a different branch, so please be very careful before merging.

**Comment by paolaroncaglia** [comment]
@dosumis @matentzn 

> I have resolved the conflicts with the master branch but I don't know what the action items are here.
> 
> It seems to me that the term was already edited on a different branch, so please be very careful before merging.

Thanks Nico. Maria was working on this right before going on mat leave, and I'm afraid that David and I didn't get a chance to review before she left, so the PR was probably left pending because of that. Possibly safer to wait until either Maria or David are back to confirm about the terms/edits.

**Comment by paolaroncaglia** [comment]
Closing and re-doing, see https://github.com/obophenotype/cell-ontology/issues/979#issuecomment-1047003395.

**Pull request closed without merging**
