### PR TITLE
Fixes #2776 - respiratory suprabasal cell textual definition 

### LINKED ISSUE #2776: [Text def] Respiratory suprabasal cell
**CL term**
Respiratory suprabasal cell 

**Current definition**

A respiratory epithelial cell with topographic nuclear position in between the basal and luminal cell of the airway epithelium. This non-basal, intermediate cell has limited proliferative capacity, ultrastructural features of basal cells and no defined features of the typically differentiated cellular phenotypes.

Improve textual defs using descriptions from LCN 

**Suggested def**

A respiratory epithelial cell derived from basal cells, with a topographic nuclear position between the basal and luminal cells of the airway epithelium. This non-basal, intermediate progenitor cell has limited proliferative capacity and the potential to differentiate into multiciliated, secretory, and rare airway cells (ionocytes, tuft, neuroendocrine). It shares some ultrastructural features with basal cells but lacks the defined features of the typically differentiated cellular phenotypes.

PMID: [37834236](https://pubmed.ncbi.nlm.nih.gov/37834236/)
PMID: 34044844
PMID: 35387001

**Comment**

LCN comment micro : By scRNA-seq, suprabasal cells derived from the human nasal epithelium are distinct from found in the trachea and airway epithelium (Deprez et al. 2020). Additional scRNA-seq studies have identified suprabasal cell heterogeneity after culture (Ruiz Garcia et al. 2019).

### PR DESCRIPTION
**Pull request by Caroline-99**
Fixes #2776 Updated the textual definition to include information from the Lung Atlas Jamboree

### CODE REVIEW

**Comment by Caroline-99** [comment]
#gogoeditdiff

**Comment by Caroline-99** [comment]
#gogoeditdiff

**Comment by Caroline-99** [comment]
#gogoeditdiff

**Review by JABelfiore — APPROVED** [review]
Amends look good!

**Pull request merged**
