### PR TITLE
Fixes #734

### LINKED ISSUE #734: obsolete 'lobed nucleus'
I'm trying to update GO to use cl-base (see https://github.com/geneontology/go-ontology/issues/19984). Unsatisfiabilities are fixed by the new Uberon release, but now I am running into an inferred equivalence between two 'lobed nucleus' classes.

CL [lobed nucleus](http://purl.obolibrary.org/obo/CP_0000025) and GO [lobed nucleus](http://purl.obolibrary.org/obo/GO_0098537) have identical logical definitions. Could CL obsolete CP:0000025 in favor of the GO term? As a side note, CP is not a registered OBO prefix (there are some [GO problems like this](https://github.com/geneontology/go-ontology/issues/19535) as well); it seems like that should be addressed.

### PR DESCRIPTION
**Pull request by dosumis**
Can you check I obsoleted properly?  Haven't done this in ages.

### CODE REVIEW

**Review by addiehl — APPROVED** [review]

**Review by nicolevasilevsky — CHANGES_REQUESTED** [review]
Looks good, not sure why the build failed, I'll look into it.

Only suggestion - add a comment to explain the reason for obsoletion, and we can also link to the GitHuub ticket with the 'seeAlso' annotation. Not sure if that is commonly done in CL, we do that in Mondo, and I think it's very handy.

**Comment by dosumis** [comment]
Seems to be failing due to no label rule being triggered by declaration of GO term + not running imports.

FAIL Rule ../sparql/nolabels-violation.sparql: 1 violation(s)
cls
http://purl.obolibrary.org/obo/GO_0098537

I'll update imports to fix, but wondering whether we should relax the constraint to only work on non imported terms.   Having this means the increasingly common scenario of adding a new Uberon term will => pull request check fail even though most new editors we train will not be running import updates.  @matentzn ?

**Comment by dosumis** [comment]
Hmmm.... This is annoying:

I tried to update imports/GO_import.owl alone and got a bunch of pattern schema check fails

```
./run.sh make imports/go_import.owl
cl.Makefile:107: warning: overriding recipe for target 'cl-simple.owl'
Makefile:231: warning: ignoring old recipe for target 'cl-simple.owl'
cl.Makefile:115: warning: overriding recipe for target 'cl-simple.obo'
Makefile:159: warning: ignoring old recipe for target 'cl-simple.obo'
cl.Makefile:126: warning: overriding recipe for target 'cl-basic.owl'
Makefile:244: warning: ignoring old recipe for target 'cl-basic.owl'
cl.Makefile:139: warning: overriding recipe for target 'cl-basic.obo'
Makefile:164: warning: ignoring old recipe for target 'cl-basic.obo'
--2020-09-19 08:36:43--  http://purl.obolibrary.org/obo/upheno/patterns/abnormalAnatomicalEntity.yaml
Resolving purl.obolibrary.org (purl.obolibrary.org)... 52.3.123.63
Connecting to purl.obolibrary.org (purl.obolibrary.org)|52.3.123.63|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/obophenotype/upheno/master/src/patterns/dosdp-patterns/abnormalAnatomicalEntity.yaml [following]
--2020-09-19 08:36:43--  https://raw.githubusercontent.com/obophenotype/upheno/master/src/patterns/dosdp-patterns/abnormalAnatomicalEntity.yaml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.16.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.16.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1254 (1.2K) [text/plain]
Failed to rename ../patterns/dosdp-patterns/abnormalAnatomicalEntity.yaml to ../patterns/dosdp-patterns/abnormalAnatomicalEntity.yaml.1: (2) No such file or directory
Saving to: ‘../patterns/dosdp-patterns/abnormalAnatomicalEntity.yaml’

abnormalAnatomicalEntity.yaml                               100%[=========================================================================================================================================>]   1.22K  --.-KB/s    in 0s      

2020-09-19 08:36:43 (32.5 MB/s) - ‘../patterns/dosdp-patterns/abnormalAnatomicalEntity.yaml’ saved [1254/1254]

FINISHED --2020-09-19 08:36:43--
Total wall clock time: 0.5s
Downloaded: 1 files, 1.2K in 0s (32.5 MB/s)
/tools//simple_pattern_tester.py:96: UserWarning: Checking ../patterns/dosdp-patterns/cellPartOfAnatomicalEntity.yaml
  warnings.warn("Checking %s" % pattern_doc)
/tools//simple_pattern_tester.py:23: UserWarning: deque(['additionalProperties']) => Additional properties are not allowed ('examples' was unexpected) => []
  str(e.context)]))
/tools//simple_pattern_tester.py:96: UserWarning: Checking ../patterns/dosdp-patterns/abnormalAnatomicalEntity.yaml
  warnings.warn("Checking %s" % pattern_doc)
/tools//simple_pattern_tester.py:96: UserWarning: Checking ../patterns/dosdp-patterns/abnormalCell.yaml
  warnings.warn("Checking %s" % pattern_doc)
/tools//simple_pattern_tester.py:75: UserWarning: equivalentTo.text has values ({'abnormal cell'}) not found in owl entity dictionaries t ({'bearer of', 'quality'}): 
  % (field.full_path, str(quoted.difference(owl_entities)), str(owl_entities)))
/tools//simple_pattern_tester.py:96: UserWarning: Checking ../patterns/dosdp-patterns/cellBearerOfQuality.yaml
  warnings.warn("Checking %s" % pattern_doc)
/tools//simple_pattern_tester.py:96: UserWarning: Checking ../patterns/dosdp-patterns/cellCapableOfSensoryPerception.yaml
  warnings.warn("Checking %s" % pattern_doc)
/tools//simple_pattern_tester.py:23: UserWarning: deque(['additionalProperties']) => Additional properties are not allowed ('example' was unexpected) => []
  str(e.context)]))
/tools//simple_pattern_tester.py:96: UserWarning: Checking ../patterns/dosdp-patterns/cellHasPlasmaMembranePartX.yaml
  warnings.warn("Checking %s" % pattern_doc)
/tools//simple_pattern_tester.py:96: UserWarning: Checking ../patterns/dosdp-patterns/glandularEpithelialCellPartOfAnatomicalEntity.yaml
  warnings.warn("Checking %s" % pattern_doc)
/tools//simple_pattern_tester.py:96: UserWarning: Checking ../patterns/dosdp-patterns/taxonSpecific.yaml
  warnings.warn("Checking %s" % pattern_doc)
Traceback (most recent call last):
  File "/tools//simple_pattern_tester.py", line 98, in <module>
    pattern = ryaml.load(file.read())
  File "/usr/local/lib/python3.6/dist-packages/ruamel/yaml/main.py", line 343, in load
    return constructor.get_single_data()
  File "/usr/local/lib/python3.6/dist-packages/ruamel/yaml/constructor.py", line 111, in get_single_data
    node = self.composer.get_single_node()
  File "_ruamel_yaml.pyx", line 706, in _ruamel_yaml.CParser.get_single_node
  File "_ruamel_yaml.pyx", line 724, in _ruamel_yaml.CParser._compose_document
  File "_ruamel_yaml.pyx", line 775, in _ruamel_yaml.CParser._compose_node
  File "_ruamel_yaml.pyx", line 889, in _ruamel_yaml.CParser._compose_mapping_node
  File "_ruamel_yaml.pyx", line 775, in _ruamel_yaml.CParser._compose_node
  File "_ruamel_yaml.pyx", line 891, in _ruamel_yaml.CParser._compose_mapping_node
  File "_ruamel_yaml.pyx", line 904, in _ruamel_yaml.CParser._parse_next_event
ruamel.yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 34, column 3
did not find expected key
  in "<unicode string>", line 34, column 36
Makefile:459: recipe for target 'pattern_schema_checks' failed
make: *** [pattern_schema_checks] Error 1
```

If this is current default ODK behaviour, I think we need a discussion on ODK.  If possible, updating imports should be independent of checks.

**Comment by matentzn** [comment]
My changes to this branch did not fix this? someone merged broken patterns into master.. I thought I fixed them and added the changes here.

**Comment by matentzn** [comment]
yes i think travis does not run the pattern check pipeline..

**Comment by dosumis** [comment]
@matentzn - The GO import file is updated and the label of the new term is visible in Protege, but the build is still failing on 

FAIL Rule ../sparql/nolabels-violation.sparql: 1 violation(s)
cls
http://purl.obolibrary.org/obo/GO_0098537

Does that mean that adding new imported terms by adding declarations to the -edit file is no longer a viable workflow?  I think it would be better if it was, as this is easy to teach to editors and they can use the results immediately.

**Comment by matentzn** [comment]
This has been a test from way before we started working on ODK - the solution is to refresh the import; but I also dont like that this test is so general.. It is more important that it is run on the terms in the CL namespace.

**Comment by dosumis** [comment]
Well - that turned into a bit of a saga.  For some reason (Protege version?) this differs from the master wrt data type declaration on def xrefs.  This makes the diffs massive.    For the record, here's a ROBOT diff: 

```diff
6 axioms in Ontology 1 but not in Ontology 2:
- AnnotationAssertion(rdfs:label <http://purl.obolibrary.org/obo/CP_0000025> "lobed nucleus"^^xsd:string)
- EquivalentClasses(<http://purl.obolibrary.org/obo/CL_0000041> ObjectIntersectionOf(<http://purl.obolibrary.org/obo/CL_0000771> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000051> <http://purl.obolibrary.org/obo/CP_0000025>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000051> <http://purl.obolibrary.org/obo/PR_000007152>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000051> <http://purl.obolibrary.org/obo/PR_000007857>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000051> <http://purl.obolibrary.org/obo/PR_000007858>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000051> <http://purl.obolibrary.org/obo/PR_000014046>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000051> <http://purl.obolibrary.org/obo/PR_000014047>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000051> <http://purl.obolibrary.org/obo/PR_000022006>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002104> <http://purl.obolibrary.org/obo/PR_000009129>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002215> <http://purl.obolibrary.org/obo/GO_0002495>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002215> <http://purl.obolibrary.org/obo/GO_0002540>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002215> <http://purl.obolibrary.org/obo/GO_0045730>)) )
- EquivalentClasses(<http://purl.obolibrary.org/obo/CL_0000043> ObjectIntersectionOf(<http://purl.obolibrary.org/obo/CL_0000767> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000051> <http://purl.obolibrary.org/obo/CP_0000025>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002215> <http://purl.obolibrary.org/obo/GO_0002349>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002215> <http://purl.obolibrary.org/obo/GO_0002351>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002215> <http://purl.obolibrary.org/obo/GO_0002830>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002215> <http://purl.obolibrary.org/obo/GO_0008015>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002215> <http://purl.obolibrary.org/obo/GO_0032616>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002215> <http://purl.obolibrary.org/obo/GO_0032633>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002215> <http://purl.obolibrary.org/obo/GO_0048295>)) )
- EquivalentClasses(<http://purl.obolibrary.org/obo/CL_0000096> ObjectIntersectionOf(<http://purl.obolibrary.org/obo/CL_0000775> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000051> <http://purl.obolibrary.org/obo/CP_0000000>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000051> <http://purl.obolibrary.org/obo/CP_0000025>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000051> <http://purl.obolibrary.org/obo/GO_0070820>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002104> <http://purl.obolibrary.org/obo/PR_000001256>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002104> <http://purl.obolibrary.org/obo/PR_000001257>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002104> <http://purl.obolibrary.org/obo/PR_000001456>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002104> <http://purl.obolibrary.org/obo/PR_000001483>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002104> <http://purl.obolibrary.org/obo/PR_000001879>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002104> <http://purl.obolibrary.org/obo/PR_000001944>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002104> <http://purl.obolibrary.org/obo/PR_000007597>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002215> <http://purl.obolibrary.org/obo/GO_0002536>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002215> <http://purl.obolibrary.org/obo/GO_0002690>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002215> <http://purl.obolibrary.org/obo/GO_0006909>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002215> <http://purl.obolibrary.org/obo/GO_0032637>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/cl#lacks_part> <http://purl.obolibrary.org/obo/PR_000009978>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/cl#lacks_part> <http://purl.obolibrary.org/obo/PR_000010543>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/cl#lacks_part> <http://purl.obolibrary.org/obo/PR_000010799>)) )
- EquivalentClasses(<http://purl.obolibrary.org/obo/CP_0000025> ObjectIntersectionOf(<http://purl.obolibrary.org/obo/GO_0005634> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0000053> <http://purl.obolibrary.org/obo/PATO_0001979>)) )
- SubClassOf(<http://purl.obolibrary.org/obo/CP_0000025> <http://purl.obolibrary.org/obo/GO_0005634>)

8 axioms in Ontology 2 but not in Ontology 1:
+ AnnotationAssertion(<http://purl.obolibrary.org/obo/IAO_0100001> <http://purl.obolibrary.org/obo/CP_0000025> "http://purl.obolibrary.org/obo/GO_0098537"^^xsd:anyURI)
+ AnnotationAssertion(owl:deprecated <http://purl.obolibrary.org/obo/CP_0000025> "true"^^xsd:boolean)
+ AnnotationAssertion(rdfs:comment <http://purl.obolibrary.org/obo/CP_0000025> "Obsoleted because duplicate with GO term.")
+ AnnotationAssertion(rdfs:label <http://purl.obolibrary.org/obo/CP_0000025> "obsolete lobed nucleus"^^xsd:string)
+ AnnotationAssertion(rdfs:seeAlso <http://purl.obolibrary.org/obo/CP_0000025> "https://github.com/obophenotype/cell-ontology/issues/734")
+ EquivalentClasses(<http://purl.obolibrary.org/obo/CL_0000041> ObjectIntersectionOf(<http://purl.obolibrary.org/obo/CL_0000771> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000051> <http://purl.obolibrary.org/obo/GO_0098537>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000051> <http://purl.obolibrary.org/obo/PR_000007152>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000051> <http://purl.obolibrary.org/obo/PR_000007857>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000051> <http://purl.obolibrary.org/obo/PR_000007858>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000051> <http://purl.obolibrary.org/obo/PR_000014046>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000051> <http://purl.obolibrary.org/obo/PR_000014047>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000051> <http://purl.obolibrary.org/obo/PR_000022006>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002104> <http://purl.obolibrary.org/obo/PR_000009129>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002215> <http://purl.obolibrary.org/obo/GO_0002495>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002215> <http://purl.obolibrary.org/obo/GO_0002540>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002215> <http://purl.obolibrary.org/obo/GO_0045730>)) )
+ EquivalentClasses(<http://purl.obolibrary.org/obo/CL_0000043> ObjectIntersectionOf(<http://purl.obolibrary.org/obo/CL_0000767> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000051> <http://purl.obolibrary.org/obo/GO_0098537>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002215> <http://purl.obolibrary.org/obo/GO_0002349>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002215> <http://purl.obolibrary.org/obo/GO_0002351>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002215> <http://purl.obolibrary.org/obo/GO_0002830>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002215> <http://purl.obolibrary.org/obo/GO_0008015>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002215> <http://purl.obolibrary.org/obo/GO_0032616>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002215> <http://purl.obolibrary.org/obo/GO_0032633>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002215> <http://purl.obolibrary.org/obo/GO_0048295>)) )
+ EquivalentClasses(<http://purl.obolibrary.org/obo/CL_0000096> ObjectIntersectionOf(<http://purl.obolibrary.org/obo/CL_0000775> ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000051> <http://purl.obolibrary.org/obo/CP_0000000>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000051> <http://purl.obolibrary.org/obo/GO_0070820>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/BFO_0000051> <http://purl.obolibrary.org/obo/GO_0098537>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002104> <http://purl.obolibrary.org/obo/PR_000001256>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002104> <http://purl.obolibrary.org/obo/PR_000001257>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002104> <http://purl.obolibrary.org/obo/PR_000001456>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002104> <http://purl.obolibrary.org/obo/PR_000001483>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002104> <http://purl.obolibrary.org/obo/PR_000001879>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002104> <http://purl.obolibrary.org/obo/PR_000001944>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002104> <http://purl.obolibrary.org/obo/PR_000007597>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002215> <http://purl.obolibrary.org/obo/GO_0002536>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002215> <http://purl.obolibrary.org/obo/GO_0002690>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002215> <http://purl.obolibrary.org/obo/GO_0006909>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/RO_0002215> <http://purl.obolibrary.org/obo/GO_0032637>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/pr#lacks_part> <http://purl.obolibrary.org/obo/PR_000009978>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/pr#lacks_part> <http://purl.obolibrary.org/obo/PR_000010543>) ObjectSomeValuesFrom(<http://purl.obolibrary.org/obo/pr#lacks_part> <http://purl.obolibrary.org/obo/PR_000010799>)) )
```

**Pull request merged**
