### PR TITLE
NTR-pro-opiomelanocortin-neuron

### LINKED ISSUE #2443: [NTR] pro-opiomelanocortin neuron
Please check that the term does not already exist by using the ontology search tool OLS:
https://www.ebi.ac.uk/ols4/ontologies/cl

**Preferred term label**

**Synonyms** (add reference(s), please)

**Definition** (free text, with reference(s), please. PubMed ID format is PMID:XXXXXX)

**Parent cell type term** (check the hierarchy here https://www.ebi.ac.uk/ols4/ontologies/cl)

**Anatomical structure where the cell type is found** (check Uberon for anatomical structures: https://www.ebi.ac.uk/ols4/ontologies/uberon)

**Your ORCID**

**Additional notes or concerns**

### PR DESCRIPTION
**Pull request by AvolaAmg**
Fixes #2443 
NTR-pro-opiomelanocortin-neuron

### CODE REVIEW

**Comment by AvolaAmg** [comment]
#gogoeditdiff

**Review by JABelfiore — DISMISSED** [review]

**Comment by dosumis** [comment]
#gogoeditdiff

Looks good.  

I think interesting to look at neuropeptide annotation of clusters in whole brain datasets  We have this for Siletti.   Not much annotation to look at in annotations, but dissections potentially informative - note hypothalamus population which could fit with the cells you describe. But also other populations that don't. 


cell_set_accession | cell_label | cell_fullname | parent_cell_set_accession | parent_cell_set_name | labelset | Cluster ID | Class auto_annotation | Neurotransmitter auto_annotation | Neuropeptide auto_annotation | Top three regions | Top three dissections | Top Enriched Genes
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
CS202210140_337 | Splat_336 |   | CS202210140_483 | Splatter | Cluster | 336 | NEUR | VGLUT2 VGLUT3 | AGT CBLN CCK CHGA CHGB GAL NAMPT   NPPC NTS NUCB NXPH POMC SCG SST UBL proSAAS | Midbrain: 91.5%, Thalamus: 8.1%,   Medulla: 0.3% | Human SN-RN: 59.7%, Human PAG:   18.3%, Human CM-Pf: 7.7% | NKX6-1, FAM83B, ASAH2,   LINC00261, EBF3, SIM1, ONECUT1, FOXA2, AC024230.1, AC079148.3
CS202210140_338 | Splat_337 |   | CS202210140_483 | Splatter | Cluster | 337 | NEUR | GABA | CALCB CHGA CHGB IGF NAMPT NPPC   NUCB NXPH PNOC POMC PYY SCG UBL VGF proSAAS | Basal forebrain: 81.9%,   Midbrain: 17.6%, Hypothalamus: 0.5% | Human GPi: 53.9%, Human GPe:   26.4%, Human SN: 16.1% | ONECUT1, ASAH2, AC016044.1,   LHX1-DT, KANK4, LINC00922, LINC02520, ZNF676, LHX1, MARCHF11-AS1
CS202210140_354 | Splat_353 |   | CS202210140_483 | Splatter | Cluster | 353 | NEUR | GABA | CBLN CHGA CHGB NAMPT NMB NPB NPY   NUCB NXPH PENK PNOC POMC SCG TAC UBL VGF proSAAS | Thalamus: 97.2%, Midbrain: 2.2%,   Hypothalamus: 0.5% | Human LG: 93.9%, Human VLN: 1.4%,   Human CM-Pf: 1.1% | GATA3, FABP4, HPGD, LHX5-AS1,   NPY, GATA3-AS1, LINC00237, AC096751.2, AL138899.1, NDNF
CS202210140_432 | Splat_431 |   | CS202210140_483 | Splatter | Cluster | 431 | NEUR | HDC VGLUT2 | CART CBLN CHGA CHGB KISS NAMPT   NPPC NUCB NXPH PENK POMC SCG TAC UBL VGF proSAAS | Hypothalamus: 99.7%, Midbrain:   0.2%, Cerebral cortex: 0.0% | Human MN: 57.0%, Human   HTHma-HTHtub: 14.2%, Human HTHso-HTHtub: 13.8% | PGR, TBX3, PGR-AS1, AC004870.4,   AC026765.3, CALCR, POMC, NR5A2, ESR1, C14orf39

**Comment by dosumis** [comment]
We could stick with these classical defs for now and wait for any further characterisation of NP expressing neurons.  Alternatively, we could keep a general term for "pro-opiomelanocortin-neuron" and add region specific subclasses for neurons in the hypothalamus and brainstem that you mention in your def.  

Thoughts?

**Review by JABelfiore — APPROVED** [review]

**Comment by dosumis** [comment]
> @dosumis I agree with creating an intermediate term for neurons in the hypothalamus and then make 'pro-opiomelanocortin-neuron' one of its subclass.
see ticket https://github.com/obophenotype/cell-ontology/issues/2719 I will add a new grouping term specifically for these cell types

My suggestion is that "pro-opiomelanocortin-neuron" be a general term for neurons expressing this NP and to make subclasses for e.g. pro-opiomelanocortin neuron of hypothalamus.  A general term for 'neuron of hypothalamus' sounds too abstract to be useful.

**Comment by AvolaAmg** [comment]
Neurons of the hypothalamus are neurons of the neuroendocrine system 
There are specific neurons that are only in the hypothalamus and have a function related to the regulation of hormones and diet.
I can provide you a literature review of those and a list of neurons.
Otherwise let me know how you want me to proceed.

**Comment by dosumis** [comment]
> There are specific neurons that are only in the hypothalamus and have a function related to the regulation of hormones and diet.

I'm very happy to add those specific neuron types, just wondering how useful the grouping term is.  As mentioned in call last week, I am concerned that the classical definitions of "{some neuropeptide}-neuron" will soon be very out of date as we find much broader expression of these NPs.

**Pull request merged**
