### PR TITLE
Refreshing imports 2023-02-17

### PR DESCRIPTION
**Pull request by bvarner-ebi**
Refreshing imports 2023-02-17

Steps taken:

- Open Docker

In terminal:
-  `cd Git/obophenotype/cell-ontology/src/ontology`
- `sh run.sh make imports/merged_import.owl  `

### CODE REVIEW

**Comment by bvarner-ebi** [comment]
Of note, all GO changes are not being reflected.
For example, compare EA for GO:0005227 in CL vs GO.

**Comment by matentzn** [comment]
See slack, try again using 

```
sh run.sh make refresh-merged
```

**Comment by bvarner-ebi** [comment]
> See slack, try again using
> 
> ```
> sh run.sh make refresh-merged
> ```

Unfortunately, this does not seem to make a difference.

**Comment by matentzn** [comment]
I will deal with this now separately.

**Pull request closed without merging**
