### PR TITLE
Added Upper FS BC PV

### LINKED ISSUE #876: [NTR] Upper FS Basket cell (Mus MOp)
Note - please check that the term does not already exist (check OLS: https://www.ebi.ac.uk/ols/ontologies/cl)

**Preferred term label:**
Upper fast-spiking basket Pvalb GABAergic interneuron of the primary motor cortex (Mus musculus)

**Synonyms**
Upper FS BC PV MOp (Mus)

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
A Pvalb GABAergic cortical interneuron in upper L5 and L2/3 of the primary motor cortex that have strong layer-adapting morphology, classical L2/3 basket morphology in L2/3, and mostly large basket cell morphology in upper L5. They are Fast spiking with some showing delayed firing with large latency.
PMID:26612957
PMID:18568015

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
GABAergic interneuron

**What is the anatomical structure that the cell is a part of? Please check Uberon: https://www.ebi.ac.uk/ols/ontologies/uberon**
http://purl.obolibrary.org/obo/UBERON_0001384 - Primary Motor Cortex
*has some soma location, can specify layer

**Your nano-attribution (ORCID)**

**Any additional notes or concerns**
subclass of Pvalb interneurons #868

### PR DESCRIPTION
**Pull request by shawntanzk**
Fixes #876

### CODE REVIEW

**Review by patrick-lloyd-ray — COMMENTED** [review]
I would prefer a more descriptive label, but if it's clear to others, I'm okay with it.

**Comment by shawntanzk** [comment]
My difficulty with this group is that they are quite varied. See Pvalb Egfem1, Pvalb Gpr149, Pvalb Kank4, Pvalb Calb1_1, and Pvalb Calb1_2 in [the Nature paper table
](https://www.nature.com/articles/s41586-020-2907-3/tables/1). What I did was find the commonality between the descriptions and put that down, hence a bit less descriptive.

**Review by patrick-lloyd-ray — COMMENTED** [review]
Makes sense!

**Comment by dosumis** [comment]
Hold up on this one until we have more discussion of electrophysiological groupings. If we are happy with differentium 'upper fast spiking' this needs to be in the first sentence of the text def.  These are so morphologically variable, I'd drop morphology details from the def altogether.  Strong case for making subtypes by morphology.

**Comment by patrick-lloyd-ray** [comment]
I would like to have a discussion about the strategy for these ephys groupings as well.

**Pull request closed without merging**
