### PR TITLE
Add check to flag when a PMID is associated with anything other than dbxref

### LINKED ISSUE #1354: Add check to flag when a PMID is associated with anything other than dbxref
annotations starting with PMID: should only ever be dbxrefs
Related to #1353

### PR DESCRIPTION
**Pull request by anitacaron**
Fixes #1354

### CODE REVIEW

**Comment by anitacaron** [comment]
Do I also fix the problem with this PR? How could I proceed? Delete all the wrong entries?

**Comment by shawntanzk** [comment]
@anitacaron looks like only 5 violations, happy to go take a look at them manually :) I think it's probably just tagged wrongly on something, but I'll check

**Comment by shawntanzk** [comment]
yeah its also my mistake :p i did a stupid >.< sorry

**Comment by shawntanzk** [comment]
Should all be fixed, 3/5 were mine >.< hahahhahaa! im really glad we have this check now

**Review by shawntanzk — APPROVED** [review]

**Review by paolaroncaglia — APPROVED** [review]

**Pull request merged**
