### PR TITLE
Add CL_0009020 (fetal hepatobiliary progenitor cell)

### PR DESCRIPTION
**Pull request by paolaroncaglia**
Addresses #840

### CODE REVIEW

**Comment by paolaroncaglia** [comment]
@dosumis 
@cmungall 
Asking for your opinion please on whether "part of some liver bud" is appropriate (it was the best I could find).
Also, is there any way to indicate that the synonym "HHyP cell" is an abbreviation? That way I'd feel more comfortable in having it as an exact synonym.
Thanks,
Paola

**Comment by dosumis** [comment]
May be borderline whether 'liver bud' is suitable.  Wikipedia has this has liver bud as 'reabsorbed in tubular structures of the septum transversum by the eighth week. [2]'.  Found this for ductal plate:

image - in https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5385778/ 

From these two sources, it sounds like ductal plate may be a later structure than liver bud.  Either way, it should be added to Uberon.

If adding term is urgent then I think OK for now as long as we have an uberon ticket for 'ductal plate' and another CL ticket to update this term when the more accurate Uberon term is available.

Agree would be good to have standard way to record that a synonyms in an abbreviation using synonym type.  Is there any precedent in Uberon for this?

**Comment by paolaroncaglia** [comment]
Note for self, I'll use UBERON:8410003 ductal plate (created today but not released yet).

**Comment by matentzn** [comment]
- [ ] I resolved conflicts here, @paolaroncaglia please review again (I used an id from my own range because your ID was already used for something else).
- [ ] Paola assign someone as `Assignee`

**Comment by paolaroncaglia** [comment]
Hi @matentzn ,

>     * [ ]  I resolved conflicts here, @paolaroncaglia please review again (I used an id from my own range because your ID was already used for something else).
> 
>     * [ ]  Paola assign someone as `Assignee`

I'm really sorry, looks like my old PR was a duplicate and I had already committed the relevant edits since. I forgot to close it. I usually am quite careful but this one slipped. Apologies Nico, I'll double-check now and close as necessary.

**Pull request closed without merging**
