### PR TITLE
fix auditory hair cell issues

### LINKED ISSUE #1264: Make 'auditory system neuron' broader.
**CL term**

auditory hair cell
http://purl.obolibrary.org/obo/CL_0000202
A mechanoreceptor cell located in the inner ear that is sensitive to auditory stimuli. The accessory sensory structures are arranged so that appropriate stimuli cause movement of the hair-like projections (stereocilia and kinocilia) which relay the information centrally in the nervous system. [ MESH:A08.663.650.250 ]

image

**Description of problem**

1. CL terms like links to Uberon
2. This definition is, like many in CL,  has a very strong mammalian/human bias.  Auditory hair cells exist in other contexts in vertebrates
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3023005/

**Suggested solution**

Broaden the meaning of 'auditory hair cell' to cover all hair cells with an auditory function.  Question - should we keep the link to ear - assuming this is meant in a broad sense?   Make a new, more specific class for 'cochlea auditory hair cell' with part_of relationship to 'spiral organ of cochlea':

Equivalent to:
'auditory hair cell' and part_of some 'spiral organ of cochlea'

### PR DESCRIPTION
**Pull request by shawntanzk**
Fixes #1264

Note: the change in uberon import file is removing subclass of 'ear hair cell' - this is done now (instead of just importing it into uberon and making a release) as uberon release is a bit broken at the moment, should not be a problem.

### CODE REVIEW

**Review by rays22 — APPROVED** [review]
The changes in definition and relationships, as well as the new class make sense to me.

**Comment by gouttegd** [comment]
Is there any roadblock here? @shawntanzk Are you waiting for a second review on top of @rays22 ’s one? (@dosumis maybe?)

**Comment by shawntanzk** [comment]
> Is there any roadblock here? @shawntanzk Are you waiting for a second review on top of @rays22 ’s one? (@dosumis maybe?)

yes, waiting for @dosumis review as I'm not 100% sure I did what he requested in the ticket correctly

**Comment by dosumis** [comment]
@shawntanzk - made some edits myself.  Please check.

**Comment by shawntanzk** [comment]
currently, auditory hair cell has subclassof ear hair cell, that is from uberon_import though so I think it's just an import issue. For now I will remove the axiom but basically need the whole imports refresh etc. to fix in the end

**Pull request merged**
