### PR TITLE
removing cruft from DPs #450

### PR DESCRIPTION
**Pull request by cmungall**
See #450﻿

### CODE REVIEW

**Comment by matentzn** [comment]
Ok this PR just deletes a bunch of patterns.. Not sure I am clear about the entire context - are these patterns redundant?

**Comment by cmungall** [comment]
It looks like they were just taken from the patternizer (can you confirm @nicolevasilevsky ), which is an automated process lacking intuition or domain. They were at odd levels of abstraction

**Comment by nicolevasilevsky** [comment]
Yes, I agree, these were all probably created by patternizer, with the exception of abnormalAnatomicalEntity, which looks like maybe it was created during the POTATO workshop in Cambridge? Or sometime after with the folks from the POTATO working group.

**Review by nicolevasilevsky — APPROVED** [review]

**Comment by matentzn** [comment]
Abnormal anatomical entity does not belong here and needs to be deleted. Probably an oversight.

**Pull request merged**
