### PR TITLE
mge-derived-cortical-interneuron-hierarchy

### LINKED ISSUE #2428: [Class hierarchy] CGE and MGE cortical interneurons have no children
This may have been broken.  We should add subClassOf: develops_from some MGE/CGE axioms to all relevant cortical interneurons to => automated classification. 
```[tasklist]
### Tasks
- [ ] Declare the medial ganglionic GABAergic interneuron term obsolete CL:4023069
- [ ] Revise the definition of mge derived interneurons t-types and add adjust their hierarchy
```

### PR DESCRIPTION
**Pull request by AvolaAmg**
fixes #2428

### CODE REVIEW

**Comment by Caroline-99** [comment]
#gogoeditdiff

**Comment by dosumis** [comment]
Updated to use inferred classification #gogoeditdiff

**Comment by dosumis** [comment]
@AvolaAmg  - it would be good to add refs supporting MGE origin, + some note on evidence in comment. This will make it easier for future editors to understand and work with, as well as being potentially useful to users.

**Comment by dosumis** [comment]
Also wondering what the status is on moving some of these to T-types - particularly SST CHODL to move out from under SST.

**Comment by Caroline-99** [comment]
#gogoeditdiff

**Comment by Caroline-99** [comment]
@AvolaAmg The classification looks good. The only suggestion I have is to align the textual defs with the logical ones (if you want). ie. sst GABAergic cortical interneuron: A GABAergic neuron that develops from medial ganglionic eminence and is located in the cerebral cortex. The interneuron expresses somatostatin (sst) and secretes gamma-aminobutyric acid.

**Comment by AvolaAmg** [comment]
@Caroline-99 thank you Caroline! all done, see next commit!

**Comment by AvolaAmg** [comment]
#gogoeditdiff

**Review by Caroline-99 — APPROVED** [review]

**Pull request merged**
