### PR TITLE
Obsolete inhibitory and excitatory neuron

### PR DESCRIPTION
**Pull request by shawntanzk**
Fixes https://github.com/obophenotype/cell-ontology/issues/1540

### CODE REVIEW

**Comment by shawntanzk** [comment]
@bvarner-ebi - I know you had an example on where glutamatergic neuron can be inhibitory - would you mind adding it to the comment in the obsolete excitatory neuron please (or just give a description here and I'll add it in) would like to give an example of what to look out for like i did with inhibitory neuron. Thanks!

**Comment by bvarner-ebi** [comment]
Hi @shawntanzk, 

https://www.ncbi.nlm.nih.gov/books/NBK11526/ (see section on metabotropic glutamate receptors)

https://openbooks.lib.msu.edu/neuroscience/chapter/vision-the-retina/ (see section "ON bipolar cells"... "In ON bipolar cells, the glutamate released by the photoreceptor is inhibitory. ON bipolar cells express metabotropic glutamate receptors."

**Comment by shawntanzk** [comment]
ah I used to work on mGluRs in my MSc - they are more on the receptors that can be inhibitory, but I guess its the issue as what we mentioned before - technically the receptors controls the excitatory/inhibitory nature, yet we call the secreting neuron glutamatergic neuron.

**Review by gouttegd — APPROVED** [review]
Looks good to me.
Just one question: on the corresponding ticket you mentioned that we should “check if any downstream [consumer] is affected first”. If you did check that maybe mention it in the PR, so that there’s a trace of it.

**Review by patrick-lloyd-ray — APPROVED** [review]
LGTM.

**Pull request merged**
