### PR TITLE
remove "not" in CL

### LINKED ISSUE #1693: find all "Not" in CL
grep "ObjectComplementOf" in cl-edit and find what they are 
Not should not be allowed in CL -> ELK doesn't deal with this

### PR DESCRIPTION
**Pull request by shawntanzk**
Fixes #1693
Changed taxon restrictions to annotation never_in_taxon - @matentzn not sure if CL pipelines deal with expansion of this or is that uberon specific? Removed some equiv classes
PS sorry for asking so many reviewers - thought it might be something that everyone on the reviewer list might want to go through :) 

PS I love how the automated diff in simple file vs unreasoned show how the "not" is not being used by a reasoner :D

### CODE REVIEW

**Comment by matentzn** [comment]
- [ ] Do not merge this PR without a positive review from _both_ @cmungall and @dosumis

**Review by dosumis — APPROVED** [review]
Looks good to me.

**Comment by cmungall** [comment]
I was confused looking at this then I realized the "reasoned" view is actually a composition of expanded and reasoned.

I was going to say this PR should update the editors docs on TCs too but looks like we don't have any!

go ahead and merge

**Review by cmungall — APPROVED** [review]

**Comment by shawntanzk** [comment]
> I was going to say this PR should update the editors docs on TCs too but looks like we don't have any!

Can do a redirect here: https://oboacademy.github.io/obook/explanation/taxon-constraints-explainer/ and https://oboacademy.github.io/obook/howto/add-taxon-restrictions/

**Pull request merged**
