### PR TITLE
2021-12-16 release including standard simple and basic files generated from ODK

### PR DESCRIPTION
**Pull request by anitacaron**
Related to #1380

### CODE REVIEW

**Review by matentzn — APPROVED** [review]
Great work @anitacaron 

I would sleep better if @shawntanzk could check out this branch and:

- [ ] open cl-basic.owl to spot oddities (just screen the top level(s)
- [ ] open cl-simple.owl to spot oddities
- [ ] click through the diff in GitHub Desktop

Otherwise this is good to go!

@shawntanzk you can also merge this after that without getting back to me (unless they are questions) and make a new release. Remember, the tag must be the tag @anitacaron gave to the ontology. Thank you both!

**Comment by shawntanzk** [comment]
Will do after I deal with PCL release >.< can barely get anything done atm with computer working extra hard

**Comment by matentzn** [comment]
Zero rush on this!

**Comment by shawntanzk** [comment]
I'm not sure if this is of concern - 
Screenshot 2021-12-17 at 16 26 07
Also due to the huge diff - its hard to really write release notes like previously

**Comment by matentzn** [comment]
The large diff is only this once. cant you just use the diff on cl-base.obo for writing the notes?

**Comment by matentzn** [comment]
The CP terms in the diff are expected - this would take care of it: https://github.com/obophenotype/cell-ontology/pull/1311

next release!

**Comment by shawntanzk** [comment]
only weird looking thing is the CP classes, other than that looks alright

v2021-12-16 release

Edits:
	- Change 'supportive' & 'support' to 'supporting' in labels for various cells
	- Edit label of mesenchymal stem cell of adipose tissue
	- Merged fusimotor neuron to CL:0008037
	- Merged neuron of cerebral cortex to CL:0010012
	- Fixed some minor errors with xref formats

New Terms:
	- endothelial cell of placenta
	- smooth muscle cell of placenta
	- endothelial cell of hepatic portal vein
	- endothelial cell of uterus
	- alveolar type 1 fibroblast cell
        - alveolar type 2 fibroblast cell

**Pull request merged**
