### PR TITLE
Addresses #2154 [NTR-cxg] cortical region-agnostic L2/3-6 intratelencephalic projecting glutamatergic cortical neuron (by layer)

### PR DESCRIPTION
**Pull request by bvarner-ebi**
Addresses #2154 [NTR] cortical region-agnostic L2/3-6 intratelencephalic projecting glutamatergic cortical neuron (by layer)

#gogoeditdiff

### CODE REVIEW

**Comment by bvarner-ebi** [comment]
@anitacaron, any advice on why this is failing QC?

```
fastobo-validator cl-check.obo
     Parsing `cl-check.obo`
      Failed parsing `cl-check.obo`
             --> cl-check.obo:31176:10
              |
        31176 | xref: An intratelencephalic-projecting glutamatergic neuron with a soma found in cortical layer 5. {xref="PMID:37292694", xref="PMID:37609206"}␊
              |          ^---
              |
              = expected EOL or QuotedString
make: *** [cl.Makefile:190: obocheck] Error 1
```

**Comment by anitacaron** [comment]
I checked on Protégé, and you're using `database_cross_reference` instead of `definition` annotation 😃 
The two new terms with issue are CL:4030064 and CL:4030065.

Screenshot 2023-10-13 at 08 55 20

**Comment by bvarner-ebi** [comment]
#gogoeditdiff

**Review by aleixpuigb — APPROVED** [review]
No breaking changes noted.

**Pull request merged**
