### PR TITLE
Unmerge has characteristic and has participant ranges temporarily

### PR DESCRIPTION
**Pull request by matentzn**
Will be undone by https://github.com/obophenotype/cell-ontology/issues/1376

- [x] Can you check out this branch and recreate `no-mirror-refresh-merged`? @shawntanzk 
- [x] Then open in protege and check unsats

### CODE REVIEW

**Comment by matentzn** [comment]
Then open in protege and check unsats

**Comment by shawntanzk** [comment]
no more unsats with after refreshing imports, looks good

**Comment by matentzn** [comment]
- [ ] before we merge this, can we make sure that there is a ticket in GO for the problems resulting from the `has characteristic` range? @rays22

**Comment by shawntanzk** [comment]
> * [ ]  before we merge this, can we make sure that there is a ticket in GO for the problems resulting from the `has characteristic` range? @rays22

there isn't one at the moment -happy to write one up

**Comment by matentzn** [comment]
Ok, basically you need to write an issue, nameing GO classes and sharing the screen shot of that explanation you shared with me on slack (the one pertaining to has characteristic). Tag @balhoff and me in the issue.

**Comment by shawntanzk** [comment]
done - ready to merge (brain freezes a bit when I wrote "merge" and saw "unmerge" in the title :p)

**Review by shawntanzk — APPROVED** [review]

**Comment by balhoff** [comment]
We do have a ticket at GO, for all problems with ranges: https://github.com/geneontology/go-ontology/issues/16524

**Comment by shawntanzk** [comment]
@balhoff sorry about that, not sure if it was exactly same issue etc. so created a new ticket and linked it to that one :)

**Comment by balhoff** [comment]
No problem, specific examples are good. The date on the other ticket is embarrassing 😳

**Comment by matentzn** [comment]
Ready to merge!

**Pull request merged**
