### PR TITLE
Addresses #1909 blood_and_immune_upper_slim

### PR DESCRIPTION
**Pull request by bvarner-ebi**
Addresses #1909 blood_and_immune_upper_slim

### CODE REVIEW

**Review by aleixpuigb — COMMENTED** [review]
All cell types in the list are present in the subset.

**Review by aleixpuigb — APPROVED** [review]

**Review by ubyndr — APPROVED** [review]

**Comment by anitacaron** [comment]
Is there a reason the slim URI doesn't follow the default using the cl namespace?

Current
`<http://purl.obolibrary.org/obo/blood_and_immune_upperslim>

Expected 

`<http://purl.obolibrary.org/obo/cl#blood_and_immune_upperslim>`

**Comment by bvarner-ebi** [comment]
Updates:

- relabelled upper slim URI
- Added https://github.com/obophenotype/cell-ontology/commit/80719a2e2c34d36c5b5edc754d79dba7f9c7f59a

@anitacaron, should I also remove the subset annotations that were added in Protégé?

**Comment by bvarner-ebi** [comment]
@anitacaron, thanks for processing the template.
From a technical standpoint, is this PR ready to be merged?

**Comment by dosumis** [comment]
@anitacaron - can you add the import statement?  Need to make sure this detail ends up in an SOP for editors to follow for future subsets.

**Pull request merged**
