### PR TITLE
Fix typo #1368

### PR DESCRIPTION
**Pull request by bvarner-ebi**
@dosumis, @paolaroncaglia, would you mind reviewing this correction related to issue #1368?

### CODE REVIEW

**Comment by bvarner-ebi** [comment]
Seeing many changes involving xsd:string like the following in the diff...

Screenshot 2021-12-16 at 08 23 12

Please confirm that these are expected.

**Comment by shawntanzk** [comment]
@bvarner-ebi follow this: https://obophenotype.github.io/cell-ontology/Fixing_xsdstring_diffs/ to remove string diffs :)

**Comment by dosumis** [comment]
@bvarner-ebi some background: this is an annoying bug that shows up sporadically.  It's been fixed in the OWL-API lib that causes it, but we're waiting for this fix to make it's way through to Protege. Until then, we need to use the fix @shawntanzk pointed to above.

**Comment by bvarner-ebi** [comment]
Thank you, @shawntanzk and @dosumis.
I'm going to delete this branch/PR and start again after running the fix.

**Comment by shawntanzk** [comment]
@bvarner-ebi you dont actually have to - you can just run the line and push that commit in - should work :) but up to your preference

**Pull request closed without merging**
