### PR TITLE
import UBERON:0001639

### LINKED ISSUE #1342: Please import UBERON:0001639 'hepatic portal vein'
Hi @shawntanzk ,
Could you please import UBERON:0001639 'hepatic portal vein' into CL? Or let me know if I should ask someone else.
Needed for https://github.com/obophenotype/cell-ontology/issues/932. 
Thanks!
Paola

### PR DESCRIPTION
**Pull request by shawntanzk**
Have checked to make sure that the old import issues didn't come back and looks good to me.
Happy for you to merge after you review. 
Thanks

Fixes #1342

### CODE REVIEW

**Comment by paolaroncaglia** [comment]
Thanks @shawntanzk ! I'll do as soon as the checks complete.

**Review by paolaroncaglia — COMMENTED** [review]
@shawntanzk 
uberon_terms.txt looks good. Just to confirm re. old import issue: uberon_import.owl says
"59,232 additions, 1,786 deletions"
but you said you've checked, so can I ignore? Thanks!

**Comment by shawntanzk** [comment]
@paolaroncaglia I've checked a couple of things in protege, doesn't look like anything is broken - should all be ok. Just if you want to go into protege to make sure that the new import didnt revert any stuff that we spent the last week fixing and all :) if not it should be good to merge

**Comment by paolaroncaglia** [comment]
Thanks @shawntanzk , I left a message on Slack. No rush.

**Pull request merged**
