### PR TITLE
Revise epithelial cell of cervix classification

### PR DESCRIPTION
**Pull request by Caroline-99**
This is the current classification of epithelial cell of the uterus. columnar cell of endocervix and squamous cell of ectocervix should be classified under the epithelial cell of cervix.

image

Actions taken:
-logical definitions for squamous cell of ectocervix and columnar cell of endocervix have been updated 
-changed the textual definition of squamous cell of ectocervix and added references 
-changed the textual definition of columnar cell of ectocervix and added references

### CODE REVIEW

**Comment by dosumis** [comment]
#gogoeditdiff

**Comment by dosumis** [comment]
You can delete some redundant subClassOf axioms:

e.g. these epithelial cell of uterus is redundant with inferred classification here 
image
part_of some endocervix is redundant with part_of some endocervical epithelium in EC axiom.

**Review by dosumis — APPROVED** [review]

**Comment by aleixpuigb** [comment]
#gogoeditdiff

**Comment by Caroline-99** [comment]
#gogoeditdiff

**Comment by Caroline-99** [comment]
#gogoeditdiff

**Review by aleixpuigb — APPROVED** [review]
It looks good!

**Pull request merged**
