### PR TITLE
Release with simple/basic

### PR DESCRIPTION
**Pull request by matentzn**
While we are waiting for ROBOT making a new release, I have reverted the basic and simple artefacts back to oort. Please review carefully; in particular whether the following snippet did what you expect:

```
KEEPRS=part_of develops_from
	
$(ONT)-basic.owl: $(ONT)-simple.owl
	owltools $< --make-subset-by-properties $(KEEPRS) -o -f owl $@
```

### CODE REVIEW

**Comment by dosumis** [comment]
cl-basic.obo headers look good.  Ontology loads fine in variuos tools.  

Potential issues:  
- Missing develops_from.  Maybe reference CURIES instead of shortnames.  develops_from is RO:0002202.  part_of actually not needed because all uses have Uberon as subject.
-  Includes disjoints - which earlier releases did not include these.  

```
commit d546f2812019be2af5b8dceb3bdf09b69b24db9b
Author: cmungall <cjm@berkeleybop.org>
Date:   Mon Jul 9 17:25:35 2018 -0700
```

If reciprocals are included, disjoints may cause the graph to include cycles,

to remove: `owltools ... --remove-axioms -t DisjointClasses`


Also - don't see a Makefile commit - need this ASAP in order to make releases.

**Comment by matentzn** [comment]
@dosumis can you take care of this: makefile changes are already on master

**Comment by dosumis** [comment]
> @dosumis can you take care of this: makefile changes are already on master

Ahh - didn't realise that.   Would follow a more conventional branch-merge approach for Makefile in future -  esp where some review required.   Will work on it myself now.

**Comment by matentzn** [comment]
Yeah the reason I put it there was that it was broken in other respects that needed immediate fixing; and I was a bit impatient so I did not split the other fixes I made from these here ones which really should have been on this branch. :P Sorry, wont happen again.

**Comment by dosumis** [comment]
Patched and rebuilt locally - but building release files failing because hanging during pattern build issue documented here:  https://github.com/obophenotype/cell-ontology/issues/566

Can you push  the changes you think fix this?

**Comment by matentzn** [comment]
Its this:

https://github.com/obophenotype/cell-ontology/blob/2e22cdabb28fd74257bfff2457a87ce7307d38a8/src/ontology/cl.Makefile#L59

**Comment by matentzn** [comment]
Are you sure its the exact same issue? Can you post the last lines of the output?

**Comment by matentzn** [comment]
I am on slack as well

**Comment by dosumis** [comment]
Sorry - was rushing.  Different error.  Seems to be some problem with CHEBI import.  WIll try again and report back.

**Comment by matentzn** [comment]
@dosumis its all done. Was a massive pain, but I think it should be fine now. I would say merge asap and we will deal with fallout later.

**Pull request merged**
