### PR TITLE
Adding validated, approved CellGuide patterns

### LINKED ISSUE #2081: Salivary gland cells, NTRs & Edits (LLM driven)
Cell Guide has draft cell type descriptions from ChatGPT
e.g. Acinar Cell Of Salivary Gland 
* On [OLS4](http://purl.obolibrary.org/obo/CL_0002623)
* On [Cell Guide](https://cellxgene.cziscience.com/cellguide/CL_0002623). 

CL def: An acinar cell of salivary gland.
CL parent class def: 

ChatGPT:

> Acinar cells of the salivary gland are a critical part of the oral physiology and the digestive mechanism. These specialized cells are concentrated towards the terminal ends of the salivary glands, where they form sac-like acini or clusters, giving them their name. They are amphicrine in nature, which means they play both secretory and endocrine roles.
> 
> The primary function of the acinar cells of the salivary gland is to manufacture and secrete saliva. This substance, comprised mainly of water, electrolytes, mucins, and enzymes, is vital for the initial stages of digestion and for the regular maintenance of oral health. The acinar cells produce the two main types of saliva: serous and mucinous. The serous type, predominantly produced by the parotid gland, contains the enzyme amylase responsible for the initial breakdown of complex carbohydrates. The mucinous type, more common in the submandibular and sublingual glands, contains mucin that aids in lubrication, facilitating the process of mastication and bolus formation.
> 
> Moreover, acinar cells also express and respond to various endocrine, paracrine, and autocrine hormones that govern the quantity and composition of the saliva produced. This implies sensitivity and modulation according to the internal and external environment, dietary habits, and even circadian rhythms. Impairment of acinar cells, whether due to damage or related to a systemic condition such as Sjögren's Syndrome, could disrupt the optimal functioning of the oral and digestive systems. In conclusion, acinar cells of the salivary gland, despite their diminutive size, have a substantial role in oral health and overall homeostasis.

This clearly needs curating for accuracy and the addition of references and some details may be too human-specific for CL or may better belong in an extended knowledge graph, but reading it also immediately suggests some obvious improvements we can make.

1. Having some more information about morphology location and function would make the def more useful.
1. There is currently no textual or logical connection to [saliva secretion](http://purl.obolibrary.org/obo/GO_0046541), but this can easily be added
2. We can add subtypes by function - serous & mucinous (it might be worth requesting more specific GO terms)
3. We could add subtypes by gland (parotid, submandibular and sublingual glands)
4. What evidence is there for endocrine function?  Is this sufficient to add additional links to GO via capable_of?

One way we could home in on some references is via another LLM-based resource, perplexity:

https://www.perplexity.ai/search/f5e5f8a6-cf6e-4b67-b28b-320173bc0725?s=c

> Acinar cells of salivary glands are essential for the production and secretion of saliva,  which plays a vital role in digestion and maintaining oral health. These cells are found in the salivary glands, including the parotid, submandibular, and sublingual glands [1](https://www.ncbi.nlm.nih.gov/books/NBK542251/). Acinar cells can be classified into two types: serous and mucinous [1](https://www.ncbi.nlm.nih.gov/books/NBK542251/). Serous acinar cells secrete an isotonic, protein-rich fluid, while mucinous acinar cells secrete mucin, a lubricant [1](https://www.ncbi.nlm.nih.gov/books/NBK542251/).

> The salivary glands are made up of lobules, with each lobule containing many secretory acinar cells that form rounded secretory units with a central duct [1](https://www.ncbi.nlm.nih.gov/books/NBK542251/) . Acinar cells initially produce an isotonic, plasma-like fluid that is further modified by duct cells through the reabsorption of most of the NaCl and secretion of KHCO3 [2](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4502782/) . Due to the ducts being relatively impermeable to water, the final saliva is hypotonic [2](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4502782/). Acinar cells are surrounded by myoepithelial cells, which display 4 to 8 processes that wrap around the acini and intercalated ducts [4](https://www.ncbi.nlm.nih.gov/books/NBK538325/). These myoepithelial cells rhythmically contract to squeeze saliva from the acinar units through the duct system and release it into the oral cavity [4](https://www.ncbi.nlm.nih.gov/books/NBK538325/). In addition to myoepithelial cells, acinar cells are also surrounded by an extracellular matrix, immune cells, stromal cells, myofibroblasts, and nerve fibers [4](https://www.ncbi.nlm.nih.gov/books/NBK538325/).

> The primary function of acinar cells is to regulate ion channel activity in various cellular domains to generate the appropriate fluid secretion in salivary gland [6](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4059182/) . The receptor-evoked Ca2+ signal in salivary gland acinar cells is unique in that it starts at the apical pole and then rapidly increases across the cell [6](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4059182/) . This polarized Ca2+ signal can be attributed to the polarized arrangement of Ca2+ channels, transporters, and signaling proteins [6](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4059182/)

The references may not be ideal primary refs - but typically have references to good primary refs.  This description also provides more detail on secretory mechanisms (which might suggest more GO links) as well as useful context and material for the structure and function of related cell types - the myoepithelial cells and duct cells of the salivary glands.

-----
Actions

- [x] #2171
- [x] #2172
- [ ] #2173
- [ ] Discuss SOP for using CellGuide/LLMs  to guide curation of cell types
- [ ] Outline strategy for using CellGuide to guide editor focus for single-cell project funded editors.
- [x] #2216

```[tasklist]
### Tasks
```

### PR DESCRIPTION
**Pull request by dosumis**
Fixes #2081 #2350

Tested locally & results look good in Protege.

Probably some more plumbing work needed to get this running automagically?

### CODE REVIEW

**Review by hkir-dev — APPROVED** [review]

**Comment by dosumis** [comment]
@aleixpuigb 

Some background - we promised to review and potentially integrate these definitions as part of our work for CZI. I think that there is enough useful content that it is worth folding this into CL.  I also think it is helpful for editor to be able to see these descriptions in the file while editing, as they often have useful additional content for definitions and links to CL.

Here is an example of added content.  Please review the boilerplate disclaimer text (this is from the DOSDP added by this PR)

image
image

**Comment by aleixpuigb** [comment]
Thanks for letting me know, David. I was checking if there was a consensus for adding them on the CL call (18/10/2023), but there was not. I am in favor to add them, and I am happy with the inclusion as a description with the disclaimer message. My only question is if this will be visualized in OLS.

**Comment by dosumis** [comment]
CC @Caroline-99

**Comment by dosumis** [comment]
> My only question is if this will be visualized in OLS.

All AP axioms show up in OLS.  If they're not part of the OBO core fields, they show up in the column on the right hand side.

**Comment by aleixpuigb** [comment]
I vote to add them, since it includes only curated definitions.

**Review by aleixpuigb — APPROVED** [review]

**Comment by dosumis** [comment]
Hi @hkir-dev  - I think this PR may have an a definitions.owl with all the CellGuide descriptions in whereas ExtendedDescriptions.tsv now only has reviewed.  Could you rebuild definitions.owl again so we can merge?
Thanks!

**Comment by hkir-dev** [comment]
It seems that `ExtendedDescription.tsv` haven't changed since the last build (last edit is 30 August). Can you commit your changes?

**Comment by dosumis** [comment]
> It seems that ExtendedDescription.tsv haven't changed since the last build (last edit is 30 August). Can you commit your changes?

Done.  (I'd forgotten that clashing definitions.owl builds were getting in the way of me pushing.  Cleaned up now)

**Comment by hkir-dev** [comment]
definitions.owl updated

**Pull request merged**
