### PR TITLE
Add CL:00001087 CD4+ TEMRA

### LINKED ISSUE #851: [NTR] CD4+ TEMRA
Per request of HIPC/Bjoern Peters for current data analysis needs.  The CD8+ version of this cell type was added previously #560, #110.  A few adjustments to synonyms for that [term](http://purl.obolibrary.org/obo/CL_0001062) are included as well.

**Preferred term label:**
effector memory CD4-positive, alpha-beta T cell, terminally differentiated

**Synonyms**
TEMRA [broad] PMID:17465678
CD4+ TEMRA [exact] PMID:17465678
CD4-positive TEMRA PMID:17465678

**Definition (free text, please give PubMed ID in format PMID:XXXXXX)**
A CD4-positive, alpha beta memory T cell with the phenotype CD45RA-positive, CD45RO-negative, and CCR7-negative.

PMID:17465678
PMID:26883338
PMID:27997758
PMID:29133794

**Parent cell type term (check the hierarchy here https://www.ebi.ac.uk/ols/ontologies/cl):**
CL:0000897 CD4-positive, alpha-beta memory T cell

**Your nano-attribution (ORCID)**
https://orcid.org/0000-0001-9990-8331

**additional annotations**
rdfs:comment "This cell type is seen human but not found in the mouse."

**equivalence axiom**
'CD4-positive, alpha-beta memory T cell'
 and ('has plasma membrane part' some 'receptor-type tyrosine-protein phosphatase C isoform CD45RA')
 and ('in taxon' some 'Homo sapiens')
 and (has_completed some 'memory T cell differentiation')
 and (lacks_plasma_membrane_part some 'receptor-type tyrosine-protein phosphatase C isoform CD45RO')
 and (lacks_plasma_membrane_part some 'C-C chemokine receptor type 7')

**Any additional notes or concerns**
Related changes to CL:0001062 effector memory CD8-positive, alpha-beta T cell, terminally differentiated

synonym changes
TEMRA [broad]
CD8+ TEMRA [exact]
CD8-positive TEMRA

axiom change
'in taxon' some 'Homo sapiens' rather than only_in_taxon some 'Homo sapiens'

### PR DESCRIPTION
**Pull request by addiehl**
Added CD4+ TEMRA and made CD8+ TEMRA changes Fixes #851

### CODE REVIEW

**Comment by paolaroncaglia** [comment]
@addiehl 
I noticed a minor typo in the comment "This cell type is seen human but not found in the mouse.",
should probably read "This cell type is seen _in_ human but not found in the mouse."
:-) Thanks

**Comment by addiehl** [comment]
Thanks for pointing out the typo.

**Comment by addiehl** [comment]
Fixed the typos for both CL:0001061 and CL:0001087 and committed/pushed the changes.

**Comment by addiehl** [comment]
Is Travis blocked for lack of funds?

**Comment by addiehl** [comment]
Unsure of the conflict here, since I added only one class and made fairly small changes to another.

**Pull request merged**
