### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by cthoyt**
This pull request is part of an initiative to make the licensing information about OBO Foundry ontologies more actionable.

While this ontology contains licensing information in its metadata, GitHub is not aware of the license unless you create a `LICENSE` file with standardized text. This PR creates a `LICENSE` file with the standard text for the CC BY 4.0 license. 

More information about this initiative and further discussion is taking place here: https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1840.

### CODE REVIEW

**Comment by shawntanzk** [comment]
@addiehl - tagging you and putting you as reviewer as you are the contact person for CL. Probably can just merge this in, but didn't want to do it without your thumbs up :) thanks

**Comment by addiehl** [comment]
Is the one failed check significant?

**Comment by cthoyt** [comment]
@addiehl seems irrelevant to this PR

**Comment by shawntanzk** [comment]
> Is the one failed check significant?

Nope - that just tries to post the diff. I think its cause of permissions on GitHub Token cause of the creator of the PR that disallows automated posting, but it isn't important to the PR

**Comment by addiehl** [comment]
Thanks Charles and Shawn

**Pull request merged**
