### PR TITLE
Adding normalisation documentation

### PR DESCRIPTION
**Pull request by shawntanzk**

### CODE REVIEW

**Comment by matentzn** [comment]
Do you want to try and edit the navigation as well?

https://github.com/obophenotype/cell-ontology/blob/master/mkdocs.yaml

**Comment by shawntanzk** [comment]
> Do you want to try and edit the navigation as well?

Done. Thanks! https://github.com/obophenotype/cell-ontology/blob/Adding-normalisation-documentation/mkdocs.yaml

**Review by matentzn — APPROVED** [review]
I hope the ^^ in the navigation is not a problem but shouldn't.

**Comment by shawntanzk** [comment]
> I hope the ^^ in the navigation is not a problem but shouldn't.

was thinking that too, but github didn't flag it so i assumed .yaml would be ok with it. Will see, if theres errors, I'll change the title to something else

**Pull request merged**
